-- ════════════════════════════════════════════════════════════════════════
-- Platform prerequisites — what a hosted Supabase project already has before
-- the first migration runs, expressed as a repo-owned artifact (21 Sep 2026)
--
-- WHY THIS FILE EXISTS
--
-- `supabase db reset` could not rebuild this database from the repository.
-- The migration history starts at 20260616120000_remote_baseline.sql, which
-- was itself generated by introspecting the live project — and introspection
-- records what the SCHEMA contains, not what the PLATFORM provided first.
-- Three classes of object were therefore missing from history:
--
--   1. roles          anon, authenticated, service_role, authenticator and
--                     the module's own dq_evaluator. Supabase creates the
--                     first four; dq_evaluator is ours, created by hand on
--                     10 Sep 2026 and never written down.
--   2. schemas        auth, extensions, vault, graphql_public.
--   3. extensions     and, specifically, WHERE they live. The baseline says
--                     `create extension supabase_vault with schema
--                     extensions`, but that extension insists on the schema
--                     `vault`, so a clean build failed on the very first
--                     migration. On the live project the extension already
--                     existed in `vault`, so `if not exists` never fired and
--                     nobody noticed.
--
-- This file is the missing half. It is NOT a migration: migrations run after
-- the platform has done its work, and re-running this against the hosted
-- project would be both unnecessary and unwelcome. It is the documented
-- starting point for a disposable or disaster-recovery database:
--
--     psql -f supabase/baseline/00_platform_prereqs.sql
--     psql -f supabase/baseline/10_missing_from_history.sql
--     then every file in supabase/migrations, in name order
--
-- scripts/db-rebuild.sh does exactly that and proves the result.
--
-- Everything here fills a GAP: it creates what is absent and steps over what
-- the platform already owns, so running it against a real Supabase database
-- changes nothing. Idempotent; safe to run twice.
-- ════════════════════════════════════════════════════════════════════════

-- ── 1 · roles ───────────────────────────────────────────────────────────────
-- The PostgREST roles a hosted project starts with, plus dq_evaluator, the
-- unprivileged role Data Quality runs rule SQL as (20260910140000 grants it
-- an allowlist but assumed the role already existed).
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then
    create role service_role nologin noinherit bypassrls;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticator') then
    create role authenticator login noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'supabase_admin') then
    create role supabase_admin superuser createrole createdb replication bypassrls login;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'supabase_auth_admin') then
    create role supabase_auth_admin nologin noinherit createrole;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'supabase_storage_admin') then
    create role supabase_storage_admin nologin noinherit createrole;
  end if;
  -- Data Quality's evaluator: no login, no inherit, nothing granted here.
  -- 20260919100000 decides what it may read.
  if not exists (select 1 from pg_roles where rolname = 'dq_evaluator') then
    create role dq_evaluator nologin noinherit;
  end if;
end $$;

do $$
begin
  execute 'grant anon, authenticated, service_role to authenticator';
exception when others then
  raise notice 'could not grant the PostgREST roles to authenticator (%), continuing', sqlerrm;
end $$;

-- ── 2 · schemas ─────────────────────────────────────────────────────────────
create schema if not exists extensions;
create schema if not exists auth;
create schema if not exists vault;
create schema if not exists graphql_public;

grant usage on schema extensions to anon, authenticated, service_role;
grant usage on schema public to anon, authenticated, service_role;
grant usage, create on schema public to dq_evaluator;

-- ── 2b · default privileges on the public schema ───────────────────────────
-- A hosted Supabase project ships with ALTER DEFAULT PRIVILEGES in place, so
-- every table, sequence and function a migration creates is automatically
-- reachable by the PostgREST roles. Without them a rebuilt database looks
-- complete and then refuses the service role on any table created after the
-- baseline — eleven of them here, including sync_batch, so staging failed
-- with "permission denied for table sync_batch" while every object existed.
--
-- These are the platform's defaults, reproduced. 20260910150000 then narrows
-- the FUNCTION defaults back down ("private by default"), exactly as it does
-- on the live project — so setting them here is what makes that migration
-- meaningful rather than a no-op.
alter default privileges in schema public grant all on tables    to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;
alter default privileges in schema public grant all on functions to anon, authenticated, service_role;

-- ── 3 · extensions, in the schemas they actually require ───────────────────
-- supabase_vault MUST live in `vault`; the 20260616 baseline asks for
-- `extensions`, and a clean build fails there. Installing it correctly first
-- turns that migration's `create extension if not exists` into a no-op,
-- which is exactly what happens on the live project.
create extension if not exists "pgcrypto"           with schema extensions;
create extension if not exists "uuid-ossp"          with schema extensions;
create extension if not exists "pg_stat_statements" with schema extensions;
create extension if not exists "pg_trgm"            with schema extensions;
do $$
begin
  if not exists (select 1 from pg_extension where extname = 'supabase_vault') then
    begin
      execute 'create extension supabase_vault with schema vault';
    exception when others then
      -- not every PostgreSQL build ships it; the modules that use Vault
      -- degrade to "no secret configured" rather than failing to install
      raise notice 'supabase_vault is not available here (%), continuing without it', sqlerrm;
    end;
  end if;
  if not exists (select 1 from pg_extension where extname = 'pg_net') then
    begin
      execute 'create extension pg_net with schema extensions';
    exception when others then
      raise notice 'pg_net is not available here (%), continuing without it', sqlerrm;
    end;
  end if;
end $$;

-- ── 4 · the Auth surface the schema depends on ─────────────────────────────
-- GoTrue owns auth.users on a hosted project: public.users has a foreign key
-- to it and dozens of row-security policies call auth.uid() / auth.jwt(). A
-- disposable or disaster-recovery database needs those to EXIST; it does not
-- need GoTrue itself.
--
-- On a real Supabase database the auth schema belongs to supabase_auth_admin
-- and we may not write into it — nor do we need to. Every statement below
-- runs only when its object is ABSENT, and a permission refusal is reported
-- and stepped over rather than failing the rebuild.
do $$
begin
  if to_regclass('auth.users') is null then
    create table auth.users (
      instance_id        uuid,
      id                 uuid primary key,
      aud                varchar(255),
      role               varchar(255),
      email              varchar(255),
      encrypted_password varchar(255),
      email_confirmed_at timestamptz,
      invited_at         timestamptz,
      last_sign_in_at    timestamptz,
      raw_app_meta_data  jsonb,
      raw_user_meta_data jsonb,
      is_super_admin     boolean,
      created_at         timestamptz default now(),
      updated_at         timestamptz default now()
    );
    comment on table auth.users is 'Stand-in for the GoTrue table, created by supabase/baseline/00_platform_prereqs.sql so the database can be rebuilt from the repository. On a hosted project GoTrue owns this table and this block does nothing.';
    raise notice 'created a stand-in auth.users (no GoTrue in this database)';
  end if;
exception when insufficient_privilege then
  raise notice 'the auth schema is owned elsewhere (GoTrue); auth.users is already there';
end $$;

do $$
begin
  execute 'grant usage on schema auth to anon, authenticated, service_role';
  execute 'grant select on auth.users to service_role';
exception when insufficient_privilege then
  raise notice 'the auth schema is owned elsewhere (GoTrue); leaving its grants alone';
end $$;

-- The helpers every row-security policy in the schema calls. The stand-ins
-- read the same GUC the platform's versions do, so policies behave
-- identically under `set local request.jwt.claims`.
do $$
declare v_made text := '';
begin
  if to_regprocedure('auth.jwt()') is null then
    execute 'create function auth.jwt() returns jsonb language sql stable as $f$'
         || 'select coalesce(nullif(current_setting(''request.jwt.claims'', true), '''')::jsonb, ''{}''::jsonb)$f$';
    v_made := v_made || 'auth.jwt() ';
  end if;
  if to_regprocedure('auth.uid()') is null then
    execute 'create function auth.uid() returns uuid language sql stable as $f$'
         || 'select nullif(auth.jwt() ->> ''sub'', '''')::uuid$f$';
    v_made := v_made || 'auth.uid() ';
  end if;
  if to_regprocedure('auth.role()') is null then
    execute 'create function auth.role() returns text language sql stable as $f$'
         || 'select coalesce(nullif(auth.jwt() ->> ''role'', ''''), ''anon'')$f$';
    v_made := v_made || 'auth.role() ';
  end if;
  if to_regprocedure('auth.email()') is null then
    execute 'create function auth.email() returns text language sql stable as $f$'
         || 'select nullif(auth.jwt() ->> ''email'', '''')$f$';
    v_made := v_made || 'auth.email() ';
  end if;
  if v_made <> '' then
    begin
      execute 'grant execute on function auth.jwt(), auth.uid(), auth.role(), auth.email() to anon, authenticated, service_role';
    exception when others then null;
    end;
    raise notice 'created stand-in auth helpers: %', v_made;
  end if;
exception when insufficient_privilege then
  raise notice 'the auth schema is owned elsewhere (GoTrue); its helpers are already there';
end $$;

-- ── 5 · what the rest of the repository expects to find ────────────────────
do $$
declare v_missing text := '';
begin
  if not exists (select 1 from pg_roles where rolname = 'service_role') then v_missing := v_missing || 'service_role '; end if;
  if not exists (select 1 from pg_roles where rolname = 'dq_evaluator') then v_missing := v_missing || 'dq_evaluator '; end if;
  if to_regnamespace('extensions') is null then v_missing := v_missing || 'schema:extensions '; end if;
  if not exists (select 1 from pg_extension where extname = 'pgcrypto') then v_missing := v_missing || 'pgcrypto '; end if;
  if to_regclass('auth.users') is null then v_missing := v_missing || 'auth.users '; end if;
  if to_regprocedure('auth.uid()') is null then v_missing := v_missing || 'auth.uid() '; end if;
  if v_missing <> '' then
    raise exception 'platform prerequisites incomplete: %', v_missing;
  end if;
  raise notice 'platform prerequisites ready (roles, schemas, extensions, auth surface)';
end $$;
