-- Fixture Room · FIXTURE CANDIDATES SMOKE (generated by scripts/fixture-room-harness.sh from
-- seed_fixture_shape.sql + bodies/candidates.sql; edit those, not this file).
-- BEGIN … ROLLBACK. Run as the database owner:
--   docker exec -i supabase_db_arab-ship-broker psql -U postgres -d postgres -v ON_ERROR_STOP=1 -f - < supabase/tests/fixture_room/fixture_candidates_smoke.sql

begin;

-- Fixture Room · test seed (23 Sep 2026). Fixed ids, idempotent, and meant to
-- run INSIDE the caller's transaction: every smoke file inlines this block
-- after its BEGIN (scripts/fixture-room-harness.sh assembles the files from
-- this seed and the bodies under supabase/tests/fixture_room/bodies, so the
-- copies cannot drift); fixture_race_two_sessions.sh runs it in a committed
-- transaction and removes the rows afterwards.
--
-- Gates and triggers are skipped while the listings are inserted (these are
-- test rows, not member submissions); check constraints still apply. The
-- role is reset to origin before any Fixture Room RPC runs, so the
-- append-only triggers are live for the assertions.
--
-- Shape:  two member organisations (charterer with two seats, owner with one
-- active and one pending seat), an outsider organisation, a platform admin,
-- an individual member with no organisation, a T1 member, a contact-backed
-- listing, a listing owned by an admin (platform-synced), a sanctioned vessel
-- and a TBN vessel. Every counterparty case of amendment A1 is reachable.
set local session_replication_role = replica;

create temp table if not exists fx_ids (k text primary key, v uuid);
grant all on table fx_ids to authenticated;
insert into fx_ids (k, v) values
  ('org_ch',  '00000000-0000-4000-8000-0000000000c1'),
  ('org_ow',  '00000000-0000-4000-8000-0000000000c2'),
  ('org_out', '00000000-0000-4000-8000-0000000000c3'),
  ('u_ch1',   '00000000-0000-4000-8000-0000000000a1'),
  ('u_ch2',   '00000000-0000-4000-8000-0000000000a2'),
  ('u_ow1',   '00000000-0000-4000-8000-0000000000a3'),
  ('u_out',   '00000000-0000-4000-8000-0000000000a4'),
  ('u_adm',   '00000000-0000-4000-8000-0000000000a5'),
  ('u_solo',  '00000000-0000-4000-8000-0000000000a6'),
  ('u_pend',  '00000000-0000-4000-8000-0000000000a7'),
  ('u_t1',    '00000000-0000-4000-8000-0000000000a8'),
  ('u_two',   '00000000-0000-4000-8000-0000000000a9'),
  ('u_pendcur','00000000-0000-4000-8000-0000000000aa'),
  ('org_two', '00000000-0000-4000-8000-0000000000c4'),
  ('org_x',   '00000000-0000-4000-8000-0000000000c5'),
  ('c5',      '00000000-0000-4000-8000-0000000000e5'),
  ('contact', '00000000-0000-4000-8000-0000000000d1'),
  ('c1',      '00000000-0000-4000-8000-0000000000e1'),
  ('c2',      '00000000-0000-4000-8000-0000000000e2'),
  ('c3',      '00000000-0000-4000-8000-0000000000e3'),
  ('c4',      '00000000-0000-4000-8000-0000000000e4'),
  ('v1',      '00000000-0000-4000-8000-0000000000f1'),
  ('v2',      '00000000-0000-4000-8000-0000000000f2'),
  ('v3',      '00000000-0000-4000-8000-0000000000f3'),
  ('a1',      '00000000-0000-4000-8000-0000000000b1'),
  ('a2',      '00000000-0000-4000-8000-0000000000b2'),
  ('a3',      '00000000-0000-4000-8000-0000000000b3'),
  ('a4',      '00000000-0000-4000-8000-0000000000b4')
on conflict (k) do nothing;

-- ── helpers (temp; they vanish with the transaction) ────────────────────────
create or replace function pg_temp.fx_id(p_k text) returns uuid language sql stable as $f$ select v from fx_ids where k = p_k $f$;
-- act as a seeded member: the JWT claims PostgREST would set, and the authenticated role
create or replace function pg_temp.fx_as(p_k text, p_admin boolean default false) returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', pg_temp.fx_id(p_k)::text, true);
  perform set_config('request.jwt.claims', json_build_object('sub', pg_temp.fx_id(p_k), 'role', 'authenticated',
            'app_metadata', case when p_admin then json_build_object('role', 'admin') else json_build_object('role', 'member') end)::text, true);
  execute 'set local role authenticated';
end $f$;
create or replace function pg_temp.fx_anon() returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
  execute 'set local role anon';
end $f$;
create or replace function pg_temp.fx_owner() returns void language plpgsql as $f$
begin
  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
end $f$;
-- create a room as the member whose claims are set (C2O-013): members no longer hold
-- EXECUTE on the raw-id create_fixture_room, so the suites call it as the database owner
-- with the member's JWT claims left in place; the command reads its actor from the claims,
-- so every ownership, tier and pairing rule is exercised exactly as before
create or replace function pg_temp.fx_create(p_cargo uuid, p_avail uuid, p_terms jsonb, p_key text, p_options jsonb default '{}'::jsonb)
 returns jsonb language plpgsql as $f$
declare v jsonb; v_role text := current_user;
begin
  execute 'reset role';
  begin
    v := public.create_fixture_room(p_cargo, p_avail, p_terms, p_key, p_options);
  exception when others then
    execute format('set local role %I', v_role);
    raise;
  end;
  execute format('set local role %I', v_role);
  return v;
end $f$;
-- run a statement and report 'OK' or the FX_ prefix it raised
create or replace function pg_temp.fx_err(p_sql text) returns text language plpgsql as $f$
declare v jsonb;
begin
  execute p_sql into v;
  return 'OK';
exception when others then
  return coalesce(substring(sqlerrm from '^(FX_[A-Z_]+):'), 'ERR ' || sqlstate || ' ' || left(sqlerrm, 160));
end $f$;
create or replace function pg_temp.fx_call(p_sql text) returns jsonb language plpgsql as $f$
declare v jsonb; begin execute p_sql into v; return v; end $f$;
-- owner-level peeks used by assertions only
create or replace function pg_temp.fx_term(p_room uuid, p_code text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_terms where room_id = p_room and code = p_code $f$;
create or replace function pg_temp.fx_party(p_room uuid, p_side text, p_capacity text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_parties where room_id = p_room and side = p_side and capacity = p_capacity and status in ('invited', 'active') order by created_at limit 1 $f$;
create or replace function pg_temp.fx_events(p_room uuid) returns bigint language sql stable security definer as $f$
  select count(*) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_event_types(p_room uuid) returns text language sql stable security definer as $f$
  select string_agg(type, ',' order by seq) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_ver(p_room uuid) returns integer language sql stable security definer as $f$
  select version from public.fixture_rooms where id = p_room $f$;
create or replace function pg_temp.fx_status(p_room uuid) returns text language sql stable security definer as $f$
  select status from public.fixture_rooms where id = p_room $f$;
-- the v1 catalogue, as lib/fixture-room/terms.ts sends it
create or replace function pg_temp.fx_terms() returns jsonb language sql immutable as $f$ select $j$[
  {"code":"cargo_grade","label":"Cargo & grade","category":"cargo","sortOrder":1,"valueKind":"text","required":true,"hint":"Listing: Wheat, Bulk"},
  {"code":"quantity","label":"Quantity","category":"cargo","sortOrder":2,"valueKind":"number","unit":"MT","required":true},
  {"code":"ports","label":"Load / discharge ports","category":"route","sortOrder":3,"valueKind":"port_pair","required":true},
  {"code":"laycan","label":"Laycan","category":"timing","sortOrder":4,"valueKind":"date_range","required":true},
  {"code":"ld_rates","label":"Load / discharge rates","category":"operations","sortOrder":5,"valueKind":"rate_pair","unit":"MT/day","required":true},
  {"code":"freight","label":"Freight & terms","category":"money","sortOrder":6,"valueKind":"money_per_mt","unit":"USD/MT","required":true}]$j$::jsonb $f$;
-- the catalogue with one deviation, for the FR-H2 negatives (every one must be refused)
create or replace function pg_temp.fx_terms_mut(p_op text) returns jsonb language plpgsql immutable as $f$
declare c jsonb := pg_temp.fx_terms(); o jsonb := '[]'::jsonb; t jsonb;
begin
  for t in select * from jsonb_array_elements(c) loop
    if p_op = 'missing' and t->>'code' = 'quantity' then continue; end if;
    if p_op = 'relabelled' and t->>'code' = 'freight' then t := t || '{"label":"Freight"}'::jsonb; end if;
    if p_op = 'retyped' and t->>'code' = 'quantity' then t := t || '{"valueKind":"text"}'::jsonb; end if;
    if p_op = 'optionalised' and t->>'code' = 'laycan' then t := t || '{"required":false}'::jsonb; end if;
    if p_op = 'reordered' and t->>'code' = 'ports' then t := t || '{"sortOrder":4}'::jsonb; end if;
    if p_op = 'recategorised' and t->>'code' = 'ports' then t := t || '{"category":"money"}'::jsonb; end if;
    if p_op = 'reunited' and t->>'code' = 'quantity' then t := t || '{"unit":"kg"}'::jsonb; end if;
    if p_op = 'renamed' and t->>'code' = 'ld_rates' then t := t || '{"code":"rates"}'::jsonb; end if;
    if p_op = 'unrequired' and t->>'code' = 'laycan' then t := t - 'required'; end if;
    o := o || t;
  end loop;
  if p_op = 'extra' then o := o || '{"code":"demurrage","label":"Demurrage","category":"money","sortOrder":7,"valueKind":"number","required":true}'::jsonb; end if;
  if p_op = 'duplicate' then o := o || (c->0); end if;
  return o;
end $f$;
-- owner-level peek: the latest non-terminal room of a pairing (refs are monotonic; created_at is the transaction time)
create or replace function pg_temp.fx_room(p_cargo uuid, p_avail uuid) returns uuid language sql stable security definer as $f$
  select id from public.fixture_rooms where cargo_listing_id = p_cargo and vessel_availability_id = p_avail
     and status not in ('withdrawn', 'failed', 'expired') order by ref desc limit 1 $f$;
-- owner-level peek: the identity a principal party was recorded with
create or replace function pg_temp.fx_party_identity(p_room uuid, p_side text) returns jsonb language sql stable security definer as $f$
  select jsonb_build_object('org_id', org_id, 'user_id', user_id, 'mode', participation_mode) from public.fixture_parties
   where room_id = p_room and side = p_side and capacity = 'principal' and status in ('invited', 'active') order by created_at limit 1 $f$;
-- one agreeable value per term code
create or replace function pg_temp.fx_value(p_code text) returns jsonb language sql immutable as $f$
  select ($j${"cargo_grade":{"text":"Wheat in bulk, 2026 crop"},"quantity":{"num":26000},
            "ports":{"load":"ZZFXA","disch":"ZZFXB","load_name":"Fixture Load Port","disch_name":"Fixture Disch Port"},
            "laycan":{"from":"2026-10-05","to":"2026-10-12"},"ld_rates":{"load":8000,"disch":6000},
            "freight":{"num":25.75,"currency":"USD"}}$j$::jsonb)->p_code $f$;

-- ── people and organisations ────────────────────────────────────────────────
insert into auth.users (id, email, aud, role)
select v, k || '@fixture.test', 'authenticated', 'authenticated' from fx_ids where k like 'u\_%'
on conflict (id) do nothing;

insert into public.organizations (id, name, org_type, desk_contact_name, desk_email, desk_phone, country, fleet_total) values
  (pg_temp.fx_id('org_ch'),  'Seed Charterers Ltd', 'charterer', 'Chartering Desk', 'desk@seed-charterers.test', '+20 100 000 0001', 'Egypt', null),
  (pg_temp.fx_id('org_ow'),  'Seed Owners SA',      'owner',     'Owner''s Desk',   'desk@seed-owners.test',     '+30 210 000 0002', 'Greece', 7),
  (pg_temp.fx_id('org_out'), 'Seed Outsiders LLC',  'broker',    'Outsider Desk',   'desk@seed-outsiders.test',  null,               'UAE', null),
  (pg_temp.fx_id('org_two'), 'Seed Second Org',     'charterer', 'Second Desk',     'desk@seed-second.test',     null,               'Egypt', null),
  (pg_temp.fx_id('org_x'),   'Seed Unrelated Co',   'broker',    'Unrelated Desk',  'desk@seed-unrelated.test',  null,               'Greece', null)
on conflict do nothing;

insert into public.users (id, supabase_user_id, email, full_name, company, role, subscription_tier, is_active) values
  (pg_temp.fx_id('u_ch1'),  pg_temp.fx_id('u_ch1'),  'u_ch1@fixture.test',  'Seed Charterer One', 'Seed Charterers Ltd', 'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_ch2'),  pg_temp.fx_id('u_ch2'),  'u_ch2@fixture.test',  'Seed Charterer Two', 'Seed Charterers Ltd', 'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('u_ow1'),  'u_ow1@fixture.test',  'Seed Owner One',     'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_out'),  pg_temp.fx_id('u_out'),  'u_out@fixture.test',  'Seed Outsider',      'Seed Outsiders LLC',  'broker',       'T3', true),
  (pg_temp.fx_id('u_adm'),  pg_temp.fx_id('u_adm'),  'u_adm@fixture.test',  'Seed Admin',         'Arab ShipBroker',     'admin',        'T4', true),
  (pg_temp.fx_id('u_solo'), pg_temp.fx_id('u_solo'), 'u_solo@fixture.test', 'Seed Solo Owner',    'Solo Shipping',       'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_pend'), pg_temp.fx_id('u_pend'), 'u_pend@fixture.test', 'Seed Pending',       'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_t1'),   pg_temp.fx_id('u_t1'),   'u_t1@fixture.test',   'Seed Tier One',      'Tier One Trading',    'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_two'),  pg_temp.fx_id('u_two'),  'u_two@fixture.test',  'Seed Two Seats',     'Seed Second Org',     'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_pendcur'), pg_temp.fx_id('u_pendcur'), 'u_pendcur@fixture.test', 'Seed Pending Current', 'Seed Owners SA', 'vessel_owner', 'T3', true)
on conflict (id) do nothing;

-- Seats. u_two holds two ACTIVE seats (admin in org_ch first, broker in
-- org_two second) and owns C5 through org_two: a seat-guessing rule would
-- pick org_ch (FR-H1). u_solo owns A4 personally and sits in an unrelated
-- organisation (org_x): the party must be the member, never that seat.
-- u_pend is pending and not current; u_pendcur is pending AND current, the
-- legacy shape the Phase 0 review requires to be refused (FR-M1).
insert into public.organization_members (org_id, user_id, member_role, is_current, status) values
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch2'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_ow1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_out'), pg_temp.fx_id('u_out'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pend'), 'broker', false, 'pending'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_two'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_two'), pg_temp.fx_id('u_two'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_x'),   pg_temp.fx_id('u_solo'), 'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pendcur'), 'broker', true, 'pending')
on conflict do nothing;

insert into public.contacts (id, kind, display_name, email, phone, role, source) values
  (pg_temp.fx_id('contact'), 'desk', 'Seed Brokers Desk', 'desk@seed-brokers.test', '+90 212 000 0003', 'broker', 'admin')
on conflict do nothing;

-- ── listings ────────────────────────────────────────────────────────────────
insert into public.ports (locode, trade_name, country, zone, port_type, is_active, is_verified) values
  ('ZZFXA', 'Fixture Load Port',  'Egypt',  'E.MED', 'Sea Port', true, true),
  ('ZZFXB', 'Fixture Disch Port', 'Turkey', 'E.MED', 'Sea Port', true, true)
on conflict do nothing;

insert into public.cargo_listings (id, ref, status, review_status, cargo_type, commodity_name, is_dg_cargo, is_grain_cargo,
  qty_min_mt, qty_max_mt, stowage_factor, load_port_locode, load_port_name, load_zone, disch_port_locode, disch_port_name, disch_zone,
  laycan_from, laycan_to, is_spot, load_rate, disch_rate, load_terms, freight_idea_usd_mt, commission_pct, demurrage_rate, broker, notes, broker_contact_id) values
  (pg_temp.fx_id('c1'), 'FXC-001', 'IN', 'APPROVED', 'Dry Bulk', 'Wheat, Bulk', false, true, 25000, 27500, 1.25,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 10, current_date + 20, false,
   '8000', '6000', 'FIOST', 24.50, 2.5, 12000, 'Seed Brokers (Tasos)', 'call charterer mobile +20 100 000 9999', null),
  (pg_temp.fx_id('c2'), 'FXC-002', 'IN', 'APPROVED', 'Dry Bulk', 'Barley', false, true, 20000, 22000, 1.40,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 12, current_date + 22, false,
   '7000', '5000', 'FIO', 22.00, 2.5, 10000, null, null, null),
  (pg_temp.fx_id('c3'), 'FXC-003', 'IN', 'APPROVED', 'Dry Bulk', 'Clinker', false, false, 30000, 33000, 0.90,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 15, current_date + 25, false,
   '9000', '7000', 'FIOST', 18.00, 2.5, 11000, null, null, null),
  (pg_temp.fx_id('c4'), 'FXC-004', 'IN', 'APPROVED', 'Break Bulk', 'Steel coils', false, false, 12000, 13000, null,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 8, current_date + 18, false,
   '3000', '3000', 'FIOST', 31.00, 2.5, 15000, 'Seed Brokers Desk', 'desk@seed-brokers.test', pg_temp.fx_id('contact')),
  (pg_temp.fx_id('c5'), 'FXC-005', 'IN', 'APPROVED', 'Dry Bulk', 'Corn', false, true, 24000, 26000, 1.30,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 11, current_date + 21, false,
   '8000', '6000', 'FIOST', 23.00, 2.5, 11500, null, null, null)
on conflict (id) do nothing;

insert into public.vessels (id, vessel_name, imo_number, vessel_type, dwt_grain, build_year, flag, is_geared, grain_certified, dg_certified,
  max_draft_m, is_sanctioned, owner_company, pic_name, phone, email_chartering, is_tbn) values
  (pg_temp.fx_id('v1'), 'SEED VESSEL ONE', '9000001', 'Bulk Carrier', 30000, 2012, 'Malta', true, true, false, 10.5, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', false),
  (pg_temp.fx_id('v2'), 'SEED SANCTIONED', '9000002', 'Bulk Carrier', 28000, 2008, 'Panama', false, false, false, 10.0, true,
   'Sanctioned Owner', 'Capt. Sanction', '+1 000 000 0000', 'sanctioned@example.test', false),
  (pg_temp.fx_id('v3'), 'SEED TBN HULL', null, 'Bulk Carrier', 32000, 2015, 'Liberia', true, true, false, 11.0, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', true)
on conflict (id) do nothing;

insert into public.vessel_availability (id, vessel_id, open_port_locode, open_port_name, open_zone, open_date, status, review_status, freight_idea_usd_mt, accepts_part_cargo, notes) values
  (pg_temp.fx_id('a1'), pg_temp.fx_id('v1'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 26.00, false, 'owner mobile +30 690 000 0000'),
  (pg_temp.fx_id('a2'), pg_temp.fx_id('v2'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 20.00, false, null),
  (pg_temp.fx_id('a3'), pg_temp.fx_id('v3'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 7,  'OPEN', 'APPROVED', 27.00, false, null),
  (pg_temp.fx_id('a4'), pg_temp.fx_id('v1'), 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 40, 'OPEN', 'APPROVED', 25.00, true, null)
on conflict (id) do nothing;

insert into public.listing_ownership (listing_type, listing_id, owner_user_id, owner_org_id, role, is_current, transfer_reason) values
  ('cargo', pg_temp.fx_id('c1'), pg_temp.fx_id('u_ch1'), pg_temp.fx_id('org_ch'), 'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c2'), pg_temp.fx_id('u_t1'),  null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c3'), pg_temp.fx_id('u_adm'), null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c5'), pg_temp.fx_id('u_two'), pg_temp.fx_id('org_two'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a1'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a2'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a3'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a4'), pg_temp.fx_id('u_solo'), null,                    'primary', true, 'initial_post')
on conflict do nothing;

set local session_replication_role = origin;
-- ── end of seed ─────────────────────────────────────────────────────────────

-- Fixture Room · CANDIDATES body (C2O-011, 28 Sep 2026): list_fixture_match_candidates of
-- 20260923206000. Runs after the shared seed inside the caller's transaction. Adds one
-- grain cargo (c6, owned by the charterer organisation) that both the named vessel (a1)
-- and the TBN hull (a3) match, then proves ownership, masking and the match facts.

set local session_replication_role = replica;
insert into fx_ids (k, v) values ('c6', '00000000-0000-4000-8000-0000000000e6') on conflict do nothing;
insert into public.cargo_listings (id, ref, status, review_status, cargo_type, commodity_name, is_dg_cargo, is_grain_cargo,
  qty_min_mt, qty_max_mt, stowage_factor, load_port_locode, load_port_name, load_zone, disch_port_locode, disch_port_name, disch_zone,
  laycan_from, laycan_to, is_spot, load_rate, disch_rate, load_terms, freight_idea_usd_mt, commission_pct, demurrage_rate) values
  (pg_temp.fx_id('c6'), 'FXC-006', 'IN', 'APPROVED', 'Dry Bulk', 'Soya beans', false, true, 29000, 31000, 1.30,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 10, current_date + 20, false,
   '8000', '6000', 'FIOST', 26.00, 2.5, 12000)
on conflict (id) do nothing;
insert into public.listing_ownership (listing_type, listing_id, owner_user_id, owner_org_id, role, is_current, transfer_reason) values
  ('cargo', pg_temp.fx_id('c6'), pg_temp.fx_id('u_ch1'), pg_temp.fx_id('org_ch'), 'primary', true, 'initial_post')
on conflict do nothing;
set local session_replication_role = origin;

do $$
declare v jsonb; c jsonb; s text; n int;
begin
  -- K1 · the owner of the cargo sees both hulls; the TBN one is a label with no identifier
  perform pg_temp.fx_as('u_ch1');
  v := public.list_fixture_match_candidates('cargo', pg_temp.fx_id('c6'));
  s := v::text;
  select count(*) into n from jsonb_array_elements(v) x where x->>'name' in ('TBN', 'SEED VESSEL ONE') and x ? 'candidateKey';
  if n <> 2 then raise exception 'K1: both matching positions must be listed, got % in %', n, s; end if;
  select x into c from jsonb_array_elements(v) x where x->>'name' = 'TBN';
  if c->>'name' <> 'TBN' or (c->>'isTbn')::boolean is not true then raise exception 'K1: the TBN hull must be named TBN: %', c; end if;
  if s like '%SEED TBN HULL%' then raise exception 'K1: the TBN hull name reached the candidate payload'; end if;
  if s like '%' || pg_temp.fx_id('v3')::text || '%' or s like '%' || pg_temp.fx_id('v1')::text || '%' then
    raise exception 'K1: a vessels.id reached the candidate payload'; end if;
  if s like '%9000001%' then raise exception 'K1: an IMO number reached the candidate payload'; end if;
  if exists (select 1 from jsonb_array_elements(v) x where x ? 'vesselId' or x ? 'vesselRef' or x ? 'imo' or x ? 'availabilityId') then
    raise exception 'K1: a candidate carries a vessel identifier key'; end if;
  select x into c from jsonb_array_elements(v) x where x->>'name' = 'SEED VESSEL ONE';
  if c->>'name' <> 'SEED VESSEL ONE' then raise exception 'K1: a named vessel keeps its name: %', c; end if;
  raise notice 'K1 ok: the TBN hull is listed as TBN; no vessel id, IMO or hidden name in the payload';

  -- K2 · the match facts are the governed rule's: same zone, laycan window, grain certified
  if c->'fit'->>'zone' <> 'load' or c->'fit'->>'laycan' <> 'window' or (c->'fit'->>'grain')::boolean is not true then
    raise exception 'K2: the match facts must mirror the governed rule: %', c->'fit'; end if;
  raise notice 'K2 ok: each candidate carries the governed match facts (zone, laycan window, grain)';

  -- K3 · another member cannot list the matches of a listing they do not own
  perform pg_temp.fx_as('u_out');
  begin
    v := public.list_fixture_match_candidates('cargo', pg_temp.fx_id('c6'));
    raise exception 'K3: an outsider listed another member''s matches';
  exception when insufficient_privilege then null;
  end;
  perform pg_temp.fx_as('u_ow1');
  begin
    v := public.list_fixture_match_candidates('cargo', pg_temp.fx_id('c6'));
    raise exception 'K3: the counterparty listed the charterer''s matches';
  exception when insufficient_privilege then null;
  end;
  -- a second active seat of the owning organisation represents the listing too
  perform pg_temp.fx_as('u_ch2');
  v := public.list_fixture_match_candidates('cargo', pg_temp.fx_id('c6'));
  if jsonb_array_length(v) < 2 then raise exception 'K3: an active seat of the owning organisation must see the matches'; end if;
  raise notice 'K3 ok: only the listing''s owner or its organisation''s active seats may list its matches';

  -- K4 · the vessel side follows the same ownership rule
  perform pg_temp.fx_as('u_ow1');
  v := public.list_fixture_match_candidates('vessel', pg_temp.fx_id('a3'));
  if not exists (select 1 from jsonb_array_elements(v) x where x->>'ref' = 'FXC-006') then
    raise exception 'K4: the TBN position must see the matching cargo: %', v; end if;
  perform pg_temp.fx_as('u_ch1');
  begin
    v := public.list_fixture_match_candidates('vessel', pg_temp.fx_id('a3'));
    raise exception 'K4: the charterer listed the owner''s position matches';
  exception when insufficient_privilege then null;
  end;
  raise notice 'K4 ok: the vessel side is governed by the same ownership rule';

  -- K5 · input validation and anonymous callers
  perform pg_temp.fx_as('u_ch1');
  begin
    v := public.list_fixture_match_candidates('fleet', pg_temp.fx_id('c6'));
    raise exception 'K5: an unknown kind was accepted';
  exception when invalid_parameter_value then null;
  end;
  perform pg_temp.fx_anon();
  begin
    v := public.list_fixture_match_candidates('cargo', pg_temp.fx_id('c6'));
    raise exception 'K5: an anonymous caller listed candidates';
  exception when insufficient_privilege then null;
  end;
  perform pg_temp.fx_owner();
  raise notice 'K5 ok: unknown kinds and anonymous callers are refused';

  -- K6 · a null kind is refused, not routed to the vessel branch (re-audit item 4)
  perform pg_temp.fx_as('u_ow1');
  begin
    v := public.list_fixture_match_candidates(null, pg_temp.fx_id('a3'));
    raise exception 'K6: a null kind was accepted';
  exception when invalid_parameter_value then null;
  end;
  perform pg_temp.fx_owner();
  raise notice 'K6 ok: a null kind is refused';

  -- K7 · the builder's own listings follow the create rule: an active second seat of the
  -- owning organisation sees the organisation's listing; an outsider sees none of it
  perform pg_temp.fx_as('u_ch2');
  v := public.list_fixture_my_listings();
  if not exists (select 1 from jsonb_array_elements(v->'cargo') x where x->>'id' = pg_temp.fx_id('c6')::text)
     or not exists (select 1 from jsonb_array_elements(v->'cargo') x where x->>'id' = pg_temp.fx_id('c1')::text) then
    raise exception 'K7: the second seat of the charterer organisation must see its cargo: %', v; end if;
  if v::text like '%' || pg_temp.fx_id('v1')::text || '%' or v::text like '%9000001%' then raise exception 'K7: an own-listing read carries a vessel id or IMO'; end if;
  perform pg_temp.fx_as('u_out');
  v := public.list_fixture_my_listings();
  if v::text like '%' || pg_temp.fx_id('c1')::text || '%' or v::text like '%' || pg_temp.fx_id('c6')::text || '%' then raise exception 'K7: an outsider sees another organisation''s listing: %', v; end if;
  perform pg_temp.fx_as('u_ow1');
  v := public.list_fixture_my_listings();
  if not exists (select 1 from jsonb_array_elements(v->'vessels') x where x->>'availabilityId' = pg_temp.fx_id('a3')::text and x->>'name' = 'SEED TBN HULL') then
    raise exception 'K7: the owner sees its own TBN position by name: %', v; end if;
  perform pg_temp.fx_owner();
  raise notice 'K7 ok: own listings follow the create rule (organisation seats included), with no vessel id or IMO';
end $$;

do $$ begin raise notice 'FIXTURE CANDIDATES SMOKE: ALL ASSERTIONS PASSED'; end $$;

rollback;
