-- Fixture Room · FIXTURE SNAPSHOT SMOKE (generated by scripts/fixture-room-harness.sh from
-- seed_fixture_shape.sql + bodies/snapshot.sql; edit those, not this file).
-- BEGIN … ROLLBACK. Run as the database owner:
--   docker exec -i supabase_db_arab-ship-broker psql -U postgres -d postgres -v ON_ERROR_STOP=1 -f - < supabase/tests/fixture_room/fixture_snapshot_smoke.sql

begin;

-- Fixture Room · test seed (23 Sep 2026). Fixed ids, idempotent, and meant to
-- run INSIDE the caller's transaction: every smoke file inlines this block
-- after its BEGIN (scripts/fixture-room-harness.sh assembles the files from
-- this seed and the bodies under supabase/tests/fixture_room/bodies, so the
-- copies cannot drift); fixture_race_two_sessions.sh runs it in a committed
-- transaction and removes the rows afterwards.
--
-- Gates and triggers are skipped while the listings are inserted (these are
-- test rows, not member submissions); check constraints still apply. The
-- role is reset to origin before any Fixture Room RPC runs, so the
-- append-only triggers are live for the assertions.
--
-- Shape:  two member organisations (charterer with two seats, owner with one
-- active and one pending seat), an outsider organisation, a platform admin,
-- an individual member with no organisation, a T1 member, a contact-backed
-- listing, a listing owned by an admin (platform-synced), a sanctioned vessel
-- and a TBN vessel. Every counterparty case of amendment A1 is reachable.
set local session_replication_role = replica;

create temp table if not exists fx_ids (k text primary key, v uuid);
grant all on table fx_ids to authenticated;
insert into fx_ids (k, v) values
  ('org_ch',  '00000000-0000-4000-8000-0000000000c1'),
  ('org_ow',  '00000000-0000-4000-8000-0000000000c2'),
  ('org_out', '00000000-0000-4000-8000-0000000000c3'),
  ('u_ch1',   '00000000-0000-4000-8000-0000000000a1'),
  ('u_ch2',   '00000000-0000-4000-8000-0000000000a2'),
  ('u_ow1',   '00000000-0000-4000-8000-0000000000a3'),
  ('u_out',   '00000000-0000-4000-8000-0000000000a4'),
  ('u_adm',   '00000000-0000-4000-8000-0000000000a5'),
  ('u_solo',  '00000000-0000-4000-8000-0000000000a6'),
  ('u_pend',  '00000000-0000-4000-8000-0000000000a7'),
  ('u_t1',    '00000000-0000-4000-8000-0000000000a8'),
  ('u_two',   '00000000-0000-4000-8000-0000000000a9'),
  ('u_pendcur','00000000-0000-4000-8000-0000000000aa'),
  ('org_two', '00000000-0000-4000-8000-0000000000c4'),
  ('org_x',   '00000000-0000-4000-8000-0000000000c5'),
  ('c5',      '00000000-0000-4000-8000-0000000000e5'),
  ('contact', '00000000-0000-4000-8000-0000000000d1'),
  ('c1',      '00000000-0000-4000-8000-0000000000e1'),
  ('c2',      '00000000-0000-4000-8000-0000000000e2'),
  ('c3',      '00000000-0000-4000-8000-0000000000e3'),
  ('c4',      '00000000-0000-4000-8000-0000000000e4'),
  ('v1',      '00000000-0000-4000-8000-0000000000f1'),
  ('v2',      '00000000-0000-4000-8000-0000000000f2'),
  ('v3',      '00000000-0000-4000-8000-0000000000f3'),
  ('a1',      '00000000-0000-4000-8000-0000000000b1'),
  ('a2',      '00000000-0000-4000-8000-0000000000b2'),
  ('a3',      '00000000-0000-4000-8000-0000000000b3'),
  ('a4',      '00000000-0000-4000-8000-0000000000b4')
on conflict (k) do nothing;

-- ── helpers (temp; they vanish with the transaction) ────────────────────────
create or replace function pg_temp.fx_id(p_k text) returns uuid language sql stable as $f$ select v from fx_ids where k = p_k $f$;
-- act as a seeded member: the JWT claims PostgREST would set, and the authenticated role
create or replace function pg_temp.fx_as(p_k text, p_admin boolean default false) returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', pg_temp.fx_id(p_k)::text, true);
  perform set_config('request.jwt.claims', json_build_object('sub', pg_temp.fx_id(p_k), 'role', 'authenticated',
            'app_metadata', case when p_admin then json_build_object('role', 'admin') else json_build_object('role', 'member') end)::text, true);
  execute 'set local role authenticated';
end $f$;
create or replace function pg_temp.fx_anon() returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
  execute 'set local role anon';
end $f$;
create or replace function pg_temp.fx_owner() returns void language plpgsql as $f$
begin
  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
end $f$;
-- create a room as the member whose claims are set (C2O-013): members no longer hold
-- EXECUTE on the raw-id create_fixture_room, so the suites call it as the database owner
-- with the member's JWT claims left in place; the command reads its actor from the claims,
-- so every ownership, tier and pairing rule is exercised exactly as before
create or replace function pg_temp.fx_create(p_cargo uuid, p_avail uuid, p_terms jsonb, p_key text, p_options jsonb default '{}'::jsonb)
 returns jsonb language plpgsql as $f$
declare v jsonb; v_role text := current_user;
begin
  execute 'reset role';
  begin
    v := public.create_fixture_room(p_cargo, p_avail, p_terms, p_key, p_options);
  exception when others then
    execute format('set local role %I', v_role);
    raise;
  end;
  execute format('set local role %I', v_role);
  return v;
end $f$;
-- run a statement and report 'OK' or the FX_ prefix it raised
create or replace function pg_temp.fx_err(p_sql text) returns text language plpgsql as $f$
declare v jsonb;
begin
  execute p_sql into v;
  return 'OK';
exception when others then
  return coalesce(substring(sqlerrm from '^(FX_[A-Z_]+):'), 'ERR ' || sqlstate || ' ' || left(sqlerrm, 160));
end $f$;
create or replace function pg_temp.fx_call(p_sql text) returns jsonb language plpgsql as $f$
declare v jsonb; begin execute p_sql into v; return v; end $f$;
-- owner-level peeks used by assertions only
create or replace function pg_temp.fx_term(p_room uuid, p_code text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_terms where room_id = p_room and code = p_code $f$;
create or replace function pg_temp.fx_party(p_room uuid, p_side text, p_capacity text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_parties where room_id = p_room and side = p_side and capacity = p_capacity and status in ('invited', 'active') order by created_at limit 1 $f$;
create or replace function pg_temp.fx_events(p_room uuid) returns bigint language sql stable security definer as $f$
  select count(*) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_event_types(p_room uuid) returns text language sql stable security definer as $f$
  select string_agg(type, ',' order by seq) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_ver(p_room uuid) returns integer language sql stable security definer as $f$
  select version from public.fixture_rooms where id = p_room $f$;
create or replace function pg_temp.fx_status(p_room uuid) returns text language sql stable security definer as $f$
  select status from public.fixture_rooms where id = p_room $f$;
-- the v1 catalogue, as lib/fixture-room/terms.ts sends it
create or replace function pg_temp.fx_terms() returns jsonb language sql immutable as $f$ select $j$[
  {"code":"cargo_grade","label":"Cargo & grade","category":"cargo","sortOrder":1,"valueKind":"text","required":true,"hint":"Listing: Wheat, Bulk"},
  {"code":"quantity","label":"Quantity","category":"cargo","sortOrder":2,"valueKind":"number","unit":"MT","required":true},
  {"code":"ports","label":"Load / discharge ports","category":"route","sortOrder":3,"valueKind":"port_pair","required":true},
  {"code":"laycan","label":"Laycan","category":"timing","sortOrder":4,"valueKind":"date_range","required":true},
  {"code":"ld_rates","label":"Load / discharge rates","category":"operations","sortOrder":5,"valueKind":"rate_pair","unit":"MT/day","required":true},
  {"code":"freight","label":"Freight & terms","category":"money","sortOrder":6,"valueKind":"money_per_mt","unit":"USD/MT","required":true}]$j$::jsonb $f$;
-- the catalogue with one deviation, for the FR-H2 negatives (every one must be refused)
create or replace function pg_temp.fx_terms_mut(p_op text) returns jsonb language plpgsql immutable as $f$
declare c jsonb := pg_temp.fx_terms(); o jsonb := '[]'::jsonb; t jsonb;
begin
  for t in select * from jsonb_array_elements(c) loop
    if p_op = 'missing' and t->>'code' = 'quantity' then continue; end if;
    if p_op = 'relabelled' and t->>'code' = 'freight' then t := t || '{"label":"Freight"}'::jsonb; end if;
    if p_op = 'retyped' and t->>'code' = 'quantity' then t := t || '{"valueKind":"text"}'::jsonb; end if;
    if p_op = 'optionalised' and t->>'code' = 'laycan' then t := t || '{"required":false}'::jsonb; end if;
    if p_op = 'reordered' and t->>'code' = 'ports' then t := t || '{"sortOrder":4}'::jsonb; end if;
    if p_op = 'recategorised' and t->>'code' = 'ports' then t := t || '{"category":"money"}'::jsonb; end if;
    if p_op = 'reunited' and t->>'code' = 'quantity' then t := t || '{"unit":"kg"}'::jsonb; end if;
    if p_op = 'renamed' and t->>'code' = 'ld_rates' then t := t || '{"code":"rates"}'::jsonb; end if;
    if p_op = 'unrequired' and t->>'code' = 'laycan' then t := t - 'required'; end if;
    o := o || t;
  end loop;
  if p_op = 'extra' then o := o || '{"code":"demurrage","label":"Demurrage","category":"money","sortOrder":7,"valueKind":"number","required":true}'::jsonb; end if;
  if p_op = 'duplicate' then o := o || (c->0); end if;
  return o;
end $f$;
-- owner-level peek: the latest non-terminal room of a pairing (refs are monotonic; created_at is the transaction time)
create or replace function pg_temp.fx_room(p_cargo uuid, p_avail uuid) returns uuid language sql stable security definer as $f$
  select id from public.fixture_rooms where cargo_listing_id = p_cargo and vessel_availability_id = p_avail
     and status not in ('withdrawn', 'failed', 'expired') order by ref desc limit 1 $f$;
-- owner-level peek: the identity a principal party was recorded with
create or replace function pg_temp.fx_party_identity(p_room uuid, p_side text) returns jsonb language sql stable security definer as $f$
  select jsonb_build_object('org_id', org_id, 'user_id', user_id, 'mode', participation_mode) from public.fixture_parties
   where room_id = p_room and side = p_side and capacity = 'principal' and status in ('invited', 'active') order by created_at limit 1 $f$;
-- one agreeable value per term code
create or replace function pg_temp.fx_value(p_code text) returns jsonb language sql immutable as $f$
  select ($j${"cargo_grade":{"text":"Wheat in bulk, 2026 crop"},"quantity":{"num":26000},
            "ports":{"load":"ZZFXA","disch":"ZZFXB","load_name":"Fixture Load Port","disch_name":"Fixture Disch Port"},
            "laycan":{"from":"2026-10-05","to":"2026-10-12"},"ld_rates":{"load":8000,"disch":6000},
            "freight":{"num":25.75,"currency":"USD"}}$j$::jsonb)->p_code $f$;

-- ── people and organisations ────────────────────────────────────────────────
insert into auth.users (id, email, aud, role)
select v, k || '@fixture.test', 'authenticated', 'authenticated' from fx_ids where k like 'u\_%'
on conflict (id) do nothing;

insert into public.organizations (id, name, org_type, desk_contact_name, desk_email, desk_phone, country, fleet_total) values
  (pg_temp.fx_id('org_ch'),  'Seed Charterers Ltd', 'charterer', 'Chartering Desk', 'desk@seed-charterers.test', '+20 100 000 0001', 'Egypt', null),
  (pg_temp.fx_id('org_ow'),  'Seed Owners SA',      'owner',     'Owner''s Desk',   'desk@seed-owners.test',     '+30 210 000 0002', 'Greece', 7),
  (pg_temp.fx_id('org_out'), 'Seed Outsiders LLC',  'broker',    'Outsider Desk',   'desk@seed-outsiders.test',  null,               'UAE', null),
  (pg_temp.fx_id('org_two'), 'Seed Second Org',     'charterer', 'Second Desk',     'desk@seed-second.test',     null,               'Egypt', null),
  (pg_temp.fx_id('org_x'),   'Seed Unrelated Co',   'broker',    'Unrelated Desk',  'desk@seed-unrelated.test',  null,               'Greece', null)
on conflict do nothing;

insert into public.users (id, supabase_user_id, email, full_name, company, role, subscription_tier, is_active) values
  (pg_temp.fx_id('u_ch1'),  pg_temp.fx_id('u_ch1'),  'u_ch1@fixture.test',  'Seed Charterer One', 'Seed Charterers Ltd', 'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_ch2'),  pg_temp.fx_id('u_ch2'),  'u_ch2@fixture.test',  'Seed Charterer Two', 'Seed Charterers Ltd', 'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('u_ow1'),  'u_ow1@fixture.test',  'Seed Owner One',     'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_out'),  pg_temp.fx_id('u_out'),  'u_out@fixture.test',  'Seed Outsider',      'Seed Outsiders LLC',  'broker',       'T3', true),
  (pg_temp.fx_id('u_adm'),  pg_temp.fx_id('u_adm'),  'u_adm@fixture.test',  'Seed Admin',         'Arab ShipBroker',     'admin',        'T4', true),
  (pg_temp.fx_id('u_solo'), pg_temp.fx_id('u_solo'), 'u_solo@fixture.test', 'Seed Solo Owner',    'Solo Shipping',       'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_pend'), pg_temp.fx_id('u_pend'), 'u_pend@fixture.test', 'Seed Pending',       'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_t1'),   pg_temp.fx_id('u_t1'),   'u_t1@fixture.test',   'Seed Tier One',      'Tier One Trading',    'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_two'),  pg_temp.fx_id('u_two'),  'u_two@fixture.test',  'Seed Two Seats',     'Seed Second Org',     'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_pendcur'), pg_temp.fx_id('u_pendcur'), 'u_pendcur@fixture.test', 'Seed Pending Current', 'Seed Owners SA', 'vessel_owner', 'T3', true)
on conflict (id) do nothing;

-- Seats. u_two holds two ACTIVE seats (admin in org_ch first, broker in
-- org_two second) and owns C5 through org_two: a seat-guessing rule would
-- pick org_ch (FR-H1). u_solo owns A4 personally and sits in an unrelated
-- organisation (org_x): the party must be the member, never that seat.
-- u_pend is pending and not current; u_pendcur is pending AND current, the
-- legacy shape the Phase 0 review requires to be refused (FR-M1).
insert into public.organization_members (org_id, user_id, member_role, is_current, status) values
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch2'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_ow1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_out'), pg_temp.fx_id('u_out'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pend'), 'broker', false, 'pending'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_two'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_two'), pg_temp.fx_id('u_two'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_x'),   pg_temp.fx_id('u_solo'), 'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pendcur'), 'broker', true, 'pending')
on conflict do nothing;

insert into public.contacts (id, kind, display_name, email, phone, role, source) values
  (pg_temp.fx_id('contact'), 'desk', 'Seed Brokers Desk', 'desk@seed-brokers.test', '+90 212 000 0003', 'broker', 'admin')
on conflict do nothing;

-- ── listings ────────────────────────────────────────────────────────────────
insert into public.ports (locode, trade_name, country, zone, port_type, is_active, is_verified) values
  ('ZZFXA', 'Fixture Load Port',  'Egypt',  'E.MED', 'Sea Port', true, true),
  ('ZZFXB', 'Fixture Disch Port', 'Turkey', 'E.MED', 'Sea Port', true, true)
on conflict do nothing;

insert into public.cargo_listings (id, ref, status, review_status, cargo_type, commodity_name, is_dg_cargo, is_grain_cargo,
  qty_min_mt, qty_max_mt, stowage_factor, load_port_locode, load_port_name, load_zone, disch_port_locode, disch_port_name, disch_zone,
  laycan_from, laycan_to, is_spot, load_rate, disch_rate, load_terms, freight_idea_usd_mt, commission_pct, demurrage_rate, broker, notes, broker_contact_id) values
  (pg_temp.fx_id('c1'), 'FXC-001', 'IN', 'APPROVED', 'Dry Bulk', 'Wheat, Bulk', false, true, 25000, 27500, 1.25,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 10, current_date + 20, false,
   '8000', '6000', 'FIOST', 24.50, 2.5, 12000, 'Seed Brokers (Tasos)', 'call charterer mobile +20 100 000 9999', null),
  (pg_temp.fx_id('c2'), 'FXC-002', 'IN', 'APPROVED', 'Dry Bulk', 'Barley', false, true, 20000, 22000, 1.40,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 12, current_date + 22, false,
   '7000', '5000', 'FIO', 22.00, 2.5, 10000, null, null, null),
  (pg_temp.fx_id('c3'), 'FXC-003', 'IN', 'APPROVED', 'Dry Bulk', 'Clinker', false, false, 30000, 33000, 0.90,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 15, current_date + 25, false,
   '9000', '7000', 'FIOST', 18.00, 2.5, 11000, null, null, null),
  (pg_temp.fx_id('c4'), 'FXC-004', 'IN', 'APPROVED', 'Break Bulk', 'Steel coils', false, false, 12000, 13000, null,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 8, current_date + 18, false,
   '3000', '3000', 'FIOST', 31.00, 2.5, 15000, 'Seed Brokers Desk', 'desk@seed-brokers.test', pg_temp.fx_id('contact')),
  (pg_temp.fx_id('c5'), 'FXC-005', 'IN', 'APPROVED', 'Dry Bulk', 'Corn', false, true, 24000, 26000, 1.30,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 11, current_date + 21, false,
   '8000', '6000', 'FIOST', 23.00, 2.5, 11500, null, null, null)
on conflict (id) do nothing;

insert into public.vessels (id, vessel_name, imo_number, vessel_type, dwt_grain, build_year, flag, is_geared, grain_certified, dg_certified,
  max_draft_m, is_sanctioned, owner_company, pic_name, phone, email_chartering, is_tbn) values
  (pg_temp.fx_id('v1'), 'SEED VESSEL ONE', '9000001', 'Bulk Carrier', 30000, 2012, 'Malta', true, true, false, 10.5, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', false),
  (pg_temp.fx_id('v2'), 'SEED SANCTIONED', '9000002', 'Bulk Carrier', 28000, 2008, 'Panama', false, false, false, 10.0, true,
   'Sanctioned Owner', 'Capt. Sanction', '+1 000 000 0000', 'sanctioned@example.test', false),
  (pg_temp.fx_id('v3'), 'SEED TBN HULL', null, 'Bulk Carrier', 32000, 2015, 'Liberia', true, true, false, 11.0, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', true)
on conflict (id) do nothing;

insert into public.vessel_availability (id, vessel_id, open_port_locode, open_port_name, open_zone, open_date, status, review_status, freight_idea_usd_mt, accepts_part_cargo, notes) values
  (pg_temp.fx_id('a1'), pg_temp.fx_id('v1'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 26.00, false, 'owner mobile +30 690 000 0000'),
  (pg_temp.fx_id('a2'), pg_temp.fx_id('v2'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 20.00, false, null),
  (pg_temp.fx_id('a3'), pg_temp.fx_id('v3'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 7,  'OPEN', 'APPROVED', 27.00, false, null),
  (pg_temp.fx_id('a4'), pg_temp.fx_id('v1'), 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 40, 'OPEN', 'APPROVED', 25.00, true, null)
on conflict (id) do nothing;

insert into public.listing_ownership (listing_type, listing_id, owner_user_id, owner_org_id, role, is_current, transfer_reason) values
  ('cargo', pg_temp.fx_id('c1'), pg_temp.fx_id('u_ch1'), pg_temp.fx_id('org_ch'), 'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c2'), pg_temp.fx_id('u_t1'),  null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c3'), pg_temp.fx_id('u_adm'), null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c5'), pg_temp.fx_id('u_two'), pg_temp.fx_id('org_two'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a1'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a2'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a3'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a4'), pg_temp.fx_id('u_solo'), null,                    'primary', true, 'initial_post')
on conflict do nothing;

set local session_replication_role = origin;
-- Replica-mode seed writes bypass the matching maintenance triggers. Rebuild
-- once so composed Stream R reads the same source truth as normal writes.
select public.fn_refresh_matches();
-- ── end of seed ─────────────────────────────────────────────────────────────

-- ── N1 · listing edits and status changes after creation do not touch the room ─
do $$
declare v jsonb; r jsonb; v_room uuid; v_hash text; v_recap uuid; v_list jsonb;
begin
  perform pg_temp.fx_as('u_ch1');
  v := pg_temp.fx_create(pg_temp.fx_id('c1'), pg_temp.fx_id('a1'), pg_temp.fx_terms(), 'snap-create-1', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  perform pg_temp.fx_as('u_ow1');
  v := public.respond_fixture_invitation(v_room, true, pg_temp.fx_ver(v_room), 'snap-accept');
  perform pg_temp.fx_as('u_ch1');
  v := public.submit_fixture_proposal(v_room, pg_temp.fx_term(v_room, 'quantity'), '{"num": 26000}'::jsonb, null, false, null, pg_temp.fx_ver(v_room), 'snap-bid-qty');
  v := public.publish_fixture_recap(v_room, pg_temp.fx_ver(v_room), 'snap-recap-1');
  v_recap := (v->'data'->>'recapVersionId')::uuid;
  r := public.get_fixture_room(v_room);
  v_hash := r->'room'->>'snapshotHash';
  if r->'snapshot'->'cargo'->>'commodity_name' <> 'Wheat, Bulk' or (r->'snapshot'->'cargo'->>'qty_max_mt')::int <> 27500 then raise exception 'N1: baseline snapshot %', r->'snapshot'->'cargo'; end if;

  -- the marketplace moves on: the cargo is edited, the position goes off-market
  perform pg_temp.fx_owner();
  set local session_replication_role = replica;
  update public.cargo_listings set commodity_name = 'Corn, Bulk', qty_max_mt = 40000, notes = 'changed after the room opened' where id = pg_temp.fx_id('c1');
  update public.vessel_availability set status = 'FIXED', freight_idea_usd_mt = 99 where id = pg_temp.fx_id('a1');
  set local session_replication_role = origin;
  perform public.fn_refresh_matches();

  -- the charterer, who can no longer see the position through listing RLS, still reads the whole room
  perform pg_temp.fx_as('u_ch1');
  if exists (select 1 from public.vessel_availability where id = pg_temp.fx_id('a1')) then raise exception 'N1: the off-market position should be invisible to the charterer through RLS (test premise)'; end if;
  r := public.get_fixture_room(v_room);
  if r->'snapshot'->'cargo'->>'commodity_name' <> 'Wheat, Bulk' or (r->'snapshot'->'cargo'->>'qty_max_mt')::int <> 27500 then raise exception 'N1: snapshot rewritten by a listing edit: %', r->'snapshot'->'cargo'; end if;
  if r->'snapshot'->'vessel'->'availability'->>'status' <> 'OPEN' or (r->'snapshot'->'vessel'->'availability'->>'freight_idea_usd_mt')::numeric <> 26 then raise exception 'N1: vessel snapshot rewritten: %', r->'snapshot'->'vessel'->'availability'; end if;
  if r->'room'->>'snapshotHash' <> v_hash then raise exception 'N1: snapshot hash changed'; end if;
  if r::text like '%changed after the room opened%' then raise exception 'N1: post-creation notes leaked'; end if;
  if (select x->>'contentText' from jsonb_array_elements(r->'recaps') x where x->>'id' = v_recap::text) not like '%Wheat, Bulk%' then raise exception 'N1: recap text must keep the snapshot'; end if;
  -- the owner still reads too, and the inbox still lists the room from the snapshot
  perform pg_temp.fx_as('u_ow1');
  r := public.get_fixture_room(v_room);
  if r->'snapshot'->'vessel'->'vessel'->>'vessel_name' <> 'SEED VESSEL ONE' then raise exception 'N1: owner read broke'; end if;
  v_list := public.list_fixture_rooms(null, 50);
  if not exists (select 1 from jsonb_array_elements(v_list) x where x->>'id' = v_room::text and x->'cargo'->>'commodity' = 'Wheat, Bulk') then raise exception 'N1: inbox must come from the snapshot: %', v_list; end if;
  raise notice 'N1 ok: listing edits and a position going FIXED neither blank nor rewrite the room, the recap or the inbox';
end $$;

-- ── N2 · decision D4: the room never writes the listings; the sync view tells the truth ─
do $$
declare v jsonb; r jsonb; v_room uuid; v_code text; v_tid uuid; v_pid uuid; v_cargo text; v_vessel text;
begin
  perform pg_temp.fx_as('u_ow1');
  v := pg_temp.fx_create(pg_temp.fx_id('c2'), pg_temp.fx_id('a3'), pg_temp.fx_terms(), 'snap-create-2', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  perform pg_temp.fx_as('u_t1');
  v := public.respond_fixture_invitation(v_room, true, pg_temp.fx_ver(v_room), 'snap2-accept');
  foreach v_code in array array['cargo_grade', 'quantity', 'ports', 'laycan', 'ld_rates', 'freight'] loop
    v_tid := pg_temp.fx_term(v_room, v_code);
    perform pg_temp.fx_as('u_ow1');
    v := public.submit_fixture_proposal(v_room, v_tid, pg_temp.fx_value(v_code), null, false, null, pg_temp.fx_ver(v_room), 'snap2-offer-' || v_code);
    v_pid := (v->'data'->>'proposalId')::uuid;
    perform pg_temp.fx_as('u_t1');
    v := public.accept_fixture_proposal(v_room, v_pid, pg_temp.fx_ver(v_room), 'snap2-accept-' || v_code);
  end loop;
  perform pg_temp.fx_as('u_ow1');
  v := public.add_fixture_subject(v_room, 'Sub stem', null, 'cargo', null, pg_temp.fx_ver(v_room), 'snap2-sub');
  v := public.fix_fixture_on_subjects(v_room, pg_temp.fx_ver(v_room), 'snap2-fix');
  perform pg_temp.fx_as('u_t1');
  v := public.fix_fixture_on_subjects(v_room, pg_temp.fx_ver(v_room), 'snap2-fix-c');
  perform pg_temp.fx_as('u_ow1');
  r := public.get_fixture_room(v_room);
  if r->'room'->'listingSync'->'cargo'->>'target' <> 'OUT' or r->'room'->'listingSync'->'vessel'->>'target' <> 'ON SUBS' then raise exception 'N2: targets %', r->'room'->'listingSync'; end if;
  if r->'room'->'listingSync'->'cargo'->>'current' <> 'IN' or r->'room'->'listingSync'->'vessel'->>'current' <> 'OPEN' then raise exception 'N2: current statuses %', r->'room'->'listingSync'; end if;
  if (r->'room'->'listingSync'->>'outstanding')::boolean is not true then raise exception 'N2: sync must be outstanding'; end if;
  if not exists (select 1 from jsonb_array_elements(r->'events') x where x->>'type' = 'listing_sync.required' and x->'payload'->'target'->>'vessel_status' = 'ON SUBS') then raise exception 'N2: listing_sync.required event missing'; end if;
  -- the listings themselves were NOT touched by the room
  perform pg_temp.fx_owner();
  select status::text into v_cargo from public.cargo_listings where id = pg_temp.fx_id('c2');
  select status::text into v_vessel from public.vessel_availability where id = pg_temp.fx_id('a3');
  if v_cargo <> 'IN' or v_vessel <> 'OPEN' then raise exception 'N2: the room mutated a listing (% / %)', v_cargo, v_vessel; end if;
  -- an authorised owner updates the listings through the existing flows (simulated here): the requirement clears
  set local session_replication_role = replica;
  update public.vessel_availability set status = 'ON SUBS' where id = pg_temp.fx_id('a3');
  update public.cargo_listings set status = 'OUT' where id = pg_temp.fx_id('c2');
  set local session_replication_role = origin;
  perform public.fn_refresh_matches();
  perform pg_temp.fx_as('u_ow1');
  r := public.get_fixture_room(v_room);
  if (r->'room'->'listingSync'->>'outstanding')::boolean then raise exception 'N2: sync should be satisfied now: %', r->'room'->'listingSync'; end if;
  if not exists (select 1 from jsonb_array_elements(public.list_fixture_rooms(null, 50)) x where x->>'id' = v_room::text and (x->>'listingSyncOutstanding')::boolean = false) then raise exception 'N2: inbox flag'; end if;
  raise notice 'N2 ok: on_subjects records the requirement (cargo OUT, vessel ON SUBS), writes nothing to the listings, and the view clears once the owner updates them';
end $$;

do $$ begin raise notice 'FIXTURE SNAPSHOT SMOKE: ALL ASSERTIONS PASSED'; end $$;

rollback;
