-- Fixture Room · FIXTURE RLS SMOKE (generated by scripts/fixture-room-harness.sh from
-- seed_fixture_shape.sql + bodies/rls.sql; edit those, not this file).
-- BEGIN … ROLLBACK. Run as the database owner:
--   docker exec -i supabase_db_arab-ship-broker psql -U postgres -d postgres -v ON_ERROR_STOP=1 -f - < supabase/tests/fixture_room/fixture_rls_smoke.sql

begin;

-- Fixture Room · test seed (23 Sep 2026). Fixed ids, idempotent, and meant to
-- run INSIDE the caller's transaction: every smoke file inlines this block
-- after its BEGIN (scripts/fixture-room-harness.sh assembles the files from
-- this seed and the bodies under supabase/tests/fixture_room/bodies, so the
-- copies cannot drift); fixture_race_two_sessions.sh runs it in a committed
-- transaction and removes the rows afterwards.
--
-- Gates and triggers are skipped while the listings are inserted (these are
-- test rows, not member submissions); check constraints still apply. The
-- role is reset to origin before any Fixture Room RPC runs, so the
-- append-only triggers are live for the assertions.
--
-- Shape:  two member organisations (charterer with two seats, owner with one
-- active and one pending seat), an outsider organisation, a platform admin,
-- an individual member with no organisation, a T1 member, a contact-backed
-- listing, a listing owned by an admin (platform-synced), a sanctioned vessel
-- and a TBN vessel. Every counterparty case of amendment A1 is reachable.
set local session_replication_role = replica;

create temp table if not exists fx_ids (k text primary key, v uuid);
grant all on table fx_ids to authenticated;
insert into fx_ids (k, v) values
  ('org_ch',  '00000000-0000-4000-8000-0000000000c1'),
  ('org_ow',  '00000000-0000-4000-8000-0000000000c2'),
  ('org_out', '00000000-0000-4000-8000-0000000000c3'),
  ('u_ch1',   '00000000-0000-4000-8000-0000000000a1'),
  ('u_ch2',   '00000000-0000-4000-8000-0000000000a2'),
  ('u_ow1',   '00000000-0000-4000-8000-0000000000a3'),
  ('u_out',   '00000000-0000-4000-8000-0000000000a4'),
  ('u_adm',   '00000000-0000-4000-8000-0000000000a5'),
  ('u_solo',  '00000000-0000-4000-8000-0000000000a6'),
  ('u_pend',  '00000000-0000-4000-8000-0000000000a7'),
  ('u_t1',    '00000000-0000-4000-8000-0000000000a8'),
  ('u_two',   '00000000-0000-4000-8000-0000000000a9'),
  ('u_pendcur','00000000-0000-4000-8000-0000000000aa'),
  ('org_two', '00000000-0000-4000-8000-0000000000c4'),
  ('org_x',   '00000000-0000-4000-8000-0000000000c5'),
  ('c5',      '00000000-0000-4000-8000-0000000000e5'),
  ('contact', '00000000-0000-4000-8000-0000000000d1'),
  ('c1',      '00000000-0000-4000-8000-0000000000e1'),
  ('c2',      '00000000-0000-4000-8000-0000000000e2'),
  ('c3',      '00000000-0000-4000-8000-0000000000e3'),
  ('c4',      '00000000-0000-4000-8000-0000000000e4'),
  ('v1',      '00000000-0000-4000-8000-0000000000f1'),
  ('v2',      '00000000-0000-4000-8000-0000000000f2'),
  ('v3',      '00000000-0000-4000-8000-0000000000f3'),
  ('a1',      '00000000-0000-4000-8000-0000000000b1'),
  ('a2',      '00000000-0000-4000-8000-0000000000b2'),
  ('a3',      '00000000-0000-4000-8000-0000000000b3'),
  ('a4',      '00000000-0000-4000-8000-0000000000b4')
on conflict (k) do nothing;

-- ── helpers (temp; they vanish with the transaction) ────────────────────────
create or replace function pg_temp.fx_id(p_k text) returns uuid language sql stable as $f$ select v from fx_ids where k = p_k $f$;
-- act as a seeded member: the JWT claims PostgREST would set, and the authenticated role
create or replace function pg_temp.fx_as(p_k text, p_admin boolean default false) returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', pg_temp.fx_id(p_k)::text, true);
  perform set_config('request.jwt.claims', json_build_object('sub', pg_temp.fx_id(p_k), 'role', 'authenticated',
            'app_metadata', case when p_admin then json_build_object('role', 'admin') else json_build_object('role', 'member') end)::text, true);
  execute 'set local role authenticated';
end $f$;
create or replace function pg_temp.fx_anon() returns void language plpgsql as $f$
begin
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
  execute 'set local role anon';
end $f$;
create or replace function pg_temp.fx_owner() returns void language plpgsql as $f$
begin
  execute 'reset role';
  perform set_config('request.jwt.claim.sub', '', true);
  perform set_config('request.jwt.claims', '', true);
end $f$;
-- run a statement and report 'OK' or the FX_ prefix it raised
create or replace function pg_temp.fx_err(p_sql text) returns text language plpgsql as $f$
declare v jsonb;
begin
  execute p_sql into v;
  return 'OK';
exception when others then
  return coalesce(substring(sqlerrm from '^(FX_[A-Z_]+):'), 'ERR ' || sqlstate || ' ' || left(sqlerrm, 160));
end $f$;
create or replace function pg_temp.fx_call(p_sql text) returns jsonb language plpgsql as $f$
declare v jsonb; begin execute p_sql into v; return v; end $f$;
-- owner-level peeks used by assertions only
create or replace function pg_temp.fx_term(p_room uuid, p_code text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_terms where room_id = p_room and code = p_code $f$;
create or replace function pg_temp.fx_party(p_room uuid, p_side text, p_capacity text) returns uuid language sql stable security definer as $f$
  select id from public.fixture_parties where room_id = p_room and side = p_side and capacity = p_capacity and status in ('invited', 'active') order by created_at limit 1 $f$;
create or replace function pg_temp.fx_events(p_room uuid) returns bigint language sql stable security definer as $f$
  select count(*) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_event_types(p_room uuid) returns text language sql stable security definer as $f$
  select string_agg(type, ',' order by seq) from public.fixture_events where room_id = p_room $f$;
create or replace function pg_temp.fx_ver(p_room uuid) returns integer language sql stable security definer as $f$
  select version from public.fixture_rooms where id = p_room $f$;
create or replace function pg_temp.fx_status(p_room uuid) returns text language sql stable security definer as $f$
  select status from public.fixture_rooms where id = p_room $f$;
-- the v1 catalogue, as lib/fixture-room/terms.ts sends it
create or replace function pg_temp.fx_terms() returns jsonb language sql immutable as $f$ select $j$[
  {"code":"cargo_grade","label":"Cargo & grade","category":"cargo","sortOrder":1,"valueKind":"text","required":true,"hint":"Listing: Wheat, Bulk"},
  {"code":"quantity","label":"Quantity","category":"cargo","sortOrder":2,"valueKind":"number","unit":"MT","required":true},
  {"code":"ports","label":"Load / discharge ports","category":"route","sortOrder":3,"valueKind":"port_pair","required":true},
  {"code":"laycan","label":"Laycan","category":"timing","sortOrder":4,"valueKind":"date_range","required":true},
  {"code":"ld_rates","label":"Load / discharge rates","category":"operations","sortOrder":5,"valueKind":"rate_pair","unit":"MT/day","required":true},
  {"code":"freight","label":"Freight & terms","category":"money","sortOrder":6,"valueKind":"money_per_mt","unit":"USD/MT","required":true}]$j$::jsonb $f$;
-- the catalogue with one deviation, for the FR-H2 negatives (every one must be refused)
create or replace function pg_temp.fx_terms_mut(p_op text) returns jsonb language plpgsql immutable as $f$
declare c jsonb := pg_temp.fx_terms(); o jsonb := '[]'::jsonb; t jsonb;
begin
  for t in select * from jsonb_array_elements(c) loop
    if p_op = 'missing' and t->>'code' = 'quantity' then continue; end if;
    if p_op = 'relabelled' and t->>'code' = 'freight' then t := t || '{"label":"Freight"}'::jsonb; end if;
    if p_op = 'retyped' and t->>'code' = 'quantity' then t := t || '{"valueKind":"text"}'::jsonb; end if;
    if p_op = 'optionalised' and t->>'code' = 'laycan' then t := t || '{"required":false}'::jsonb; end if;
    if p_op = 'reordered' and t->>'code' = 'ports' then t := t || '{"sortOrder":4}'::jsonb; end if;
    if p_op = 'recategorised' and t->>'code' = 'ports' then t := t || '{"category":"money"}'::jsonb; end if;
    if p_op = 'reunited' and t->>'code' = 'quantity' then t := t || '{"unit":"kg"}'::jsonb; end if;
    if p_op = 'renamed' and t->>'code' = 'ld_rates' then t := t || '{"code":"rates"}'::jsonb; end if;
    if p_op = 'unrequired' and t->>'code' = 'laycan' then t := t - 'required'; end if;
    o := o || t;
  end loop;
  if p_op = 'extra' then o := o || '{"code":"demurrage","label":"Demurrage","category":"money","sortOrder":7,"valueKind":"number","required":true}'::jsonb; end if;
  if p_op = 'duplicate' then o := o || (c->0); end if;
  return o;
end $f$;
-- owner-level peek: the latest non-terminal room of a pairing (refs are monotonic; created_at is the transaction time)
create or replace function pg_temp.fx_room(p_cargo uuid, p_avail uuid) returns uuid language sql stable security definer as $f$
  select id from public.fixture_rooms where cargo_listing_id = p_cargo and vessel_availability_id = p_avail
     and status not in ('withdrawn', 'failed', 'expired') order by ref desc limit 1 $f$;
-- owner-level peek: the identity a principal party was recorded with
create or replace function pg_temp.fx_party_identity(p_room uuid, p_side text) returns jsonb language sql stable security definer as $f$
  select jsonb_build_object('org_id', org_id, 'user_id', user_id, 'mode', participation_mode) from public.fixture_parties
   where room_id = p_room and side = p_side and capacity = 'principal' and status in ('invited', 'active') order by created_at limit 1 $f$;
-- one agreeable value per term code
create or replace function pg_temp.fx_value(p_code text) returns jsonb language sql immutable as $f$
  select ($j${"cargo_grade":{"text":"Wheat in bulk, 2026 crop"},"quantity":{"num":26000},
            "ports":{"load":"ZZFXA","disch":"ZZFXB","load_name":"Fixture Load Port","disch_name":"Fixture Disch Port"},
            "laycan":{"from":"2026-10-05","to":"2026-10-12"},"ld_rates":{"load":8000,"disch":6000},
            "freight":{"num":25.75,"currency":"USD"}}$j$::jsonb)->p_code $f$;

-- ── people and organisations ────────────────────────────────────────────────
insert into auth.users (id, email, aud, role)
select v, k || '@fixture.test', 'authenticated', 'authenticated' from fx_ids where k like 'u\_%'
on conflict (id) do nothing;

insert into public.organizations (id, name, org_type, desk_contact_name, desk_email, desk_phone, country, fleet_total) values
  (pg_temp.fx_id('org_ch'),  'Seed Charterers Ltd', 'charterer', 'Chartering Desk', 'desk@seed-charterers.test', '+20 100 000 0001', 'Egypt', null),
  (pg_temp.fx_id('org_ow'),  'Seed Owners SA',      'owner',     'Owner''s Desk',   'desk@seed-owners.test',     '+30 210 000 0002', 'Greece', 7),
  (pg_temp.fx_id('org_out'), 'Seed Outsiders LLC',  'broker',    'Outsider Desk',   'desk@seed-outsiders.test',  null,               'UAE', null),
  (pg_temp.fx_id('org_two'), 'Seed Second Org',     'charterer', 'Second Desk',     'desk@seed-second.test',     null,               'Egypt', null),
  (pg_temp.fx_id('org_x'),   'Seed Unrelated Co',   'broker',    'Unrelated Desk',  'desk@seed-unrelated.test',  null,               'Greece', null)
on conflict do nothing;

insert into public.users (id, supabase_user_id, email, full_name, company, role, subscription_tier, is_active) values
  (pg_temp.fx_id('u_ch1'),  pg_temp.fx_id('u_ch1'),  'u_ch1@fixture.test',  'Seed Charterer One', 'Seed Charterers Ltd', 'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_ch2'),  pg_temp.fx_id('u_ch2'),  'u_ch2@fixture.test',  'Seed Charterer Two', 'Seed Charterers Ltd', 'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('u_ow1'),  'u_ow1@fixture.test',  'Seed Owner One',     'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_out'),  pg_temp.fx_id('u_out'),  'u_out@fixture.test',  'Seed Outsider',      'Seed Outsiders LLC',  'broker',       'T3', true),
  (pg_temp.fx_id('u_adm'),  pg_temp.fx_id('u_adm'),  'u_adm@fixture.test',  'Seed Admin',         'Arab ShipBroker',     'admin',        'T4', true),
  (pg_temp.fx_id('u_solo'), pg_temp.fx_id('u_solo'), 'u_solo@fixture.test', 'Seed Solo Owner',    'Solo Shipping',       'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_pend'), pg_temp.fx_id('u_pend'), 'u_pend@fixture.test', 'Seed Pending',       'Seed Owners SA',      'vessel_owner', 'T3', true),
  (pg_temp.fx_id('u_t1'),   pg_temp.fx_id('u_t1'),   'u_t1@fixture.test',   'Seed Tier One',      'Tier One Trading',    'cargo_owner',  'T1', true),
  (pg_temp.fx_id('u_two'),  pg_temp.fx_id('u_two'),  'u_two@fixture.test',  'Seed Two Seats',     'Seed Second Org',     'cargo_owner',  'T3', true),
  (pg_temp.fx_id('u_pendcur'), pg_temp.fx_id('u_pendcur'), 'u_pendcur@fixture.test', 'Seed Pending Current', 'Seed Owners SA', 'vessel_owner', 'T3', true)
on conflict (id) do nothing;

-- Seats. u_two holds two ACTIVE seats (admin in org_ch first, broker in
-- org_two second) and owns C5 through org_two: a seat-guessing rule would
-- pick org_ch (FR-H1). u_solo owns A4 personally and sits in an unrelated
-- organisation (org_x): the party must be the member, never that seat.
-- u_pend is pending and not current; u_pendcur is pending AND current, the
-- legacy shape the Phase 0 review requires to be refused (FR-M1).
insert into public.organization_members (org_id, user_id, member_role, is_current, status) values
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_ch2'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_ow1'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_out'), pg_temp.fx_id('u_out'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pend'), 'broker', false, 'pending'),
  (pg_temp.fx_id('org_ch'),  pg_temp.fx_id('u_two'),  'admin',  true,  'active'),
  (pg_temp.fx_id('org_two'), pg_temp.fx_id('u_two'),  'broker', true,  'active'),
  (pg_temp.fx_id('org_x'),   pg_temp.fx_id('u_solo'), 'admin',  true,  'active'),
  (pg_temp.fx_id('org_ow'),  pg_temp.fx_id('u_pendcur'), 'broker', true, 'pending')
on conflict do nothing;

insert into public.contacts (id, kind, display_name, email, phone, role, source) values
  (pg_temp.fx_id('contact'), 'desk', 'Seed Brokers Desk', 'desk@seed-brokers.test', '+90 212 000 0003', 'broker', 'admin')
on conflict do nothing;

-- ── listings ────────────────────────────────────────────────────────────────
insert into public.ports (locode, trade_name, country, zone, port_type, is_active, is_verified) values
  ('ZZFXA', 'Fixture Load Port',  'Egypt',  'E.MED', 'Sea Port', true, true),
  ('ZZFXB', 'Fixture Disch Port', 'Turkey', 'E.MED', 'Sea Port', true, true)
on conflict do nothing;

insert into public.cargo_listings (id, ref, status, review_status, cargo_type, commodity_name, is_dg_cargo, is_grain_cargo,
  qty_min_mt, qty_max_mt, stowage_factor, load_port_locode, load_port_name, load_zone, disch_port_locode, disch_port_name, disch_zone,
  laycan_from, laycan_to, is_spot, load_rate, disch_rate, load_terms, freight_idea_usd_mt, commission_pct, demurrage_rate, broker, notes, broker_contact_id) values
  (pg_temp.fx_id('c1'), 'FXC-001', 'IN', 'APPROVED', 'Dry Bulk', 'Wheat, Bulk', false, true, 25000, 27500, 1.25,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 10, current_date + 20, false,
   '8000', '6000', 'FIOST', 24.50, 2.5, 12000, 'Seed Brokers (Tasos)', 'call charterer mobile +20 100 000 9999', null),
  (pg_temp.fx_id('c2'), 'FXC-002', 'IN', 'APPROVED', 'Dry Bulk', 'Barley', false, true, 20000, 22000, 1.40,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 12, current_date + 22, false,
   '7000', '5000', 'FIO', 22.00, 2.5, 10000, null, null, null),
  (pg_temp.fx_id('c3'), 'FXC-003', 'IN', 'APPROVED', 'Dry Bulk', 'Clinker', false, false, 30000, 33000, 0.90,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 15, current_date + 25, false,
   '9000', '7000', 'FIOST', 18.00, 2.5, 11000, null, null, null),
  (pg_temp.fx_id('c4'), 'FXC-004', 'IN', 'APPROVED', 'Break Bulk', 'Steel coils', false, false, 12000, 13000, null,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 8, current_date + 18, false,
   '3000', '3000', 'FIOST', 31.00, 2.5, 15000, 'Seed Brokers Desk', 'desk@seed-brokers.test', pg_temp.fx_id('contact')),
  (pg_temp.fx_id('c5'), 'FXC-005', 'IN', 'APPROVED', 'Dry Bulk', 'Corn', false, true, 24000, 26000, 1.30,
   'ZZFXA', 'Fixture Load Port', 'E.MED', 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 11, current_date + 21, false,
   '8000', '6000', 'FIOST', 23.00, 2.5, 11500, null, null, null)
on conflict (id) do nothing;

insert into public.vessels (id, vessel_name, imo_number, vessel_type, dwt_grain, build_year, flag, is_geared, grain_certified, dg_certified,
  max_draft_m, is_sanctioned, owner_company, pic_name, phone, email_chartering, is_tbn) values
  (pg_temp.fx_id('v1'), 'SEED VESSEL ONE', '9000001', 'Bulk Carrier', 30000, 2012, 'Malta', true, true, false, 10.5, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', false),
  (pg_temp.fx_id('v2'), 'SEED SANCTIONED', '9000002', 'Bulk Carrier', 28000, 2008, 'Panama', false, false, false, 10.0, true,
   'Sanctioned Owner', 'Capt. Sanction', '+1 000 000 0000', 'sanctioned@example.test', false),
  (pg_temp.fx_id('v3'), 'SEED TBN HULL', null, 'Bulk Carrier', 32000, 2015, 'Liberia', true, true, false, 11.0, false,
   'Seed Owners SA', 'Capt. Seed', '+30 210 000 7777', 'chartering@seed-owners.test', true)
on conflict (id) do nothing;

insert into public.vessel_availability (id, vessel_id, open_port_locode, open_port_name, open_zone, open_date, status, review_status, freight_idea_usd_mt, accepts_part_cargo, notes) values
  (pg_temp.fx_id('a1'), pg_temp.fx_id('v1'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 26.00, false, 'owner mobile +30 690 000 0000'),
  (pg_temp.fx_id('a2'), pg_temp.fx_id('v2'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 5,  'OPEN', 'APPROVED', 20.00, false, null),
  (pg_temp.fx_id('a3'), pg_temp.fx_id('v3'), 'ZZFXA', 'Fixture Load Port', 'E.MED', current_date + 7,  'OPEN', 'APPROVED', 27.00, false, null),
  (pg_temp.fx_id('a4'), pg_temp.fx_id('v1'), 'ZZFXB', 'Fixture Disch Port', 'E.MED', current_date + 40, 'OPEN', 'APPROVED', 25.00, true, null)
on conflict (id) do nothing;

insert into public.listing_ownership (listing_type, listing_id, owner_user_id, owner_org_id, role, is_current, transfer_reason) values
  ('cargo', pg_temp.fx_id('c1'), pg_temp.fx_id('u_ch1'), pg_temp.fx_id('org_ch'), 'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c2'), pg_temp.fx_id('u_t1'),  null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c3'), pg_temp.fx_id('u_adm'), null,                    'primary', true, 'initial_post'),
  ('cargo', pg_temp.fx_id('c5'), pg_temp.fx_id('u_two'), pg_temp.fx_id('org_two'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a1'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a2'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a3'), pg_temp.fx_id('u_ow1'),  pg_temp.fx_id('org_ow'), 'primary', true, 'initial_post'),
  ('vessel_availability', pg_temp.fx_id('a4'), pg_temp.fx_id('u_solo'), null,                    'primary', true, 'initial_post')
on conflict do nothing;

set local session_replication_role = origin;
-- ── end of seed ─────────────────────────────────────────────────────────────

-- ── R1 · no member reads a fixture table through PostgREST ──────────────────
do $$
declare t text; v_ok boolean; v_bad text := '';
begin
  perform pg_temp.fx_as('u_ch1');
  foreach t in array array['fixture_rooms', 'fixture_parties', 'fixture_terms', 'fixture_proposals', 'fixture_subjects', 'fixture_messages', 'fixture_events', 'fixture_recap_versions', 'fixture_access_log'] loop
    v_ok := false;
    begin
      execute format('select 1 from public.%I limit 1', t);
    exception when insufficient_privilege then v_ok := true;
    end;
    if not v_ok then v_bad := v_bad || t || ' '; end if;
    v_ok := false;
    begin
      execute format('insert into public.%I default values', t);
    exception when insufficient_privilege then v_ok := true;
    when others then v_ok := false;
    end;
    if not v_ok then v_bad := v_bad || t || '(insert) '; end if;
  end loop;
  perform pg_temp.fx_owner();
  if v_bad <> '' then raise exception 'R1: authenticated can reach: %', v_bad; end if;
  -- the internal helpers are not member-callable either
  perform pg_temp.fx_as('u_ch1');
  v_ok := false;
  begin
    perform public.fn_fixture_snapshot_cargo(pg_temp.fx_id('c1'));
  exception when insufficient_privilege then v_ok := true;
  end;
  perform pg_temp.fx_owner();
  if not v_ok then raise exception 'R1: fn_fixture_snapshot_cargo is executable by members'; end if;
  raise notice 'R1 ok: every fixture table and internal helper is closed to authenticated';
end $$;

-- ── R2 · party-based access: outsider, pending member, anon ─────────────────
do $$
declare v jsonb; v_room uuid; e text; v_ok boolean; v_list jsonb;
begin
  perform pg_temp.fx_as('u_ch1');
  v := public.create_fixture_room(pg_temp.fx_id('c1'), pg_temp.fx_id('a1'), pg_temp.fx_terms(), 'rls-create-1', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  -- an outsider (member of another organisation)
  perform pg_temp.fx_as('u_out');
  e := pg_temp.fx_err(format('select public.get_fixture_room(%L)', v_room));
  if e <> 'FX_AUTH' then raise exception 'R2: outsider read must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select to_jsonb(public.get_fixture_room_version(%L))', v_room));
  if e <> 'FX_AUTH' then raise exception 'R2: outsider version poll must be FX_AUTH, got %', e; end if;
  v_list := public.list_fixture_rooms(null, 50);
  if jsonb_array_length(v_list) <> 0 then raise exception 'R2: outsider inbox must be empty'; end if;
  e := pg_temp.fx_err(format('select public.post_fixture_message(%L, %L, %L, %L, null, %s, %L)', v_room, 'hi', 'note', 'room', pg_temp.fx_ver(v_room), 'rls-out-msg'));
  if e <> 'FX_AUTH' then raise exception 'R2: outsider command must be FX_AUTH, got %', e; end if;
  -- a PENDING member of the owner organisation has no access (is_current = false)
  perform pg_temp.fx_as('u_pend');
  e := pg_temp.fx_err(format('select public.get_fixture_room(%L)', v_room));
  if e <> 'FX_AUTH' then raise exception 'R2: pending member read must be FX_AUTH, got %', e; end if;
  -- a PENDING member whose seat row is nonetheless CURRENT (a legacy shape) has no access either (FR-M1: current AND active)
  perform pg_temp.fx_as('u_pendcur');
  e := pg_temp.fx_err(format('select public.get_fixture_room(%L)', v_room));
  if e <> 'FX_AUTH' then raise exception 'R2: pending-but-current member read must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select to_jsonb(public.get_fixture_room_version(%L))', v_room));
  if e <> 'FX_AUTH' then raise exception 'R2: pending-but-current member poll must be FX_AUTH, got %', e; end if;
  v_list := public.list_fixture_rooms(null, 50);
  if jsonb_array_length(v_list) <> 0 then raise exception 'R2: pending-but-current member inbox must be empty'; end if;
  e := pg_temp.fx_err(format('select public.respond_fixture_invitation(%L, true, %s, %L)', v_room, pg_temp.fx_ver(v_room), 'rls-pendcur-accept'));
  if e <> 'FX_AUTH' and e <> 'FX_STATE' then raise exception 'R2: pending-but-current member must not answer the organisation''s invitation, got %', e; end if;
  -- the charterer''s colleague (same organisation, broker seat) is a participant through the organisation party
  perform pg_temp.fx_as('u_ch2');
  v := public.get_fixture_room(v_room);
  if (v->'viewer'->>'side') <> 'cargo' then raise exception 'R2: colleague must resolve to the cargo side'; end if;
  -- anon cannot even execute the RPCs
  perform pg_temp.fx_anon();
  v_ok := false;
  begin
    perform public.get_fixture_room(v_room);
  exception when insufficient_privilege then v_ok := true;
  end;
  perform pg_temp.fx_owner();
  if not v_ok then raise exception 'R2: anon can execute get_fixture_room'; end if;
  raise notice 'R2 ok: outsider, pending member (current or not) and anon refused; a colleague of a party organisation is a participant';
end $$;

-- ── R3 · capacity: a viewer reads but cannot make commercial commands ───────
do $$
declare v jsonb; r jsonb; v_room uuid; e text; v_tid uuid;
begin
  perform pg_temp.fx_as('u_ch1');
  v := public.create_fixture_room(pg_temp.fx_id('c1'), pg_temp.fx_id('a1'), pg_temp.fx_terms(), 'rls-create-1', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  v := public.invite_fixture_party(v_room, 'cargo', 'viewer', pg_temp.fx_id('org_out'), null, pg_temp.fx_ver(v_room), 'rls-invite-viewer');
  -- inviting onto the other side is refused for a principal
  e := pg_temp.fx_err(format('select public.invite_fixture_party(%L, %L, %L, null, %L, %s, %L)', v_room, 'vessel', 'viewer', pg_temp.fx_id('u_solo'), pg_temp.fx_ver(v_room), 'rls-invite-other-side'));
  if e <> 'FX_AUTH' then raise exception 'R3: inviting onto the other side must be FX_AUTH, got %', e; end if;
  perform pg_temp.fx_as('u_out');
  v := public.respond_fixture_invitation(v_room, true, pg_temp.fx_ver(v_room), 'rls-viewer-accept');
  r := public.get_fixture_room(v_room);
  if (r->'viewer'->'capabilities'->>'canPropose')::boolean or (r->'viewer'->'capabilities'->>'canAccept')::boolean or (r->'viewer'->'capabilities'->>'canFixOnSubjects')::boolean then
    raise exception 'R3: a viewer must have no commercial capability: %', r->'viewer'->'capabilities'; end if;
  if (r->'viewer'->'capabilities'->>'canMessage')::boolean is not true then raise exception 'R3: a viewer may message'; end if;
  v_tid := pg_temp.fx_term(v_room, 'freight');
  e := pg_temp.fx_err(format('select public.submit_fixture_proposal(%L, %L, %L::jsonb, null, false, null, %s, %L)', v_room, v_tid, '{"num": 1}', pg_temp.fx_ver(v_room), 'rls-viewer-bid'));
  if e <> 'FX_AUTH' then raise exception 'R3: viewer proposing must be FX_AUTH (server refuses, not just the UI), got %', e; end if;
  e := pg_temp.fx_err(format('select public.add_fixture_subject(%L, %L, null, null, null, %s, %L)', v_room, 'x', pg_temp.fx_ver(v_room), 'rls-viewer-subject'));
  if e <> 'FX_STATE' and e <> 'FX_AUTH' then raise exception 'R3: viewer adding a subject must be refused, got %', e; end if;
  raise notice 'R3 ok: viewer reads and messages; every commercial command refused server-side';
end $$;

-- ── R4 · tier: invited parties act regardless of tier; admin inspection is audited and unmasked ─
do $$
declare v jsonb; r jsonb; v_room uuid; e text; v_tid uuid; v_before bigint; v_after bigint; p jsonb;
begin
  -- the owner (T3) opens a room on the T1 member''s cargo: the T1 member is invited and may act
  perform pg_temp.fx_as('u_ow1');
  v := public.create_fixture_room(pg_temp.fx_id('c2'), pg_temp.fx_id('a1'), pg_temp.fx_terms(), 'rls-create-c2', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  perform pg_temp.fx_as('u_t1');
  v := public.respond_fixture_invitation(v_room, true, pg_temp.fx_ver(v_room), 'rls-t1-accept');
  v_tid := pg_temp.fx_term(v_room, 'freight');
  v := public.submit_fixture_proposal(v_room, v_tid, '{"num": 21}'::jsonb, null, false, null, pg_temp.fx_ver(v_room), 'rls-t1-bid');
  if (v->>'ok')::boolean is not true then raise exception 'R4: a T1 invitee must be able to bid'; end if;
  -- admin: unmasked read, every read logged
  perform pg_temp.fx_owner();
  select count(*) into v_before from public.fixture_access_log where room_id = v_room;
  perform pg_temp.fx_as('u_adm', true);
  r := public.get_fixture_room(v_room);
  perform pg_temp.fx_owner();
  select count(*) into v_after from public.fixture_access_log where room_id = v_room;
  if v_after <> v_before + 1 then raise exception 'R4: admin read must write one fixture_access_log row (% → %)', v_before, v_after; end if;
  if not exists (select 1 from public.fixture_access_log where room_id = v_room and user_id = pg_temp.fx_id('u_adm') and is_admin) then raise exception 'R4: access log row must name the admin'; end if;
  if (r->'viewer'->>'isAdmin')::boolean is not true then raise exception 'R4: admin flag'; end if;
  select x into p from jsonb_array_elements(r->'parties') x where x->>'side' = 'vessel' and x->>'capacity' = 'principal';
  if p->>'orgId' <> pg_temp.fx_id('org_ow')::text or p->>'name' <> 'Seed Owners SA' then raise exception 'R4: admin must see raw ids and names: %', p; end if;
  -- the member read is NOT logged
  select count(*) into v_before from public.fixture_access_log where room_id = v_room;
  perform pg_temp.fx_as('u_ow1');
  r := public.get_fixture_room(v_room);
  perform pg_temp.fx_owner();
  select count(*) into v_after from public.fixture_access_log where room_id = v_room;
  if v_after <> v_before then raise exception 'R4: member reads must not write the access log'; end if;
  -- the log is append-only
  begin
    delete from public.fixture_access_log where room_id = v_room;
    raise exception 'R4: access log delete must be refused';
  exception when others then
    if sqlerrm not like 'FX_IMMUTABLE:%' then raise; end if;
  end;
  -- the admin console reads the log through admin_fixture_access_log: admins only, and reading it is not logged
  perform pg_temp.fx_as('u_ow1');
  e := pg_temp.fx_err(format('select public.admin_fixture_access_log(%L, 50)', v_room));
  if e <> 'FX_AUTH' then raise exception 'R4: a member reading the access log must be FX_AUTH, got %', e; end if;
  perform pg_temp.fx_owner();
  select count(*) into v_before from public.fixture_access_log where room_id = v_room;
  perform pg_temp.fx_as('u_adm', true);
  r := public.admin_fixture_access_log(v_room, 50);
  perform pg_temp.fx_owner();
  select count(*) into v_after from public.fixture_access_log where room_id = v_room;
  -- (an admin who is the platform party of the room is logged as 'mediate'; an admin who is not, as 'inspect')
  if jsonb_array_length(r) < 1 or not exists (select 1 from jsonb_array_elements(r) x where x->>'reason' in ('inspect', 'mediate') and (x->>'isAdmin')::boolean and x->>'userId' = pg_temp.fx_id('u_adm')::text) then
    raise exception 'R4: the access log read must list the admin inspection: %', r; end if;
  if v_after <> v_before then raise exception 'R4: reading the access log must not write to it'; end if;
  perform pg_temp.fx_as('u_adm', true);
  e := pg_temp.fx_err(format('select public.admin_fixture_access_log(%L, 50)', gen_random_uuid()));
  if e <> 'FX_NOT_FOUND' then raise exception 'R4: an unknown room must be FX_NOT_FOUND, got %', e; end if;
  perform pg_temp.fx_owner();
  raise notice 'R4 ok: T1 invitee acts; admin reads are unmasked and logged; member reads are not; the log is append-only and admin-only to read';
end $$;

-- ── R5 · an anonymised member (the INT-H1 tombstone) cannot act as its former party; the counterparty keeps the room ─
do $$
declare v jsonb; r jsonb; v_room uuid; e text; p jsonb; v_tid uuid;
begin
  -- the charterer opens a room on the solo owner's position; the owner accepts, offers, and agrees to disclose
  perform pg_temp.fx_as('u_ch1');
  v := public.create_fixture_room(pg_temp.fx_id('c1'), pg_temp.fx_id('a4'), pg_temp.fx_terms(), 'rls-create-a4', '{}'::jsonb);
  v_room := (v->'data'->>'roomId')::uuid;
  perform pg_temp.fx_as('u_solo');
  v := public.respond_fixture_invitation(v_room, true, pg_temp.fx_ver(v_room), 'rls-a4-accept');
  v_tid := pg_temp.fx_term(v_room, 'freight');
  v := public.submit_fixture_proposal(v_room, v_tid, '{"num": 26}'::jsonb, null, false, null, pg_temp.fx_ver(v_room), 'rls-a4-offer');
  v := public.agree_fixture_disclosure(v_room, pg_temp.fx_ver(v_room), 'rls-a4-disc-solo');
  -- the platform erases the solo owner: the tombstone shape fn_anonymize_account leaves behind
  -- (integration branch b6aed98): row kept, PII scrubbed, inactive, login link severed, seats rejected
  perform pg_temp.fx_owner();
  update public.users set full_name = 'Deleted account', company = null, email = null, phone = null, role = null,
         is_active = false, subscription_tier = 'T1', supabase_user_id = null where id = pg_temp.fx_id('u_solo');
  update public.organization_members set is_current = false, status = 'rejected' where user_id = pg_temp.fx_id('u_solo');
  -- a token the erased account still held is refused at the Fixture boundary: read, poll, inbox, answer, act, create
  perform pg_temp.fx_as('u_solo');
  e := pg_temp.fx_err(format('select public.get_fixture_room(%L)', v_room));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member read must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select to_jsonb(public.get_fixture_room_version(%L))', v_room));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member poll must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err('select public.list_fixture_rooms(null, 50)');
  if e <> 'FX_AUTH' then raise exception 'R5: erased member inbox must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select public.submit_fixture_proposal(%L, %L, %L::jsonb, null, false, null, %s, %L)', v_room, v_tid, '{"num": 25}', pg_temp.fx_ver(v_room), 'rls-a4-erased-offer'));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member proposing must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select public.respond_fixture_invitation(%L, true, %s, %L)', v_room, pg_temp.fx_ver(v_room), 'rls-a4-erased-answer'));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member answering must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select public.post_fixture_message(%L, %L, %L, %L, null, %s, %L)', v_room, 'still here?', 'note', 'room', pg_temp.fx_ver(v_room), 'rls-a4-erased-msg'));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member messaging must be FX_AUTH, got %', e; end if;
  e := pg_temp.fx_err(format('select public.create_fixture_room(%L, %L, pg_temp.fx_terms(), %L, %L::jsonb)', pg_temp.fx_id('c2'), pg_temp.fx_id('a4'), 'rls-a4-erased-create', '{}'));
  if e <> 'FX_AUTH' then raise exception 'R5: erased member creating must be FX_AUTH, got %', e; end if;
  -- the counterparty keeps the room and its history, and never sees a person behind the vacated seat
  perform pg_temp.fx_as('u_ch1');
  r := public.get_fixture_room(v_room);
  select x into p from jsonb_array_elements(r->'parties') x where x->>'side' = 'vessel' and x->>'capacity' = 'principal';
  if p->>'label' <> 'Owner side' or p->>'status' <> 'active' then raise exception 'R5: the vacated seat must keep its label and status: %', p; end if;
  if not exists (select 1 from jsonb_array_elements(r->'terms') x where x->>'code' = 'freight' and x->'vesselPosition'->>'displayValue' = '$26.00/MT') then
    raise exception 'R5: the erased member''s offer must remain on the record'; end if;
  if r::text like '%Seed Solo Owner%' or r::text like '%u_solo@fixture.test%' or r::text like '%Solo Shipping%' then
    raise exception 'R5: PII of the erased member reached the counterparty'; end if;
  -- disclosure completes from the charterer's side: the tombstone discloses as a generic label, never a person
  v := public.agree_fixture_disclosure(v_room, pg_temp.fx_ver(v_room), 'rls-a4-disc-ch');
  if (v->'data'->>'disclosed')::boolean is not true then raise exception 'R5: both principals agreed, disclosure expected'; end if;
  r := public.get_fixture_room(v_room);
  select x into p from jsonb_array_elements(r->'parties') x where x->>'side' = 'vessel' and x->>'capacity' = 'principal';
  if p->>'name' <> 'Registered member' or p->>'deskLabel' is not null then raise exception 'R5: an erased member discloses as "Registered member" only, got %', p; end if;
  if r::text like '%Deleted account%' then raise exception 'R5: the tombstone name must not surface either'; end if;
  raise notice 'R5 ok: an anonymised member is refused on read, poll, inbox, answer, act and create; the counterparty keeps the room, the history and a person-free label';
end $$;

do $$ begin raise notice 'FIXTURE RLS SMOKE: ALL ASSERTIONS PASSED'; end $$;

rollback;
