import type { SupabaseClient } from "@supabase/supabase-js";
import { EMAIL_LOGO_B64, EMAIL_LOGO_CID } from "@/lib/groupmail/logo";
import { makeTransport, type SmtpAuth } from "@/lib/groupmail/send";

const NOTIFICATION_MESSAGE_ID_DOMAIN = "arabshipbroker.com";

export interface NotificationClaim {
  job_kind: "instant" | "digest";
  id: string;
  claim_token: string;
  attempts: number;
  recipient_user_id: string;
}

export interface NotificationSnapshot {
  id: string;
  recipient_user_id: string;
  importance: "urgent" | "normal" | "info";
  title: string;
  body: string;
  href: string | null;
  created_at: string;
  total_count: number;
}

export interface NotificationRecipient {
  id: string;
  email: string;
  full_name: string | null;
  is_active: boolean;
}

export interface NotificationMail {
  to: string;
  subject: string;
  html: string;
  text: string;
  messageId: string;
}

export interface NotificationDispatchResult {
  claimed: number;
  sent: number;
  retried: number;
  failed: number;
  suppressed: number;
  lost: number;
}

export interface DeliveryTransport {
  send(mail: NotificationMail): Promise<void>;
  close(): void;
}

export type SettleDelivery = (
  claim: NotificationClaim,
  outcome: "sent" | "failed" | "suppressed",
  error: string | null,
) => Promise<boolean>;

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function safeMailSubject(value: string): string {
  const normalized = value.replace(/[\u0000-\u001f\u007f]+/g, " ").replace(/\s+/g, " ").trim();
  return normalized || "Arab ShipBroker notification";
}

function safeAbsoluteHref(siteUrl: string | null, href: string | null): string | null {
  if (!siteUrl || !href || !href.startsWith("/") || href.startsWith("//") || /[\\\u0000-\u001f\u007f]/.test(href)) return null;
  try {
    const base = new URL(siteUrl);
    const target = new URL(href, base);
    return target.origin === base.origin ? target.toString() : null;
  } catch {
    return null;
  }
}

export function buildNotificationMail(
  claim: NotificationClaim,
  notification: NotificationSnapshot,
  recipient: NotificationRecipient,
  options: { siteUrl: string | null },
): NotificationMail {
  const target = safeAbsoluteHref(options.siteUrl, notification.href);
  const name = recipient.full_name?.trim() || "Member";
  const action = target
    ? `<a href="${escapeHtml(target)}" style="display:inline-block;margin-top:18px;padding:10px 16px;border-radius:6px;background:#1768a9;color:#ffffff;text-decoration:none;font-weight:600">Open in Arab ShipBroker</a>`
    : "";
  const html = `<!doctype html><html><body style="margin:0;background:#f4f7fa;font-family:Arial,sans-serif;color:#18324f"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border:1px solid #dbe4ec;border-radius:10px;overflow:hidden"><tr><td style="background:#0d2f50;padding:18px 22px"><img src="cid:${EMAIL_LOGO_CID}" width="32" height="32" alt="" style="vertical-align:middle"><span style="margin-left:10px;color:#ffffff;font-size:18px;font-weight:700;vertical-align:middle">Arab ShipBroker</span></td></tr><tr><td style="padding:24px 22px"><p style="margin:0 0 12px;color:#60758a;font-size:13px">Hello ${escapeHtml(name)},</p><h1 style="margin:0 0 12px;font-size:21px;line-height:1.3;color:#0d2f50">${escapeHtml(notification.title)}</h1><p style="margin:0;font-size:15px;line-height:1.6;color:#334e68">${escapeHtml(notification.body)}</p>${action}<p style="margin:24px 0 0;padding-top:16px;border-top:1px solid #e6edf3;color:#7a8da0;font-size:11px">This operational notification was generated by Arab ShipBroker. Manage delivery preferences in the portal.</p></td></tr></table></td></tr></table></body></html>`;
  const text = [
    `Hello ${name},`,
    "",
    notification.title,
    notification.body,
    ...(target ? ["", `Open in Arab ShipBroker: ${target}`] : []),
    "",
    "Manage delivery preferences in the Arab ShipBroker portal.",
  ].join("\n");
  return {
    to: recipient.email,
    subject: safeMailSubject(notification.title),
    html,
    text,
    messageId: `<asb-notification-${claim.id}@${NOTIFICATION_MESSAGE_ID_DOMAIN}>`,
  };
}

export function buildNotificationDigestMail(
  claim: NotificationClaim,
  notifications: NotificationSnapshot[],
  recipient: NotificationRecipient,
  options: { siteUrl: string | null },
): NotificationMail {
  if (!notifications.length) throw new Error("digest has no deliverable items");
  const total = Math.max(notifications.length, ...notifications.map((item) => Number(item.total_count) || 0));
  const omitted = Math.max(0, total - notifications.length);
  const name = recipient.full_name?.trim() || "Member";
  const itemHtml = notifications.map((notification) => {
    const target = safeAbsoluteHref(options.siteUrl, notification.href);
    const action = target
      ? `<a href="${escapeHtml(target)}" style="display:inline-block;margin-top:8px;color:#1768a9;text-decoration:none;font-size:12px;font-weight:600">Open update</a>`
      : "";
    return `<li style="margin:0;padding:14px 0;border-bottom:1px solid #e6edf3;list-style:none"><h2 style="margin:0 0 6px;font-size:16px;line-height:1.35;color:#0d2f50">${escapeHtml(notification.title)}</h2><p style="margin:0;font-size:14px;line-height:1.55;color:#334e68">${escapeHtml(notification.body)}</p>${action}</li>`;
  }).join("");
  const omittedHtml = omitted
    ? `<p style="margin:16px 0 0;color:#60758a;font-size:13px">${omitted} more ${omitted === 1 ? "update is" : "updates are"} waiting in the portal.</p>`
    : "";
  const html = `<!doctype html><html><body style="margin:0;background:#f4f7fa;font-family:Arial,sans-serif;color:#18324f"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border:1px solid #dbe4ec;border-radius:10px;overflow:hidden"><tr><td style="background:#0d2f50;padding:18px 22px"><img src="cid:${EMAIL_LOGO_CID}" width="32" height="32" alt="" style="vertical-align:middle"><span style="margin-left:10px;color:#ffffff;font-size:18px;font-weight:700;vertical-align:middle">Arab ShipBroker</span></td></tr><tr><td style="padding:24px 22px"><p style="margin:0 0 12px;color:#60758a;font-size:13px">Hello ${escapeHtml(name)},</p><h1 style="margin:0 0 8px;font-size:21px;line-height:1.3;color:#0d2f50">Your Arab ShipBroker digest</h1><p style="margin:0 0 8px;font-size:14px;line-height:1.5;color:#60758a">${total} ${total === 1 ? "update" : "updates"} since your last digest.</p><ul style="margin:0;padding:0">${itemHtml}</ul>${omittedHtml}<p style="margin:24px 0 0;padding-top:16px;border-top:1px solid #e6edf3;color:#7a8da0;font-size:11px">This operational digest was generated by Arab ShipBroker. Manage delivery preferences in the portal.</p></td></tr></table></td></tr></table></body></html>`;
  const textItems = notifications.flatMap((notification, index) => {
    const target = safeAbsoluteHref(options.siteUrl, notification.href);
    return [
      `${index + 1}. ${notification.title}`,
      notification.body,
      ...(target ? [`Open update: ${target}`] : []),
      "",
    ];
  });
  return {
    to: recipient.email,
    subject: `Arab ShipBroker digest - ${total} ${total === 1 ? "update" : "updates"}`,
    html,
    text: [
      `Hello ${name},`,
      "",
      `Your Arab ShipBroker digest contains ${total} ${total === 1 ? "update" : "updates"}.`,
      "",
      ...textItems,
      ...(omitted ? [`${omitted} more ${omitted === 1 ? "update is" : "updates are"} waiting in the portal.`, ""] : []),
      "Manage delivery preferences in the Arab ShipBroker portal.",
    ].join("\n"),
    messageId: `<asb-notification-${claim.id}@${NOTIFICATION_MESSAGE_ID_DOMAIN}>`,
  };
}

/**
 * C2O-092 P2: what may be stored about a failed attempt. SMTP servers echo addresses, hosts, credentials hints and
 * message text; none of it is kept. Only a fixed category and, when present, the three-digit SMTP reply code.
 */
export function redactDeliveryError(raw: string | null | undefined): string {
  const text = String(raw ?? "");
  // a reply code opens an SMTP response line ("550 5.1.1 …"); digits inside hosts, ports or addresses are not codes
  const code = text.match(/(?:^|\n|:\s)([245]\d{2})(?=[ -]|$)/)?.[1];
  const category =
    // the dispatcher's own reasons first; they carry no server text
    /^recipient inactive or unavailable$/.test(text) ? "recipient inactive or unavailable"
    : /^recipient email invalid$/.test(text) ? "recipient email invalid"
    : /^no deliverable notification items remain$/.test(text) ? "no deliverable notification items remain"
    : /deadline|budget|timed? ?out|timeout|ETIMEDOUT/i.test(text) ? "timeout"
    : /auth|login|credential|535|534/i.test(text) ? "authentication failed"
    : /ECONNREFUSED|ECONNRESET|ENOTFOUND|EAI_AGAIN|socket|connect|greeting|TLS|certificate/i.test(text) ? "connection failed"
    : /recipient|mailbox|user unknown|no such user|550|551|553/i.test(text) ? "recipient rejected"
    : "delivery failed";
  return code ? `${category} (SMTP ${code})` : category;
}

/** How long, after the loop, a timed-out SMTP attempt may still complete before it is recorded as failed. */
const LATE_COMPLETION_GRACE_MS = 5_000;

export async function processNotificationClaims(
  claims: NotificationClaim[],
  notifications: Map<string, NotificationSnapshot[]>,
  recipients: Map<string, NotificationRecipient>,
  transport: DeliveryTransport,
  settle: SettleDelivery,
  options: { siteUrl: string | null; maxAttempts: number; deadlineAt?: number; lateGraceMs?: number },
): Promise<NotificationDispatchResult> {
  const result: NotificationDispatchResult = {
    claimed: claims.length,
    sent: 0,
    retried: 0,
    failed: 0,
    suppressed: 0,
    lost: 0,
  };

  const late: { claim: NotificationClaim; sending: Promise<void> }[] = [];
  const settleFailed = async (claim: NotificationClaim, failure: string) => {
    try {
      if (!(await settle(claim, "failed", redactDeliveryError(failure)))) result.lost += 1;
      else if (claim.attempts >= options.maxAttempts) result.failed += 1;
      else result.retried += 1;
    } catch {
      result.lost += 1;
    }
  };

  for (const claim of claims) {
    const jobItems = notifications.get(claim.id) ?? [];
    const recipient = recipients.get(claim.recipient_user_id);
    let failure: string | null = null;
    if (!jobItems.length) {
      try {
        if (await settle(claim, "suppressed", redactDeliveryError("no deliverable notification items remain"))) result.suppressed += 1;
        else result.lost += 1;
      } catch {
        result.lost += 1;
      }
      continue;
    }
    if (!recipient?.is_active) failure = "recipient inactive or unavailable";
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient.email)) failure = "recipient email invalid";

    if (!failure && recipient) {
      try {
        const mail = claim.job_kind === "digest"
          ? buildNotificationDigestMail(claim, jobItems, recipient, options)
          : buildNotificationMail(claim, jobItems[0]!, recipient, options);
        if (options.deadlineAt == null) {
          await transport.send(mail);
        } else {
          const remaining = options.deadlineAt - Date.now();
          if (remaining <= 0) throw new Error("notification dispatch deadline reached before SMTP send");
          let timer: ReturnType<typeof setTimeout> | undefined;
          const sending = transport.send(mail);
          sending.catch(() => undefined);   // observed below; never an unhandled rejection
          const timedOut = Symbol("timeout");
          try {
            const first = await Promise.race([
              sending.then(() => null),
              new Promise<typeof timedOut>((resolve) => { timer = setTimeout(() => resolve(timedOut), remaining); }),
            ]);
            if (first === timedOut) {
              // C2O-092 P2: the server may still accept this message. Do not record a failure now (a retry would send
              // it twice); settle it after the loop by what the attempt actually did, within a short grace.
              late.push({ claim, sending });
              continue;
            }
          } finally {
            if (timer) clearTimeout(timer);
          }
        }
        if (await settle(claim, "sent", null)) result.sent += 1;
        else result.lost += 1;
        continue;
      } catch (error) {
        failure = error instanceof Error ? error.message : "email transport failed";
      }
    }

    await settleFailed(claim, failure ?? "delivery failed");
  }

  // timed-out attempts: sent if the server accepted them within the grace, otherwise a (retryable) timeout — the
  // stable Message-ID lets the receiving side drop a duplicate if a slow server accepted it after all
  for (const { claim, sending } of late) {
    const grace = options.lateGraceMs ?? LATE_COMPLETION_GRACE_MS;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const outcome = await Promise.race([
      sending.then(() => "sent" as const, () => "failed" as const),
      new Promise<"timeout">((resolve) => { timer = setTimeout(() => resolve("timeout"), grace); }),
    ]);
    if (timer) clearTimeout(timer);
    if (outcome === "sent") {
      try {
        if (await settle(claim, "sent", null)) result.sent += 1;
        else result.lost += 1;
      } catch {
        result.lost += 1;
      }
    } else {
      await settleFailed(claim, "notification SMTP attempt exceeded the invocation budget");
    }
  }

  return result;
}

function defaultTransport(auth: SmtpAuth): DeliveryTransport {
  const transport = makeTransport(auth, {
    connectionTimeout: 8_000,
    greetingTimeout: 8_000,
    socketTimeout: 15_000,
  });
  return {
    async send(mail) {
      await transport.sendMail({
        from: { name: auth.fromName, address: auth.user },
        to: mail.to,
        envelope: { from: auth.user, to: mail.to },
        subject: mail.subject,
        html: mail.html,
        text: mail.text,
        messageId: mail.messageId,
        headers: {
          "X-Auto-Response-Suppress": "All",
          "X-ArabShipBroker-Notification": "transactional",
        },
        attachments: [{
          filename: "asb-logo.png",
          content: Buffer.from(EMAIL_LOGO_B64, "base64"),
          contentType: "image/png",
          cid: EMAIL_LOGO_CID,
        }],
      });
    },
    close() {
      transport.close();
    },
  };
}

export async function dispatchNotificationDeliveries(
  client: SupabaseClient,
  options: {
    limit?: number;
    leaseSeconds?: number;
    maxAttempts?: number;
    siteUrl?: string | null;
    deadlineAt?: number;
    transportFactory?: (auth: SmtpAuth) => DeliveryTransport;
  } = {},
): Promise<NotificationDispatchResult> {
  const limit = Math.max(1, Math.min(options.limit ?? 5, 25));
  const leaseSeconds = Math.max(30, Math.min(options.leaseSeconds ?? 180, 3600));
  const maxAttempts = Math.max(1, Math.min(options.maxAttempts ?? 8, 50));

  const { data: config, error: configError } = await client
    .from("groupmail_config")
    .select("smtp_host, smtp_port, smtp_user, from_name")
    .eq("id", 1)
    .maybeSingle();
  if (configError) throw new Error("notification SMTP configuration unavailable");
  const { data: password, error: passwordError } = await client.rpc("groupmail_get_secret", { p_key: "smtp_password" });
  if (passwordError || typeof password !== "string" || !password) throw new Error("notification SMTP password unavailable");
  if (!config?.smtp_host || !config?.smtp_user) throw new Error("notification SMTP is not configured");

  const claims: NotificationClaim[] = [];
  for (let index = 0; index < limit; index += 1) {
    const { data: claimData, error: claimError } = await client.rpc("fn_notification_email_claim", {
      p_ttl_seconds: leaseSeconds,
      p_max_attempts: maxAttempts,
    });
    if (claimError) throw new Error(`notification claim failed: ${claimError.message}`);
    const claim = ((claimData ?? []) as NotificationClaim[])[0];
    if (!claim) break;
    claims.push(claim);
  }
  if (!claims.length) return { claimed: 0, sent: 0, retried: 0, failed: 0, suppressed: 0, lost: 0 };

  const snapshots = new Map<string, NotificationSnapshot[]>();
  for (const claim of claims) {
    const { data, error } = await client.rpc("fn_notification_email_snapshot", {
      p_job_kind: claim.job_kind,
      p_id: claim.id,
      p_token: claim.claim_token,
      p_item_limit: 25,
    });
    if (error) throw new Error("notification snapshots unavailable after claim");
    snapshots.set(claim.id, (data ?? []) as NotificationSnapshot[]);
  }
  const recipientIds = [...new Set(claims.map((claim) => claim.recipient_user_id))];
  const { data: recipientData, error: recipientError } = await client
    .from("users")
    .select("id, email, full_name, is_active")
    .in("id", recipientIds);
  if (recipientError) throw new Error("notification recipients unavailable after claim");

  const smtp: SmtpAuth = {
    host: String(config.smtp_host),
    port: Number(config.smtp_port) || 465,
    user: String(config.smtp_user),
    password,
    fromName: String(config.from_name || "Arab ShipBroker"),
  };
  const transport = (options.transportFactory ?? defaultTransport)(smtp);
  try {
    return await processNotificationClaims(
      claims,
      snapshots,
      new Map(((recipientData ?? []) as NotificationRecipient[]).map((recipient) => [recipient.id, recipient] as const)),
      transport,
      async (claim, outcome, error) => {
        const settled = await client.rpc("fn_notification_email_settle", {
          p_job_kind: claim.job_kind,
          p_id: claim.id,
          p_token: claim.claim_token,
          p_outcome: outcome,
          p_error: error?.slice(0, 500) ?? null,
          p_max_attempts: maxAttempts,
        });
        if (settled.error) throw new Error(settled.error.message);
        return settled.data === true;
      },
      {
        siteUrl: options.siteUrl ?? null,
        maxAttempts,
        deadlineAt: options.deadlineAt,
      },
    );
  } finally {
    transport.close();
  }
}
