import type { SupabaseClient } from "@supabase/supabase-js";
import { EMAIL_LOGO_B64, EMAIL_LOGO_CID } from "@/lib/groupmail/logo";
import { makeTransport, type SmtpAuth } from "@/lib/groupmail/send";

export interface NotificationClaim {
  id: string;
  notification_id: string;
  claim_token: string;
  attempts: number;
}

export interface NotificationSnapshot {
  id: string;
  recipient_user_id: string;
  dedupe_key: string;
  kind: string;
  importance: "urgent" | "normal" | "info";
  title: string;
  body: string;
  href: string | null;
}

export interface NotificationRecipient {
  id: string;
  email: string;
  full_name: string | null;
  is_active: boolean;
}

export interface NotificationMail {
  to: string;
  subject: string;
  html: string;
  text: string;
  messageId: string;
}

export interface NotificationDispatchResult {
  claimed: number;
  sent: number;
  retried: number;
  failed: number;
  lost: number;
}

export interface DeliveryTransport {
  send(mail: NotificationMail): Promise<void>;
  close(): void;
}

export type SettleDelivery = (
  claim: NotificationClaim,
  ok: boolean,
  error: string | null,
) => Promise<boolean>;

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function safeAbsoluteHref(siteUrl: string | null, href: string | null): string | null {
  if (!siteUrl || !href || !href.startsWith("/") || href.startsWith("//") || /[\\\u0000-\u001f\u007f]/.test(href)) return null;
  try {
    const base = new URL(siteUrl);
    const target = new URL(href, base);
    return target.origin === base.origin ? target.toString() : null;
  } catch {
    return null;
  }
}

export function buildNotificationMail(
  claim: NotificationClaim,
  notification: NotificationSnapshot,
  recipient: NotificationRecipient,
  options: { siteUrl: string | null; senderDomain: string },
): NotificationMail {
  const target = safeAbsoluteHref(options.siteUrl, notification.href);
  const name = recipient.full_name?.trim() || "Member";
  const action = target
    ? `<a href="${escapeHtml(target)}" style="display:inline-block;margin-top:18px;padding:10px 16px;border-radius:6px;background:#1768a9;color:#ffffff;text-decoration:none;font-weight:600">Open in Arab ShipBroker</a>`
    : "";
  const html = `<!doctype html><html><body style="margin:0;background:#f4f7fa;font-family:Arial,sans-serif;color:#18324f"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:28px 12px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#ffffff;border:1px solid #dbe4ec;border-radius:10px;overflow:hidden"><tr><td style="background:#0d2f50;padding:18px 22px"><img src="cid:${EMAIL_LOGO_CID}" width="32" height="32" alt="" style="vertical-align:middle"><span style="margin-left:10px;color:#ffffff;font-size:18px;font-weight:700;vertical-align:middle">Arab ShipBroker</span></td></tr><tr><td style="padding:24px 22px"><p style="margin:0 0 12px;color:#60758a;font-size:13px">Hello ${escapeHtml(name)},</p><h1 style="margin:0 0 12px;font-size:21px;line-height:1.3;color:#0d2f50">${escapeHtml(notification.title)}</h1><p style="margin:0;font-size:15px;line-height:1.6;color:#334e68">${escapeHtml(notification.body)}</p>${action}<p style="margin:24px 0 0;padding-top:16px;border-top:1px solid #e6edf3;color:#7a8da0;font-size:11px">This operational notification was generated by Arab ShipBroker. Manage delivery preferences in the portal.</p></td></tr></table></td></tr></table></body></html>`;
  const text = [
    `Hello ${name},`,
    "",
    notification.title,
    notification.body,
    ...(target ? ["", `Open in Arab ShipBroker: ${target}`] : []),
    "",
    "Manage delivery preferences in the Arab ShipBroker portal.",
  ].join("\n");
  const domain = options.senderDomain.replace(/[^a-z0-9.-]/gi, "") || "arabshipbroker.com";
  return {
    to: recipient.email,
    subject: notification.title,
    html,
    text,
    messageId: `<asb-notification-${claim.id}@${domain}>`,
  };
}

export async function processNotificationClaims(
  claims: NotificationClaim[],
  notifications: Map<string, NotificationSnapshot>,
  recipients: Map<string, NotificationRecipient>,
  transport: DeliveryTransport,
  settle: SettleDelivery,
  options: { siteUrl: string | null; senderDomain: string; maxAttempts: number; deadlineAt?: number },
): Promise<NotificationDispatchResult> {
  const result: NotificationDispatchResult = {
    claimed: claims.length,
    sent: 0,
    retried: 0,
    failed: 0,
    lost: 0,
  };

  for (const claim of claims) {
    const notification = notifications.get(claim.notification_id);
    const recipient = notification ? recipients.get(notification.recipient_user_id) : null;
    let failure: string | null = null;
    if (!notification) failure = "notification snapshot unavailable";
    else if (!recipient?.is_active) failure = "recipient inactive or unavailable";
    else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient.email)) failure = "recipient email invalid";

    if (!failure && notification && recipient) {
      try {
        const mail = buildNotificationMail(claim, notification, recipient, options);
        if (options.deadlineAt == null) {
          await transport.send(mail);
        } else {
          const remaining = options.deadlineAt - Date.now();
          if (remaining <= 0) throw new Error("notification dispatch deadline reached before SMTP send");
          let timer: ReturnType<typeof setTimeout> | undefined;
          try {
            await Promise.race([
              transport.send(mail),
              new Promise<never>((_, reject) => {
                timer = setTimeout(() => reject(new Error("notification SMTP attempt exceeded the invocation budget")), remaining);
              }),
            ]);
          } finally {
            if (timer) clearTimeout(timer);
          }
        }
        if (await settle(claim, true, null)) result.sent += 1;
        else result.lost += 1;
        continue;
      } catch (error) {
        failure = error instanceof Error ? error.message : "email transport failed";
      }
    }

    try {
      if (!(await settle(claim, false, failure))) result.lost += 1;
      else if (claim.attempts >= options.maxAttempts) result.failed += 1;
      else result.retried += 1;
    } catch {
      result.lost += 1;
    }
  }

  return result;
}

function defaultTransport(auth: SmtpAuth): DeliveryTransport {
  const transport = makeTransport(auth, {
    connectionTimeout: 8_000,
    greetingTimeout: 8_000,
    socketTimeout: 15_000,
  });
  return {
    async send(mail) {
      await transport.sendMail({
        from: { name: auth.fromName, address: auth.user },
        to: mail.to,
        envelope: { from: auth.user, to: mail.to },
        subject: mail.subject,
        html: mail.html,
        text: mail.text,
        messageId: mail.messageId,
        headers: {
          "X-Auto-Response-Suppress": "All",
          "X-ArabShipBroker-Notification": "transactional",
        },
        attachments: [{
          filename: "asb-logo.png",
          content: Buffer.from(EMAIL_LOGO_B64, "base64"),
          contentType: "image/png",
          cid: EMAIL_LOGO_CID,
        }],
      });
    },
    close() {
      transport.close();
    },
  };
}

export async function dispatchNotificationDeliveries(
  client: SupabaseClient,
  options: {
    limit?: number;
    leaseSeconds?: number;
    maxAttempts?: number;
    siteUrl?: string | null;
    deadlineAt?: number;
    transportFactory?: (auth: SmtpAuth) => DeliveryTransport;
  } = {},
): Promise<NotificationDispatchResult> {
  const limit = Math.max(1, Math.min(options.limit ?? 5, 25));
  const leaseSeconds = Math.max(30, Math.min(options.leaseSeconds ?? 180, 3600));
  const maxAttempts = Math.max(1, Math.min(options.maxAttempts ?? 8, 50));

  const { data: config, error: configError } = await client
    .from("groupmail_config")
    .select("smtp_host, smtp_port, smtp_user, from_name")
    .eq("id", 1)
    .maybeSingle();
  if (configError) throw new Error("notification SMTP configuration unavailable");
  const { data: password, error: passwordError } = await client.rpc("groupmail_get_secret", { p_key: "smtp_password" });
  if (passwordError || typeof password !== "string" || !password) throw new Error("notification SMTP password unavailable");
  if (!config?.smtp_host || !config?.smtp_user) throw new Error("notification SMTP is not configured");

  const { data: claimData, error: claimError } = await client.rpc("fn_notification_delivery_claim", {
    p_limit: limit,
    p_ttl_seconds: leaseSeconds,
    p_max_attempts: maxAttempts,
  });
  if (claimError) throw new Error(`notification claim failed: ${claimError.message}`);
  const claims = (claimData ?? []) as NotificationClaim[];
  if (!claims.length) return { claimed: 0, sent: 0, retried: 0, failed: 0, lost: 0 };

  const notificationIds = [...new Set(claims.map((claim) => claim.notification_id))];
  const { data: notificationData, error: notificationError } = await client
    .from("notifications")
    .select("id, recipient_user_id, dedupe_key, kind, importance, title, body, href")
    .in("id", notificationIds);
  if (notificationError) throw new Error("notification snapshots unavailable after claim");
  const snapshots = (notificationData ?? []) as NotificationSnapshot[];
  const recipientIds = [...new Set(snapshots.map((notification) => notification.recipient_user_id))];
  const { data: recipientData, error: recipientError } = await client
    .from("users")
    .select("id, email, full_name, is_active")
    .in("id", recipientIds);
  if (recipientError) throw new Error("notification recipients unavailable after claim");

  const smtp: SmtpAuth = {
    host: String(config.smtp_host),
    port: Number(config.smtp_port) || 465,
    user: String(config.smtp_user),
    password,
    fromName: String(config.from_name || "Arab ShipBroker"),
  };
  const transport = (options.transportFactory ?? defaultTransport)(smtp);
  try {
    return await processNotificationClaims(
      claims,
      new Map(snapshots.map((snapshot) => [snapshot.id, snapshot] as const)),
      new Map(((recipientData ?? []) as NotificationRecipient[]).map((recipient) => [recipient.id, recipient] as const)),
      transport,
      async (claim, ok, error) => {
        const settled = await client.rpc("fn_notification_delivery_settle", {
          p_id: claim.id,
          p_token: claim.claim_token,
          p_ok: ok,
          p_error: error?.slice(0, 500) ?? null,
          p_max_attempts: maxAttempts,
        });
        if (settled.error) throw new Error(settled.error.message);
        return settled.data === true;
      },
      {
        siteUrl: options.siteUrl ?? null,
        senderDomain: smtp.user.split("@")[1] ?? "arabshipbroker.com",
        maxAttempts,
        deadlineAt: options.deadlineAt,
      },
    );
  } finally {
    transport.close();
  }
}
