-- ════════════════════════════════════════════════════════════════════
-- Organizations seed — real company registry (Companies_details.xlsx) · append-only
--
-- Seeds the 80 owner/manager firms into public.organizations (org type derived
-- from OWNS/MANAGES). No desk email/phone in the source, so those stay NULL
-- (the firewall masks contact anyway — no fabricated contacts). People are NOT
-- seeded: organization_members FKs to real auth users, and we have no member
-- names yet — the UI shows generic placeholders until real users join.
-- ════════════════════════════════════════════════════════════════════

CREATE UNIQUE INDEX IF NOT EXISTS organizations_name_key ON public.organizations (name);

INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ORIENT SEAS LTD CO', 'owner', 'T2', 'Saudi Arabia', '6285232', 5, '6th Floor, Al Falih Building, 2491 Taweriq, Al-Saddad District, Jeddah, Saudi Arabia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('THALATTA SHIPPING MANAGEMENT', 'manager', 'T2', NULL, '0067951', 5, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('KAREWOOD MANAGEMENT OU', 'manager', 'T2', NULL, '6362654', 4, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SUEZ SHIP MANAGEMENT', 'manager', 'T2', 'Egypt', NULL, 4, 'Shop 1, 359, 23rd July Street, Suez 35923, Egypt', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ADRIATIC FOR MANAGEMENT', 'manager', 'T2', 'Egypt', NULL, 2, '20 Mahmoud Hamdy Street, Alexandria 21514, Egypt', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('CAPITAL SEA FLEET INC', 'owner', 'T2', NULL, '6477421', 2, NULL, 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('GENCO GEMI ISLETMECILIGI', 'manager', 'T2', NULL, '0352051', 2, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('GMZ SHIP MANAGEMENT CO HELLAS', 'manager', 'T2', 'Greece', NULL, 2, '1 Charilaou Trikoupi Street, 185 36, Piraeus, Greece', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('OCEAN SOUL SHIP MANAGEMENT', 'manager', 'T2', NULL, '0419817', 2, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('TRIMPEX UNION LTD', 'manager', 'T2', NULL, '1552211', 2, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ABK SHIPPING CO', 'owner', 'T2', 'Lebanon', '5901913', 1, 'C/O Cedar Marine Services SAL, Apartment 3/A, 3rd Floor, Sofi Plaza, Achier el-Daya Street, Tripoli, Lebanon', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('AISLING MARITIME AB LLC', 'owner', 'T2', 'Lebanon', NULL, 1, 'C/O Safe Sea Services Sarl, 3rd Floor, Dina 11 Building, Mar Doumit Street, Sahel Aalma, Jounieh, Lebanon', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('AL TAWFEEQ SHIPPING CO LTD', 'owner', 'T2', 'Lebanon', NULL, 1, 'C/O Rabunion Maritime Agency Sarl, 1st Floor, Agha Building, Charles de Gaulle Avenue, Raouche, Beirut', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ALBANYASIA MARINE SERVICES', 'owner', 'T2', 'Egypt', '6116687', 1, 'C/O Sena Ship Management SA, 4th Floor, 25 Reda Street, Ismailia, Egypt', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ALMARASI SHIPPING CO LTD', 'owner', 'T2', 'Saudi Arabia', NULL, 1, 'Issa al-Adawi, al-Baghdadiyah, Jeddah 22231, Saudi Arabia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ALODAYNI BROTHERS', 'owner', 'T2', 'Egypt', '6082809', 1, 'C/O Adriatic for Management & Services Marine Ltd, 20 Mahmoud Hamdy Street, Alexandria 21514, Egypt', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('AQUAMAR SHIP MANAGEMENT SL', 'manager', 'T2', NULL, '0437637', 1, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ARIAZ WORLD WIDE SHIPPING CORP', 'manager', 'T2', 'UAE', NULL, 1, 'Unit 801, Bays Tower, Business Bay, Bur Dubai, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ARIS SHIPPING LTD-MAI', 'owner', 'T2', NULL, '6393373', 1, NULL, 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('AWAD AEED AL-OADINI EST', 'manager', 'T2', 'Saudi Arabia', NULL, 1, 'PO Box 16818, Jeddah, Saudi Arabia', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('AYATI SHIPPING CO LLC', 'owner', 'T2', 'Belize', NULL, 1, '3301 Chetumal Street, Belize City, Belize', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('BOS SHIPPING SA-LIB', 'manager', 'T2', 'UAE', NULL, 1, 'Industrial Area 4, Sharjah, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('CAESAR MARITIME CO SA', 'manager', 'T2', 'UAE', NULL, 1, 'Room 9, 37G, Leased Offices Building, Hamriyah Free Zone, PO Box 49097, Sharjah, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('CEDAR MARINE SERVICES SAL', 'manager', 'T2', 'Lebanon', NULL, 1, 'Apartment 3/A, 3rd Floor, Sofi Plaza, Achier el-Daya Street, Tripoli, Lebanon', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('CHINA UNITED LINES LTD (CU Lines)', 'manager', 'T2', 'China', NULL, 1, 'Building 12, 706 Wuxing Lu, Pudong Xinqu, Shanghai 201204, China', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('CU LINES LTD', 'owner', 'T2', 'China', NULL, 1, 'C/O China United Lines Ltd (CU Lines), Building 12, 706 Wuxing Lu, Pudong Xinqu, Shanghai 201204', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('DENIZ ID MARITIME LTD', 'owner', 'T2', 'Turkey', NULL, 1, 'C/O Overseas Marine Ltd, Vatan Caddesi, Merkez Mah, 12/13, Mezitli, Mersin, Turkey', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('DJIBOUTI SHIPPING CO FZE', 'owner', 'T2', 'Djibouti', NULL, 1, 'LOB-027, rue de Venise, Djibouti Free Zone, Djibouti', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('DOLPHIN SEAMARINE LTD', 'owner', 'T2', 'Liberia', NULL, 1, '80 Broad Street, Monrovia, Liberia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('EAST SHIPPING LINES LTD', 'owner', 'T2', 'Jordan', '5974603', 1, 'Office 1003, King Hussein Street 264, Amman, Jordan', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('EL REEDY SHIPPING AGENCY', 'manager', 'T2', 'Egypt', NULL, 1, 'Villa No 1, Street 39, Ras El Bar, Damietta, Egypt', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ELREEDY STARS FOR OWNING', 'owner', 'T2', 'Egypt', NULL, 1, 'C/O El Reedy Shipping Agency, Villa No 1, Street 39, Ras El Bar, Damietta, Egypt', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ETHIOPIAN SHIPPING & LOGISTICS', 'owner', 'T2', 'Ethiopia', NULL, 1, 'Kirkos District, Woreda 07, Addis Ababa, Ethiopia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('EURO WEST SHIPPING LTD-MAI', 'owner', 'T2', NULL, '0059876', 1, NULL, 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('FADAK MARINE SHIPPING LLC', 'owner', 'T2', 'UAE', NULL, 1, 'al-Majaz, PO Box 38156, Sharjah, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('FAIRNESS MARITIME COMPANY SA', 'owner', 'T2', 'Panama', NULL, 1, '3rd Floor, Omega Building, Avenida Samuel Lewis, Calle 53 Este, Panama City, Panama', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('FRIENDS SHIPPING CO', 'manager', 'T2', 'UAE', NULL, 1, 'Unit 802, Makateb Building, Port Saeed, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('GHAZAL BA', 'owner', 'T2', 'UAE', NULL, 1, 'PO Box 11398, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('GUANGXI HONGXIANG SHIPPING CO', 'owner', 'T2', 'China', '4189663', 1, 'Shop 1, Building C1, Hongsheng Garden, 136 Qinzhougang Dadao, Qinnan Qu, Qinzhou, Guangxi, China', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('HARBOR SHIPHOLDING LTD', 'owner', 'T2', 'Marshall Islands', '0045421', 1, 'Trust Company Complex, Ajeltake Road, Ajeltake, Majuro MH 96960, Marshall Islands', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('HELLENIC GLAMOR SHIP MGMT LLC', 'manager', 'T2', 'UAE', NULL, 1, 'Office 504, Ahli House 1, Amman Street, Al Nahda, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('INVICTUS TRADING FZE', 'owner', 'T2', 'UAE', '6416924', 1, 'Office LB01015, Building LB01, Jebel Ali Free Zone, Jebel Ali, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('JADROPLOV INTERNATIONAL MTME', 'manager', 'T2', 'Croatia', NULL, 1, 'Obala Kneza Branimira 16, HR-21000 Split, Croatia', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('JNS PEACE SHIPPING LTD', 'owner', 'T2', 'British Virgin Islands', '0119671', 1, 'Road Town, Tortola, British Virgin Islands', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('KHARTOUM TRADING & SHIPPING CO', 'owner', 'T2', 'Sudan', NULL, 1, 'Port Sudan, Sudan', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('LABIRINTA HOLDING LTD', 'owner', 'T2', 'Seychelles', NULL, 1, 'Suite 1, 2nd Floor, Sound & Vision House, Francis Rachel Street, Victoria, Mahe Island, Seychelles', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('LADOM SHIPPING LTD', 'owner', 'T2', 'Turkey', NULL, 1, 'Sehit Hikmet Alp Caddesi 31/12, Feyzullah Mah, Maltepe 34843, Istanbul, Turkey', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('LEVANT SHIPPING LTD-MAI', 'owner', 'T2', 'Marshall Islands', NULL, 1, 'Trust Company Complex, Ajeltake Road, Ajeltake, Majuro MH 96960, Marshall Islands', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('LIANYUNGANG JIANHONG SHIPPING', 'owner', 'T2', 'China', NULL, 1, 'Room B2202, Sunshine International Center, 2 Haibin Dadao, Lianyun Qu, Lianyungang, Jiangsu, China', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('MANTA DENIZCILIK NAKLIYAT', 'manager', 'T2', 'Turkey', NULL, 1, 'Salacak Iskele Sokak, Uskudar 14, Istanbul, Turkey', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('MARSA ZENITH INC', 'owner', 'T2', 'UAE', NULL, 1, 'C/O Petra Shipping Services LLC, Office 1807, 18th Floor, Churchill Office Tower, Business Bay, Bur Dubai, PO Box 50026, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('MERRY ENTERPRISES DENIZCILIK', 'manager', 'T2', 'Turkey', NULL, 1, 'Aydinli Yolu Caddesi 10/45, Icmeler Mah, Tuzla 34957, Istanbul, Turkey', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('NAN LIAN SHIP MANAGEMENT LLC', 'manager', 'T2', 'UAE', NULL, 1, 'The Atrium Centre, 307, Khalid Bin Waleed Road (Bank Street), PO Box 82289, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('NEW SPIRIT SHIPPING LTD', 'owner', 'T2', 'Greece', NULL, 1, 'C/O GMZ Ship Management Co (Hellas) SA, 1 Charilaou Trikoupi Street, 185 36, Piraeus, Greece', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('NOATUM CSM FZCO', 'manager', 'T2', 'UAE', NULL, 1, 'Building 04, Bay Square, Al-Asayel Street, Business Bay, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('OCEAN FREIGHT ENTERPRISES SA', 'owner', 'T2', 'UAE', '6182556', 1, 'C/O Ariaz World Wide Shipping Corp, Unit 801, Bays Tower, Business Bay, Bur Dubai, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('OMRC SHIPPING INC', 'owner', 'T2', 'Turkey', NULL, 1, 'C/O Manta Denizcilik Nakliyat, Salacak Iskele Sokak, Uskudar 14, Istanbul, Turkey', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('OVERSEAS MARINE LTD', 'manager', 'T2', 'Turkey', NULL, 1, 'Vatan Caddesi, Merkez Mah, 12/13, Mezitli, Mersin, Turkey', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('PETRA SHIPPING SERVICES LLC', 'manager', 'T2', 'UAE', NULL, 1, 'Office 1807, 18th Floor, Churchill Office Tower, Business Bay, Bur Dubai, PO Box 50026, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('PRIMAVERA SHIPPING LLC', 'owner', 'T2', 'Greece', NULL, 1, 'C/O Starbulk SA, 40 Agiou Konstantinou Street, Marousi, 151 24, Athens, Greece', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('PRINCESS HIYAM SHIPPING SA', 'owner', 'T2', 'Saudi Arabia', '6082809', 1, 'C/O Awad Aeed Al-Oadini Est, PO Box 16818, Jeddah, Saudi Arabia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('PROMAR-K LTD', 'manager', 'T2', NULL, '0049251', 1, NULL, 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('RABUNION MARITIME AGENCY SARL', 'manager', 'T2', 'Lebanon', NULL, 1, '1st Floor, Agha Building, Charles de Gaulle Avenue, Raouche, Beirut, Lebanon', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('ROXETTE SHIPPING ENTERPRISES', 'owner', 'T2', 'Turkey', '5919742', 1, 'C/O Merry Enterprises Denizcilik, Aydinli Yolu Caddesi 10/45, Icmeler Mah, Tuzla, Istanbul', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('RWS SHIPPING & TRADING SA', 'owner', 'T2', 'UAE', NULL, 1, 'C/O Friends Shipping Co, Unit 802, Makateb Building, Port Saeed, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SAFE SEA SERVICES SARL', 'manager', 'T2', 'Lebanon', NULL, 1, '3rd Floor, Dina 11 Building, Mar Doumit Street, Sahel Aalma, Jounieh, Lebanon', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SAFEEN FEEDERS 1 LTD', 'owner', 'T2', 'UAE', NULL, 1, 'C/O GFS Ship Management FZE, Office FZJOB1015, Jafza One, Jebel Ali Free Zone, Jebel Ali, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SEA EXPRESS LINE LTD', 'owner', 'T2', 'UAE', NULL, 1, 'C/O Nan Lian Ship Management LLC, The Atrium Centre, 307, Khalid Bin Waleed Road, PO Box 82289, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SEA STAR MARE LTD', 'owner', 'T2', 'UAE', '5515962', 1, 'C/O Caesar Maritime Co SA, Room 9, 37G, Leased Offices Building, Hamriyah Free Zone, PO Box 49097, Sharjah, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SENA SHIP MANAGEMENT SA', 'manager', 'T2', 'Egypt', NULL, 1, '4th Floor, 25 Reda Street, Ismailia, Egypt', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SHARP LANE SHIP CORP', 'owner', 'T2', 'China', NULL, 1, 'Room 101, Unit 1, Building 21, Mingzeyuan, Zhongshan Qu, Dalian, Liaoning, China', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SIERRA GOLD LTD', 'owner', 'T2', 'Greece', NULL, 1, 'C/O GMZ Ship Management Co (Hellas) SA, 1 Charilaou Trikoupi Street, 185 36, Piraeus, Greece', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SLA MARITIME CO SA', 'owner', 'T2', 'Turkey', NULL, 1, 'Kat 3, Karli Plaza, Bogazici Caddesi 7, Cubuklu Mah, Beykoz 34805, Istanbul, Turkey', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SOUTH STAR CARGO & SHIPPING', 'owner', 'T2', 'UAE', NULL, 1, 'Office 505, 5th Floor, Al Nokhitha Building, Al Khaleej Road, Deira, PO Box 171712, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('STARBULK SA', 'manager', 'T2', 'Greece', NULL, 1, '40 Agiou Konstantinou Street, Marousi, 151 24, Athens, Greece', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('SULTAN INTERNATIONAL CO', 'owner', 'T2', 'Qatar', NULL, 1, '690 Al Canarri Street, Zone 53, Al Rayyan, Qatar', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('TOWER SHIPPING CO SA', 'manager', 'T2', 'UAE', NULL, 1, 'Flat 202, Block A, Sheikha Latifa Building, Baniyas Road, Deira, Dubai, UAE', 'Operations Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('TROGIR MARITIME INC-MAJURO', 'owner', 'T2', 'Croatia', NULL, 1, 'C/O Jadroplov International Maritime Transport Ltd, Obala Kneza Branimira 16, HR-21000 Split, Croatia', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('VALENTINA BULKERS SA', 'owner', 'T2', 'UAE', NULL, 1, 'C/O BOS Shipping SA, Industrial Area 4, Sharjah, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
INSERT INTO public.organizations (name, org_type, subscription_tier, country, imo, fleet_total, address, desk_contact_name) VALUES ('VALIANT OCEANWAY LTD', 'owner', 'T2', 'UAE', '6387613', 1, 'C/O Hellenic Glamor Ship Management LLC, Office 504, Ahli House 1, Amman Street, Al Nahda, Dubai, UAE', 'Owner''s Desk') ON CONFLICT (name) DO NOTHING;
