-- ════════════════════════════════════════════════════════════════════
-- Cargo classification — Part 1 seed (from MASTER workbook v2)  · append-only
--
-- Authoritative reference data seeded from
-- ArabShipBroker_MASTER_Cargo_Classification_Map_v2.xlsx:
--   • imsbc_codes      — 258 BCSN names + group (A/B/C/"A and B") + UN
--   • css_categories   — 12 CSS categories (+ annex + market aliases)
--   • grain_list       — Grain Code commodities
--   • commodity_map    — 85-row resolver dictionary (market_name → regime/code/
--                        group), dual-form flagged, plausible_regimes seeded
--
-- Depends on …000700 (enum, tables, commodities extension). Firewall untouched —
-- pure reference/lookup data, no counterparty contact. Idempotent (ON CONFLICT).
-- ════════════════════════════════════════════════════════════════════

-- imsbc_codes (258 BCSN)
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALFALFA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINA HYDRATE','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINA SILICA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINA, CALCINED','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM FERROSILICON POWDER UN 1395','B','1395',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM FLUORIDE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM NITRATE UN 1438','B','1438',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM REMELTING BY-PRODUCTS UN 3170','B','3170',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM SILICON POWDER, UNCOATED UN 1398','B','1398',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM SMELTING BY-PRODUCTS UN 3170','B','3170',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM SMELTING/REMELTING BY-PRODUCTS, PROCESSED','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ALUMINIUM SULPHATE GRANULAR','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM NITRATE BASED FERTILIZER','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM NITRATE BASED FERTILIZER MHB','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM NITRATE BASED FERTILIZER UN 2067','B','2067',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM NITRATE BASED FERTILIZER UN 2071','B','2071',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM NITRATE UN 1942','B','1942',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMMONIUM SULPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('AMORPHOUS SODIUM SILICATE LUMPS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ANTIMONY ORE AND RESIDUE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('APATITE CONCENTRATE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ASPHALT GRANULATES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BARIUM NITRATE UN 1446','B','1446',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BARYTE, FLOTATION CHEMICAL GRADE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BARYTES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BAUXITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BAUXITE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BIOSLUDGE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BORAX (PENTAHYDRATE CRUDE)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BORIC ACID','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BROWN COAL BRIQUETTES','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BROWN FUSED ALUMINA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('BRUCITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CALCIUM FLUORIDE, CALCIUM SULPHATE, CALCIUM CARBONATE MIXTURE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CALCIUM NITRATE FERTILIZER','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CALCIUM NITRATE UN 1454','B','1454',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CARBORUNDUM','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CELESTINE CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CEMENT','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CEMENT CLINKERS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CEMENT COPPER','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHAMOTTE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHARCOAL','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHEMICAL GYPSUM','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHLORITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHOPPED RUBBER AND PLASTIC INSULATION','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHROME PELLETS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CHROMITE ORE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CLAM SHELL','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CLAY','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CLINKER ASH','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COAL','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COAL SLURRY','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COAL TAR PITCH','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COARSE CHOPPED TYRES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COARSE IRON AND STEEL SLAG AND ITS MIXTURE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COKE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COKE BREEZE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COLEMANITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COPPER CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COPPER GRANULES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COPPER MATTE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COPPER SLAG','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('COPRA (dry) UN 1363','B','1363',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CRUSHED CARBON ANODES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CRUSHED GRANODIORITE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CRUSHED GRANODIORITE, COARSE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('CRYOLITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DIAMMONIUM PHOSPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DIRECT REDUCED IRON (C) By-product fines','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DIRECT REDUCED IRON (D) By-product fines, moisture content >= 2%','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DISTILLERS DRIED GRAINS WITH SOLUBLES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DOLOMITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DUNITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('DUNITE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ELECTRIC ARC FURNACE DUST, PELLETIZED','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FELSPAR LUMP','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERRIC SULPHATE GRANULAR','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROCHROME','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROMANGANESE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERRONICKEL','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERRONICKEL SLAG (granulated)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROPHOSPHORUS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROSILICON','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROSILICON UN 1408','B','1408',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROUS METAL BORINGS UN 2793','B','2793',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROUS METAL CUTTINGS UN 2793','B','2793',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROUS METAL SHAVINGS UN 2793','B','2793',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROUS METAL TURNINGS UN 2793','B','2793',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERROUS SULPHATE HEPTAHYDRATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FERTILIZERS WITHOUT NITRATES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FISH (IN BULK)','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FISH MEAL, STABILIZED','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FISH SCRAP, STABILIZED','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FLUE DUST, CONTAINING LEAD AND ZINC','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FLUORSPAR','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FLY ASH, DRY','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FLY ASH, WET','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('FOAM GLASS GRAVEL','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GLASS CULLET','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GRAIN SCREENING PELLETS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GRANULAR FERROUS SULPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GRANULATED NICKEL MATTE','B',NULL,'(less than 2% moisture content)') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GRANULATED SLAG','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GRANULATED TYRE RUBBER','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GROUND GRANULATED BLAST FURNACE SLAG POWDER','A',NULL,'Ground nuts, meal BorCc see SEED CAKE or SEED CAKES AND OTHER RESIDUES OF PROCESSED OILY VEGETABLES') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GYPSUM','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('GYPSUM GRANULATED','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ILMENITE (ROCK)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ILMENITE (UPGRADED)','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ILMENITE CLAY','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ILMENITE SAND','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON AND STEEL SLAG AND ITS MIXTURE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON CONCENTRATE (pellet feed)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON CONCENTRATE (sinter feed)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON ORE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON ORE BRIQUETTES','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON ORE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON ORE PELLETS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON OXIDE TECHNICAL','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON OXIDE, SPENT UN 1376','B','1376',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON SINTER','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON SMELTING BY-PRODUCTS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('IRON SPONGE, SPENT UN 1376','B','1376',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LABRADORITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEACH RESIDUE CONTAINING LEAD','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD AND ZINC CALCINES (mixed)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD AND ZINC MIDDLINGS','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD NITRATE UN 1469','B','1469',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD ORE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD ORE RESIDUE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LEAD SILVER CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LIME (UNSLAKED)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LIMESTONE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LINTED COTTON SEED','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('LOGS','B',NULL,'see Wood Products — General schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('M.A.P.','C',NULL,'see MONOAMMONIUM PHOSPHATE') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MAGNESIA (DEADBURNED)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MAGNESIA (UNSLAKED)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MAGNESITE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MAGNESIUM NITRATE UN 1474','B','1474',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MAGNESIUM SULPHATE FERTILIZERS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MANGANESE COMPONENT FERROALLOY SLAG','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MANGANESE CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MANGANESE ORE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MANGANESE ORE FINES','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MARBLE CHIPS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MATTE CONTAINING COPPER AND LEAD','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('METAL SULPHIDE CONCENTRATES','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('METAL SULPHIDE CONCENTRATES, CORROSIVE UN 1759','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('METAL SULPHIDE CONCENTRATES, SELF-HEATING UN 3190','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MONOAMMONIUM PHOSPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MONOAMMONIUM PHOSPHATE (M.A.P.), MINERAL ENRICHED COATING','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('MONOCALCIUMPHOSPHATE (MCP)','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('NEPHELINE SYENITE (mineral)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('NICKEL CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('NICKEL ORE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('OLIVINE GRANULAR AND GRAVEL AGGREGATE PRODUCTS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('OLIVINE SAND','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PEA PROTEIN CONCENTRATE PELLETS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PEANUTS (in shell)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PEAT MOSS','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PEBBLES (sea)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PELLETS (concentrates)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PENTAHYDRATE CRUDE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PERLITE ROCK','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PETROLEUM COKE (calcined)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PETROLEUM COKE (uncalcined)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PHOSPHATE (defluorinated)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PHOSPHATE ROCK (calcined)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PHOSPHATE ROCK (uncalcined)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PHOSPHATE ROCK FINES (uncalcined)','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PIG IRON','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PITCH PRILL','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('POTASH','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('POTASSIUM CHLORIDE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('POTASSIUM NITRATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('POTASSIUM NITRATE UN 1486','B','1486',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('POTASSIUM SULPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PULP WOOD','B',NULL,'see Wood Products — General schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PUMICE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYRITE (containing copper and iron)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYRITES','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYRITES, CALCINED','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYRITIC ASHES (iron)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYRITIC CINDERS','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('PYROPHYLLITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('QUARTZ','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('QUARTZITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('RADIOACTIVE MATERIAL, LOW SPECIFIC ACTIVITY (LSA-I) UN 2912','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('RADIOACTIVE MATERIAL, SURFACE CONTAMINATED','B',NULL,'OBJECTS (SCO-l) UN 2913') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('RASORITE (ANHYDROUS)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ROUNDWOOD','B',NULL,'see Wood Products — General schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('RUTILE SAND','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SALT','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SALT CAKE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SALT ROCK','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SAND','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SAND, HEAVY MINERAL','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SAND, MINERAL CONCENTRATE, RADIOACTIVE MATERIAL, LOW SPECIFIC ACTIVITY (LSA-I) UN 2912','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SAW LOGS','B',NULL,'see Wood Products — General schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SAWDUST','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SCALE GENERATED FROM THE IRON AND STEEL MAKING PROCESS','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SCRAP METAL','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SEED CAKE UN 2217','B','2217',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SEED CAKES AND OTHER RESIDUES OF PROCESSED OILY VEGETABLES','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SILICOMANGANESE (carbo-thermic)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SILICOMANGANESE (low carbon)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SILICON SLAG','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SILVER LEAD CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SLIG (iron ore)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SODA ASH','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SODIUM NITRATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SODIUM NITRATE AND POTASSIUM NITRATE MIXTURE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SODIUM NITRATE AND POTASSIUM NITRATE MIXTURE UN 1499','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SODIUM NITRATE UN 1498','B','1498',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SOLIDIFIED FUELS RECYCLED FROM PAPER AND PLASTICS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SPODUMENE (UPGRADED)','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('STAINLESS STEEL GRINDING DUST','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('STONE CHIPPINGS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SUGAR','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SUGARCANE BIOMASS PELLETS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SULPHATE OF POTASH AND MAGNESIUM','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SULPHUR (formed, solid)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SULPHUR UN 1350 (crushed lump and coarse grained)','B','1350',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SUPERPHOSPHATE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SUPERPHOSPHATE (triple, granular)','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SYNTHETIC CALCIUM FLUORIDE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('SYNTHETIC SILICON DIOXIDE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TACONITE PELLETS','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TALC','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TANKAGE','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TAPIOCA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TIMBER','B',NULL,'see Wood Products — General schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TITANOMAGNETITE SAND','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('TUFF, COARSE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('UREA','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('VANADIUM ORE','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('VERMICULITE','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('WHITE QUARTZ','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('WOOD PELLETS CONTAINING ADDITIVES AND/OR BINDERS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('WOOD PELLETS NOT CONTAINING ANY ADDITIVES AND/OR BINDERS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('WOOD TORREFIED','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('WOODCHIPS','B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC AND LEAD CALCINES (mixed)','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC AND LEAD MIDDLINGS','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC ASHES UN 1435','B','1435',NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC CONCENTRATE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC OXIDE ENRICHED FLUE DUST','A and B',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC SINTER','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC SLAG','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC SLAG (coarse)','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZINC SLUDGE','A',NULL,'see Mineral concentrates schedule') ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZIRCON KYANITE CONCENTRATE','A',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;
INSERT INTO public.imsbc_codes (bcsn,imsbc_group,un_number,notes) VALUES ('ZIRCONSAND','C',NULL,NULL) ON CONFLICT (bcsn) DO NOTHING;

ALTER TABLE public.css_categories ADD COLUMN IF NOT EXISTS css_annex text, ADD COLUMN IF NOT EXISTS market_aliases text;
-- css_categories (12)
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-01','Containers on non-cellular ships','Annex 1','Containers carried on deck/hatches of ships not specially designed/fitted for containers.','Stow fore-and-aft; lashings (wire/chain); timber shoring <=2m; secure to prevent sliding/tipping.','(deck containers — rare in sub-35k niche)',1) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-02','Portable tanks (tank-containers)','Annex 2','Tank not permanently secured, >450 L, external stabilizing members; ISO or non-ISO frame.','Lashing angle <=25 deg sliding, 45-60 deg tipping; CSC compliance; IMDG if DG.','(tank-containers)',2) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-03','Portable receptacles','Annex 3','Receptacle (not a portable tank), capacity <= 1,000 L; cylinders, frames of cylinders.','Dunnage off steel deck; stow upright for liquefied gas; box/crib, brace, chock.','(gas cylinders, receptacles)',3) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-04','Wheel-based (rolling) cargoes','Annex 4','Cargoes on wheels/tracks: buses, tractors, earth-movers, roll-trailers (excl. road trailers/trains).','Marked securing points; brakes set; chocks; lashings >= steel chain/wire; stow fore-and-aft.','Shredded Tyres',4) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-05','Heavy cargo items','Annex 5','Heavy items such as locomotives, transformers, etc.','CoG + bedding info; timber spread load; lashing 25 deg slide / 45-60 deg tip; shoring if large angles.','Project Cargo, Marble Blocks, Granite Blocks',5) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-06','Coiled sheet steel','Annex 6','Coiled sheet steel stowed on the round (typically >10 t per coil).','Bottom stow, axes fore-and-aft, dunnage athwartships, locking coils, wedges, top-tier lashing.','Steel Coils, Hot Rolled Coils',6) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-07','Heavy metal products','Annex 7','Any heavy metal item: bars, pipes, rods, plates, billets, wire coils, etc.','Compact side-to-side, no voids; do not exceed deck/tank-top load; shore every frame >=1m; top-layer lashing.','Steel Rebars, Steel Bars, Steel Billets, Wire Rod in Coils, Steel Plates, Steel Sheets, Steel Slabs, Steel Products, Steel Debars, DBIC',7) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-08','Anchor chains','Annex 8','Anchor chains in bundles or continuous lengths.','Never on bare metal — wooden ceiling/dunnage; tight stow; top layer lashed both sides.','(anchor chains)',8) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-09','Metal scrap in bulk','Annex 9','Metal scrap difficult to stow compactly (excl. borings/shavings/turnings — those are IMSBC).','Protect side plating/pipes; heavy first; no voids; lash/overstow heavy pieces; watch tank-top load.','(scrap metal)',9) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-10','Flexible intermediate bulk containers (FIBC)','Annex 10','Flexible portable packaging for solids, capacity <= 3 m3 (3,000 L); one-way or multi-trip.','Wide hatches; stow tight from sides to centre; chock voids in centre; gratings/plywood + wire lashings.','Bagged Cargo (big bags)',10) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-11','Logs (under-deck stow)','Annex 11','Under-deck stowage of logs; bilge/stability/ballast precautions.','Pre-stow plan; heaviest first; compact fore-and-aft, fill athwartship voids; bilge & stability checks.','Logs',11) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;
INSERT INTO public.css_categories (code,name,css_annex,definition,securing_trigger,market_aliases,sort_order) VALUES ('CSS-12','Unit loads','Annex 12','Packages on a pallet/load board, in a pallet box, or permanently secured in a sling.','Clean flush deck; block stow no voids; gratings/plywood + wire lashings; check pallet strength if tiered.','Bagged Cargo, Sugar (bags), MDF Boards, Chipboards, General Cargo, Mixed BB',12) ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, css_annex=EXCLUDED.css_annex, definition=EXCLUDED.definition, securing_trigger=EXCLUDED.securing_trigger, market_aliases=EXCLUDED.market_aliases;

-- grain_list (authoritative from workbook)
INSERT INTO public.grain_list (market_name,notes) VALUES ('Wheat','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Maize/Corn','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Oats','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Rye','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Barley','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Rice','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Sorghum','Cereal') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Pulses','Pulse') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Soybeans (whole)','Oilseed') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Sunflower Seeds (whole)','Oilseed') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Rapeseed (whole)','Oilseed') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('Linseed (whole)','Oilseed') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.grain_list (market_name,notes) VALUES ('NOTE:','Meals/cakes/pellets/bran = IMSBC SEED CAKE (B), not grain. Bagged grain = CSS.') ON CONFLICT (market_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.commodity_map (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  market_name text NOT NULL UNIQUE,
  regime public.cargo_regime_enum NOT NULL,
  code text,
  group_cat text,
  is_dual_form boolean NOT NULL DEFAULT false,
  plausible_regimes public.cargo_regime_enum[] NOT NULL DEFAULT '{}',
  note text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.commodity_map ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "commodity_map read" ON public.commodity_map;
CREATE POLICY "commodity_map read" ON public.commodity_map FOR SELECT TO anon, authenticated USING (true);
GRANT SELECT ON public.commodity_map TO anon, authenticated;
-- commodity_map (resolver dictionary)
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Agri Products','GRAIN'::public.cargo_regime_enum,'DEFAULT→GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'DEFAULT: agricultural → grain regime unless processed (then IMSBC seed cake)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Agri Straw','IMSBC'::public.cargo_regime_enum,'VEGETABLE PRODUCTS','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Fibrous vegetable product') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Alfalfa Pellets','IMSBC'::public.cargo_regime_enum,'ALFALFA','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'IMSBC ALFALFA') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Bagged Cargo','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Barley','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Bauxite','IMSBC'::public.cargo_regime_enum,'BAUXITE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Bentonite','IMSBC'::public.cargo_regime_enum,'BENTONITE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Big Bags','CSS'::public.cargo_regime_enum,'CSS-10',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Calcined Coke','IMSBC'::public.cargo_regime_enum,'PETROLEUM COKE (CALCINED)','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Calcined petroleum coke') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Cement','IMSBC'::public.cargo_regime_enum,'CEMENT','C',true,ARRAY['IMSBC'::public.cargo_regime_enum,'CSS'::public.cargo_regime_enum],'Loose/bulk cement (rare). Bagged cement → CSS.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Cement Bb','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum],'Bagged cement → CSS unit-load') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Cement Bb + Steel','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Cement Copper','IMSBC'::public.cargo_regime_enum,'CEMENT COPPER','A',false,ARRAY['IMSBC'::public.cargo_regime_enum],'COPPER CONCENTRATE — liquefies (Group A). NOT construction cement. Separate entry.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('China Clay','IMSBC'::public.cargo_regime_enum,'CLAY','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Clinker','IMSBC'::public.cargo_regime_enum,'CEMENT CLINKERS','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Coal','IMSBC'::public.cargo_regime_enum,'COAL','A and B',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Copper Concentrates','IMSBC'::public.cargo_regime_enum,'COPPER CONCENTRATE','A',false,ARRAY['IMSBC'::public.cargo_regime_enum],'LIQUEFIES — Group A') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Corn','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Corn + Soybean Meal','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Corn + Wheat','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Corn Germ + Sunflower Seeds','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Dap','IMSBC'::public.cargo_regime_enum,'AMMONIUM PHOSPHATE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Diammonium phosphate') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Ddgs','IMSBC'::public.cargo_regime_enum,'DISTILLERS DRIED GRAINS WITH SOLUBLES','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Distillers grains — IMSBC entry') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Dolomite','IMSBC'::public.cargo_regime_enum,'DOLOMITE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Fertilisers','IMSBC'::public.cargo_regime_enum,'DEFAULT→see note','C (default)',false,ARRAY['IMSBC'::public.cargo_regime_enum],'DEFAULT: routes to IMSBC Group C unless broker specifies a hazardous fertiliser (then re-resolve)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Fertilisers Npk','IMSBC'::public.cargo_regime_enum,'NPK FERTILIZER','verify (some B)',false,ARRAY['IMSBC'::public.cargo_regime_enum],'NPK — some grades Group B; verify per grade') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Gbfs','CSS'::public.cargo_regime_enum,'CSS-10',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Granulated blast furnace slag → CSS-10 (per ruling)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Grain','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Grit','IMSBC'::public.cargo_regime_enum,'STONE CHIPPINGS','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Assumed stone chippings — verify') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Hbi','IMSBC'::public.cargo_regime_enum,'DIRECT REDUCED IRON (B)','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Hot briquetted iron — DRI family') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Iron Ore','IMSBC'::public.cargo_regime_enum,'IRON ORE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Iron Oxide','IMSBC'::public.cargo_regime_enum,'IRON OXIDE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Limestone','IMSBC'::public.cargo_regime_enum,'LIMESTONE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Linseed','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Linseeds','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Logs','CSS'::public.cargo_regime_enum,'CSS-11',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Maize','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Map','IMSBC'::public.cargo_regime_enum,'AMMONIUM PHOSPHATE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Monoammonium phosphate') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Marble Blocks','CSS'::public.cargo_regime_enum,'CSS-05',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Metcoke','IMSBC'::public.cargo_regime_enum,'COKE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Metallurgical coke') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Minerals','IMSBC'::public.cargo_regime_enum,'MINERAL CONCENTRATES','C (default)',false,ARRAY['IMSBC'::public.cargo_regime_enum],'DEFAULT: generic minerals → IMSBC C; if a concentrate, may be Group A — verify') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Oats','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Olive Cake','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Olive Pits','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Olive Pomace','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Olive Pulp','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Peas','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Perlite','IMSBC'::public.cargo_regime_enum,'PERLITE ROCK','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Petcoke','IMSBC'::public.cargo_regime_enum,'PETROLEUM COKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Uncalcined petroleum coke') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Pig Iron','IMSBC'::public.cargo_regime_enum,'PIG IRON','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Potash','IMSBC'::public.cargo_regime_enum,'POTASH','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Rapeseed Meal','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Rice','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Rock Phosphate','IMSBC'::public.cargo_regime_enum,'PHOSPHATE ROCK','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Rye','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Salt','IMSBC'::public.cargo_regime_enum,'SALT','C',true,ARRAY['IMSBC'::public.cargo_regime_enum,'CSS'::public.cargo_regime_enum],'Bagged salt → CSS') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Salt + Rice','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Scrap','CSS'::public.cargo_regime_enum,'CSS-09',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Metal scrap in bulk → CSS-09 (per ruling). Borings/shavings/turnings are IMSBC.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Silica Sand','IMSBC'::public.cargo_regime_enum,'SAND','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],NULL) ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Slag','CSS'::public.cargo_regime_enum,'CSS-10',NULL,true,ARRAY['CSS'::public.cargo_regime_enum],'→ CSS-10 FIBC/big bags (per ruling)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Softwood Pulp','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sorghum','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Soybean Meal','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Soybeans','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Bars','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Billets','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Coils','CSS'::public.cargo_regime_enum,'CSS-06',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Products','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Rebars','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Wire Rod + Debars','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sugar','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum],'Bagged sugar → CSS unit-load') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sugar + Rice','UNMAPPED'::public.cargo_regime_enum,NULL,NULL,false,ARRAY['UNMAPPED'::public.cargo_regime_enum],'Each parcel = separate cargo line, self-classified') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sulphate','IMSBC'::public.cargo_regime_enum,'AMMONIUM SULPHATE','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Assumed ammonium sulphate — verify if other') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sunflower Bagasse Pellets','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sunflower Meal','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sunflower Meal Pellets','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sunflower Seeds','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Urea','IMSBC'::public.cargo_regime_enum,'UREA','C',true,ARRAY['IMSBC'::public.cargo_regime_enum,'CSS'::public.cargo_regime_enum],'Bagged/big-bag urea → CSS') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Wheat','GRAIN'::public.cargo_regime_enum,'GRAIN',NULL,false,ARRAY['GRAIN'::public.cargo_regime_enum],'Grain Code; grain stability booklet + Doc of Authorization (hard block if absent)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Wheat Bran','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Wheat Bran Pellets','IMSBC'::public.cargo_regime_enum,'SEED CAKE','B',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Processed/oil-extracted → IMSBC SEED CAKE Group B (self-heating)') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Wheat Flour','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('White Cement','IMSBC'::public.cargo_regime_enum,'CEMENT','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Treated as cement') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('White Clinker','IMSBC'::public.cargo_regime_enum,'CEMENT CLINKERS','C',false,ARRAY['IMSBC'::public.cargo_regime_enum],'Treated as cement clinkers') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Wire Rod In Coils','CSS'::public.cargo_regime_enum,'CSS-06',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Break-bulk') ON CONFLICT (market_name) DO NOTHING;
