#!/usr/bin/env python3
"""Generate supabase/seed/unified_dataset.sql from the unified master workbook
(ArabShipBroker UNIFIED Cargo-Vessel Map). Idempotent upserts:

  ports (upsert by locode) -> vessels (upsert by imo; name-guard for blank-imo)
  -> vessel_availability (OPEN vessels) -> cargo_listings (upsert by ref).

Run:  python3 scripts/gen_unified_seed.py <workbook.xlsx>
Apply ORDER: migration …000960 (zone enum ECSA/WCI) first, then this seed.
"""
import sys, datetime
import openpyxl

SRC = sys.argv[1]
OUT = "supabase/seed/unified_dataset.sql"

VTYPE = {"Cargo Ship": "General Cargo", "Bulk Carrier": "Bulk Carrier"}
PORT_TYPES = {"Sea Port", "River Port", "Sea/River"}
ZONES = {"B.SEA","E.MED","W.MED","C.MED","ADRIATIC","R.SEA","AG","A.SEA","WCAF",
         "ECAF","NCONT","CARIB","F.EAST","ECI","ECSA","WCI","Unknown"}
LOAD_TERMS = {"FIO","FIOT","FIOST","FIOS","FIOS LSD","Liner Terms"}
ZONE_LONG = {
    "arabian gulf":"AG","gulf":"AG","arabian sea":"A.SEA","red sea":"R.SEA",
    "red sea north":"R.SEA","red sea south":"R.SEA","east med":"E.MED",
    "eastern med":"E.MED","e.med":"E.MED","med":"E.MED","west med":"W.MED",
    "western med":"W.MED","central med":"C.MED","black sea":"B.SEA",
    "adriatic":"ADRIATIC","continent":"NCONT","n.continent":"NCONT",
    "north continent":"NCONT","far east":"F.EAST","caribbean":"CARIB",
    "west africa":"WCAF","east africa":"ECAF","west coast india":"WCI",
    "east coast india":"ECI","india":"WCI",
}

def q(v):
    """SQL string literal or NULL."""
    if v is None: return "NULL"
    s = str(v).strip()
    if s == "" or s == "-": return "NULL"
    return "'" + s.replace("'", "''") + "'"

def num(v):
    if v is None: return None
    s = str(v).strip().replace(",", "")
    if s in ("", "-"): return None
    try:
        f = float(s)
        return int(f) if f.is_integer() else f
    except ValueError:
        return None

def sint(v):
    n = num(v)
    return None if n is None else int(round(n))

def sql_num(v):
    n = num(v)
    return "NULL" if n is None else str(n)

def date_lit(v):
    """Return ('DATE', is_spot). datetime -> 'YYYY-MM-DD'; 'SPOT' -> spot."""
    if v is None: return (None, False)
    if isinstance(v, (datetime.datetime, datetime.date)):
        return ("'%04d-%02d-%02d'" % (v.year, v.month, v.day), False)
    s = str(v).strip()
    if not s: return (None, False)
    if "spot" in s.lower(): return (None, True)
    # Try ISO yyyy-mm-dd
    try:
        d = datetime.date.fromisoformat(s[:10])
        return ("'%04d-%02d-%02d'" % (d.year, d.month, d.day), False)
    except ValueError:
        return (None, False)  # free text like "Mid April" -> no date

def zone(code):
    if code is None: return None
    c = str(code).strip().upper()
    return c if c in ZONES else None

def parse_zone_list(*sources):
    out = []
    for s in sources:
        if not s: continue
        for tok in str(s).replace("|", "/").split("/"):
            t = tok.strip()
            if not t: continue
            z = zone(t) or ZONE_LONG.get(t.lower())
            if z and z != "Unknown" and z not in out:
                out.append(z)
    return out

def boolish(v):
    if v is None: return None
    s = str(v).strip().lower()
    if s in ("y","yes","true","1","geared"): return True
    if s in ("n","no","false","0","gearless"): return False
    return None

wb = openpyxl.load_workbook(SRC, data_only=True)
def sheet(name):
    ws = wb[name]
    rows = list(ws.iter_rows(values_only=True))
    head = [("" if c is None else str(c).strip()) for c in rows[0]]
    idx = {}
    for i, h in enumerate(head):
        idx.setdefault(h, i)  # first occurrence wins (dup headers)
    recs = []
    for r in rows[1:]:
        if not any(c is not None and str(c).strip() for c in r): continue
        recs.append(lambda name, _r=r, _i=idx: (_r[_i[name]] if name in _i and _i[name] < len(_r) else None))
    return recs

out = []
W = out.append
W("-- ════════════════════════════════════════════════════════════════════")
W("-- Unified master dataset seed — GENERATED by scripts/gen_unified_seed.py")
W("-- Source: ArabShipBroker UNIFIED Cargo-Vessel Map. Idempotent (upserts).")
W("-- APPLY ORDER: run migration 20260601000960_zone_enum_additions.sql FIRST")
W("-- (adds zone_enum 'ECSA','WCI'), then run this seed.")
W("-- ════════════════════════════════════════════════════════════════════")
W("BEGIN;")
W("ALTER TABLE public.vessel_availability DISABLE TRIGGER USER;")
W("ALTER TABLE public.cargo_listings    DISABLE TRIGGER USER;")
W("")

# ── PORTS ───────────────────────────────────────────────────────────────
port_locodes = set()
W("-- ── PORTS (upsert by locode) ──────────────────────────────────────")
for g in sheet("04_PORTS"):
    loc = (g("LOCODE") or "").strip().upper().replace(" ", "")
    if not loc: continue
    z = zone(g("ZONE")) or "Unknown"
    pt = (g("PORT_TYPE") or "Sea Port").strip()
    if pt not in PORT_TYPES: pt = "Sea Port"
    port_locodes.add(loc)
    W("INSERT INTO public.ports (locode, trade_name, country, zone, port_type) VALUES "
      f"({q(loc)}, {q(g('TRADE_NAME') or loc)}, {q(g('COUNTRY') or 'Unknown')}, '{z}', '{pt}') "
      "ON CONFLICT (locode) DO UPDATE SET trade_name=EXCLUDED.trade_name, "
      "country=EXCLUDED.country, zone=EXCLUDED.zone, port_type=EXCLUDED.port_type;")

def loc_or_null(v):
    if not v: return None
    c = str(v).strip().upper().replace(" ", "")
    return c if c in port_locodes else None

# ── VESSELS ─────────────────────────────────────────────────────────────
open_vessels = []
W("\n-- ── VESSELS (88 register rows; upsert by IMO, name-guard for blank IMO) ──")
for g in sheet("02_VESSELS"):
    name = (g("VESSEL_NAME") or "").strip()
    if not name: continue
    imo = (str(g("IMO")).strip() if g("IMO") else "")
    vtype = VTYPE.get((g("VESSEL_TYPE") or "").strip(), "General Cargo")
    dwt = sint(g("DWT")); grt = sint(g("GRT"))
    if grt is not None and not (200 <= grt <= 80000): grt = None
    cols = {
        "vessel_name": q(name),
        "imo_number": q(imo) if imo else "NULL",
        "vessel_type": f"'{vtype}'",
        "dwt_grain": "NULL" if dwt is None else str(dwt),
        "dwt_bale": sql_num(g("DWT_BALE")),
        "gross_tonnage": "NULL" if grt is None else str(grt),
        "grain_cbm": sql_num(g("GRAIN_CBM")),
        "build_year": sql_num(g("BUILT")),
        "flag": q(g("FLAG")),
        "max_loa_m": sql_num(g("LOA_M")),
        "max_draft_m": sql_num(g("DRAFT_M")),
        "is_geared": {True:"TRUE",False:"FALSE",None:"NULL"}[boolish(g("IS_GEARED"))],
        "crane_count": sql_num(g("CRANE_COUNT")),
        "crane_swl_mt": sql_num(g("CRANE_SWL_MT")),
        "owner_company": q(g("REG_OWNER_COMPANY")),
        "manager_company": q(g("SHIP_COMM_MANAGER") or g("ISM_MANAGER")),
        "pi_club": "NULL",
        "risk_notes": q(g("RISK_NOTES")),
        "scope": "'In Scope'", "risk_level": "'CLEAR'", "is_sanctioned": "FALSE",
    }
    zl = parse_zone_list(g("OPEN_ZONE"), g("TRADING_ZONE"))
    cols["preferred_zones"] = ("ARRAY[" + ",".join(f"'{z}'" for z in zl) + "]::public.zone_enum[]") if zl else "NULL"
    keys = ",".join(cols.keys()); vals = ",".join(cols.values())
    if imo:
        upd = ",".join(f"{k}=EXCLUDED.{k}" for k in cols if k not in ("imo_number",))
        W(f"INSERT INTO public.vessels ({keys}) VALUES ({vals}) "
          f"ON CONFLICT (imo_number) DO UPDATE SET {upd};")
    else:
        # blank IMO: insert once (guard by name to stay idempotent)
        W(f"INSERT INTO public.vessels ({keys}) SELECT {vals} "
          f"WHERE NOT EXISTS (SELECT 1 FROM public.vessels WHERE vessel_name={q(name)} AND imo_number IS NULL);")
    # open position?
    if (g("STATUS") or "").strip().upper() == "OPEN":
        d, _ = date_lit(g("OPEN_FROM"))
        open_vessels.append({
            "imo": imo, "name": name,
            "loc": loc_or_null(g("OPEN_LOCODE")),
            "oz": zone(g("OPEN_ZONE")),
            "oport": (g("OPEN_PORT") or "").strip() or None,
            "date": d,
            "vss": sql_num(g("ME_CONS_SEA_MT")), "vsp": sql_num(g("ME_CONS_PORT_MT")),
            "lsp": sql_num(g("AUX_CONS_PORT_MT")), "spd": sql_num(g("SERVICE_SPEED_KN")),
        })

# ── VESSEL_AVAILABILITY (OPEN positions; market-visible) ────────────────
W("\n-- ── VESSEL_AVAILABILITY (OPEN positions, review_status APPROVED) ──")
for v in open_vessels:
    vsel = (f"(SELECT id FROM public.vessels WHERE imo_number={q(v['imo'])} LIMIT 1)"
            if v["imo"] else
            f"(SELECT id FROM public.vessels WHERE vessel_name={q(v['name'])} AND imo_number IS NULL LIMIT 1)")
    oz = f"'{v['oz']}'" if v["oz"] else "NULL"
    W("INSERT INTO public.vessel_availability "
      "(vessel_id, open_port_locode, open_port_name, open_zone, open_date, status, review_status, goes_live_at, "
      "vlsfo_sea_mt_day, vlsfo_port_mt_day, lsmgo_port_mt_day, service_speed_kn) "
      f"SELECT {vsel}, {q(v['loc'])}, {q(v['oport'])}, {oz}, {v['date'] or 'NULL'}, 'OPEN', 'APPROVED', NOW(), "
      f"{v['vss']}, {v['vsp']}, {v['lsp']}, {v['spd']} "
      f"WHERE {vsel} IS NOT NULL "
      f"AND NOT EXISTS (SELECT 1 FROM public.vessel_availability va WHERE va.vessel_id={vsel} AND va.status='OPEN');")

# ── CARGO_LISTINGS ──────────────────────────────────────────────────────
W("\n-- ── CARGO_LISTINGS (731 listings; upsert by ref, review_status APPROVED) ──")
skipped = 0
for g in sheet("01_CARGO"):
    ref = (g("REF") or "").strip()
    if not ref: skipped += 1; continue
    qmin = sint(g("QTY_MIN_MT")); qmax = sint(g("QTY_MAX_MT"))
    if qmin is None and qmax is None: skipped += 1; continue
    qmin = qmin if qmin is not None else qmax
    qmax = qmax if qmax is not None else qmin
    ctype = (g("CARGO_TYPE") or "Dry Bulk").strip()
    if ctype not in ("Dry Bulk", "Break Bulk"): ctype = "Dry Bulk"
    regime = (g("ASB_REGIME") or "").strip().upper()
    st = (g("STATUS") or "IN").strip().upper()
    st = {"IN":"IN","PARTIAL":"PARTIAL","OUT":"OUT","MONITOR":"IN","CLOSED":"CLOSED"}.get(st, "IN")
    lf, lf_spot = date_lit(g("LAYCAN_FROM"))
    lt, _ = date_lit(g("LAYCAN_TO"))
    is_spot = "TRUE" if lf_spot else "FALSE"
    lterm = (g("LOAD_TERMS") or "").strip()
    lterm_lit = f"'{lterm}'" if lterm in LOAD_TERMS else "NULL"
    cols = {
        "ref": q(ref), "status": f"'{st}'", "cargo_type": f"'{ctype}'",
        "commodity_name": q(g("COMMODITY") or "Cargo"),
        "is_grain_cargo": "TRUE" if regime == "GRAIN" else "FALSE",
        "is_dg_cargo": "FALSE",
        "qty_min_mt": str(qmin), "qty_max_mt": str(qmax),
        "load_port_locode": q(loc_or_null(g("LOAD_LOCODE"))),
        "load_port_name": q(g("LOAD_PORT")), "load_zone": (f"'{zone(g('LOAD_ZONE'))}'" if zone(g("LOAD_ZONE")) else "NULL"),
        "load_country": q(g("LOAD_COUNTRY")),
        "disch_port_locode": q(loc_or_null(g("DISCH_LOCODE"))),
        "disch_port_name": q(g("DISCH_PORT")), "disch_zone": (f"'{zone(g('DISCH_ZONE'))}'" if zone(g("DISCH_ZONE")) else "NULL"),
        "disch_country": q(g("DISCH_COUNTRY")),
        "laycan_from": lf or "NULL", "laycan_to": lt or "NULL", "is_spot": is_spot,
        "load_rate": q(g("LOAD_RATE")), "disch_rate": q(g("DISCH_RATE")),
        "load_terms": lterm_lit, "nor_clause": q(g("NOR_CLAUSE")),
        "commission_pct": sql_num(g("COMMISSION_PCT")),
        "demurrage_rate": sql_num(g("DEMURRAGE_RATE")),
        "broker": q(g("BROKER")), "notes": q(g("NOTES")),
        "review_status": "'APPROVED'", "goes_live_at": "NOW()",
    }
    keys = ",".join(cols.keys()); vals = ",".join(cols.values())
    upd = ",".join(f"{k}=EXCLUDED.{k}" for k in cols if k != "ref")
    W(f"INSERT INTO public.cargo_listings ({keys}) VALUES ({vals}) "
      f"ON CONFLICT (ref) DO UPDATE SET {upd};")

W("")
W("ALTER TABLE public.vessel_availability ENABLE TRIGGER USER;")
W("ALTER TABLE public.cargo_listings    ENABLE TRIGGER USER;")
W("COMMIT;")
W(f"-- cargo rows skipped (no ref / no qty): {skipped}")

with open(OUT, "w") as f:
    f.write("\n".join(out) + "\n")
print(f"Wrote {OUT}: {len(out)} lines, {len(port_locodes)} ports, "
      f"{len(open_vessels)} open positions, cargo skipped={skipped}")
