"""Usage: python scripts/pda-wave2-generate.py <repo root>

Generate 20261007300000_pda_flag_treatment.sql and its DOWN from the PR-10a
definition of pda_replace_tariff_rules, so the redefinition is a verbatim copy
plus the Wave 2 change (owner directive B2C-033): flagTreatments
('foreign' | 'national') becomes an applicability condition, validated exactly
like the other two-value lists (settlementModes)."""
import pathlib
import sys

repo = pathlib.Path(sys.argv[1])
mig = repo / "supabase" / "migrations"
pr10a = (mig / "20261006300000_pda_compound_bases.sql").read_text(encoding="utf8").replace("\r\n", "\n")


def extract(src: str, name: str, sig: str) -> str:
    start = src.index(f"create or replace function public.{name}(")
    end_body = src.index("\n$$;\n", start) + len("\n$$;\n")
    tail = src[end_body:]
    grants = []
    for line in tail.split("\n"):
        if line.startswith(("revoke ", "grant ")) and f"public.{name}({sig})" in line:
            grants.append(line)
        elif line.strip() == "":
            if grants:
                break
            continue
        else:
            break
    return src[start:end_body] + "\n".join(grants) + "\n"


def patch(text: str, pairs):
    for a, b in pairs:
        assert text.count(a) == 1, (a[:90], text.count(a))
        text = text.replace(a, b)
    return text


old_replace = extract(pr10a, "pda_replace_tariff_rules", "uuid, uuid, jsonb")
LISTS = "'requestedServices','vesselTypes','cargoTypes','cargoStatuses','voyageScopes','locations','percentageBaseCodes','settlementModes'"

new_replace = patch(old_replace, [
    ("'minDraftM','maxDraftM','minCargoQuantityMt','maxCargoQuantityMt','percentageBaseCodes','settlementModes')) then",
     "'minDraftM','maxDraftM','minCargoQuantityMt','maxCargoQuantityMt','percentageBaseCodes','settlementModes','flagTreatments')) then"),
    (f"      where e.key in ({LISTS})\n        and (jsonb_typeof(e.value) <> 'array'",
     f"      where e.key in ({LISTS},'flagTreatments')\n        and (jsonb_typeof(e.value) <> 'array'"),
    (f"      where e.key in ({LISTS})\n        and (jsonb_array_length(e.value) > 100",
     f"      where e.key in ({LISTS},'flagTreatments')\n        and (jsonb_array_length(e.value) > 100"),
    ("       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,settlementModes}','[]'::jsonb)) item(value) where item.value not in ('cash','agent_account'))",
     "       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,settlementModes}','[]'::jsonb)) item(value) where item.value not in ('cash','agent_account'))\n"
     "       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,flagTreatments}','[]'::jsonb)) item(value) where item.value not in ('foreign','national'))"),
    ("      where e.key in ('cargoStatuses','voyageScopes','locations','settlementModes')\n        and (jsonb_array_length(e.value) > 2",
     "      where e.key in ('cargoStatuses','voyageScopes','locations','settlementModes','flagTreatments')\n        and (jsonb_array_length(e.value) > 2"),
])

up = f"""-- PDA Wave 2 (owner directive B2C-033; implemented by Opus B, audited by Codex).
--  * flagTreatments ('foreign' | 'national') becomes an applicability condition.
--    The app derives the treatment from the vessel's flag state (ISO 3166-1
--    alpha-2, resolved server-side through public.flag_states) and the port's
--    country (the first two letters of its UN/LOCODE): equal = national,
--    different = foreign. A rule that names a treatment while the flag state is
--    unknown raises MISSING_INPUT; it is never guessed.
--  * Egypt Decree 488/2015 charges foreign-flag vessels in USD and national
--    vessels in EGP; the foreign-USD package declares flagTreatments ['foreign'].
-- pda_replace_tariff_rules is the 20261006300000 body, copied verbatim with only
-- this change (generated by scripts/pda-wave2-generate.py; rerun it to reproduce).
-- get_pda_calculation_context needs no change: applicability is returned as stored.

{new_replace}"""

down = f"""-- DOWN for 20261007300000_pda_flag_treatment (PDA Wave 2). Refuses while any
-- stored rule uses flagTreatments (export and replace those rules first), then
-- restores the 20261006300000 body of pda_replace_tariff_rules verbatim.
do $down$
begin
  if exists (select 1 from public.port_tariff_rules where applicability ? 'flagTreatments') then
    raise exception 'PDA_DOWN: flag treatment is in use by stored tariff rules; export and replace those rules first'
      using errcode = '55000';
  end if;
end
$down$;

{old_replace}"""

(mig / "20261007300000_pda_flag_treatment.sql").write_text(up, encoding="utf8", newline="\n")
(repo / "supabase" / "rollback" / "20261007300000_pda_flag_treatment_down.sql").write_text(down, encoding="utf8", newline="\n")
print("written", len(up), len(down))
