// Country names for the flag-state picker and P&I-club list. The flag field is
// a searchable suggestion list (datalist) — free text is still allowed, so this
// list does not have to be exhaustive to be useful. Common maritime flag states
// are listed first so they surface at the top of the suggestions.

export const FLAG_STATES: readonly string[] = [
  // Common flag-of-convenience / open registries (this trade)
  "Panama",
  "Liberia",
  "Marshall Islands",
  "Comoros",
  "Togo",
  "Palau",
  "Tanzania",
  "Sierra Leone",
  "Cook Islands",
  "St. Vincent & Grenadines",
  "Belize",
  "Moldova",
  "Cameroon",
  "Gabon",
  "Malta",
  "Cyprus",
  "Antigua & Barbuda",
  // Regional / national registries
  "Egypt",
  "Saudi Arabia",
  "United Arab Emirates",
  "Turkey",
  "Greece",
  "Lebanon",
  "Syria",
  "Iraq",
  "Iran",
  "Kuwait",
  "Qatar",
  "Bahrain",
  "Oman",
  "Yemen",
  "Jordan",
  "Sudan",
  "Djibouti",
  "Somalia",
  "Eritrea",
  "Libya",
  "Tunisia",
  "Algeria",
  "Morocco",
  "Malaysia",
  "Singapore",
  "Indonesia",
  "India",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "China",
  "Hong Kong",
  "Vietnam",
  "Thailand",
  "Philippines",
  "South Korea",
  "Japan",
  "Russia",
  "Ukraine",
  "Georgia",
  "Romania",
  "Bulgaria",
  "Italy",
  "Spain",
  "Portugal",
  "France",
  "Netherlands",
  "Belgium",
  "Germany",
  "United Kingdom",
  "Norway",
  "Denmark",
  "Sweden",
  "Finland",
  "Poland",
  "Croatia",
  "Montenegro",
  "Albania",
  "United States",
  "Brazil",
  "Nigeria",
  "Ghana",
  "Ivory Coast",
  "Senegal",
  "Mauritania",
  "Kenya",
  "South Africa",
  "Australia",
];

// The 12 International Group P&I clubs, plus common fixed-premium alternatives.
// The P&I field also allows free text for any insurer not listed.
export const PI_CLUBS: readonly string[] = [
  "Gard",
  "UK P&I Club",
  "Steamship Mutual",
  "Britannia P&I",
  "Skuld",
  "The Standard Club",
  "North of England (NorthStandard)",
  "The American Club",
  "Japan P&I Club",
  "London P&I Club",
  "Shipowners' Club",
  "Swedish Club",
  "West of England",
  // Common fixed-premium / non-IG insurers
  "Ingosstrakh",
  "MECOMS",
  "Turkish P&I",
  "Other / Fixed-premium",
];
