-- PDA Wave 2 (owner directive B2C-033; implemented by Opus B, audited by Codex).
--  * flagTreatments ('foreign' | 'national') becomes an applicability condition.
--    The app derives the treatment from the vessel's flag state (ISO 3166-1
--    alpha-2, resolved server-side through public.flag_states) and the port's
--    country (the first two letters of its UN/LOCODE): equal = national,
--    different = foreign. A rule that names a treatment while the flag state is
--    unknown raises MISSING_INPUT; it is never guessed.
--  * Egypt Decree 488/2015 charges foreign-flag vessels in USD and national
--    vessels in EGP; the foreign-USD package declares flagTreatments ['foreign'].
-- pda_replace_tariff_rules is the 20261006300000 body, copied verbatim with only
-- this change (generated by scripts/pda-wave2-generate.py; rerun it to reproduce).
-- get_pda_calculation_context needs no change: applicability is returned as stored.

create or replace function public.pda_replace_tariff_rules(p_actor uuid, p_version_id uuid, p_rules jsonb)
returns integer
language plpgsql security definer set search_path to ''
as $$
declare
  v_status text;
  v_rule jsonb;
  v_band jsonb;
  v_pair record;
  v_rule_id uuid;
  v_count integer := 0;
begin
  perform public.fn_pda_assert_admin_actor(p_actor);
  select status into v_status from public.port_tariff_versions where id = p_version_id and created_by = p_actor for update;
  if v_status is null then raise exception 'PDA_NOT_FOUND: tariff version not found' using errcode = 'P0002'; end if;
  if v_status <> 'draft' then raise exception 'PDA_IMMUTABLE: submitted or published rules cannot change' using errcode = '55000'; end if;
  if jsonb_typeof(p_rules) <> 'array' or jsonb_array_length(p_rules) = 0 then
    raise exception 'PDA_INPUT: at least one rule is required' using errcode = '22023';
  end if;

  delete from public.port_tariff_rules where tariff_version_id = p_version_id;
  for v_rule in select value from jsonb_array_elements(p_rules) loop
    if jsonb_typeof(coalesce(v_rule->'applicability','{}'::jsonb)) <> 'object'
       or exists (select 1 from jsonb_object_keys(coalesce(v_rule->'applicability','{}'::jsonb)) k
         where k not in ('requestedServices','vesselTypes','cargoTypes','cargoStatuses','voyageScopes','locations',
           'minGt','maxGt','minNt','maxNt','minScnrt','maxScnrt','minDwt','maxDwt','minLoaM','maxLoaM',
           'minDraftM','maxDraftM','minCargoQuantityMt','maxCargoQuantityMt','percentageBaseCodes','settlementModes','flagTreatments')) then
      raise exception 'PDA_APPLICABILITY: % has unsupported applicability fields', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_each(coalesce(v_rule->'applicability','{}'::jsonb)) e
      where e.key in ('requestedServices','vesselTypes','cargoTypes','cargoStatuses','voyageScopes','locations','percentageBaseCodes','settlementModes','flagTreatments')
        and (jsonb_typeof(e.value) <> 'array' or exists (select 1 from jsonb_array_elements(e.value) x where jsonb_typeof(x) <> 'string'))) then
      raise exception 'PDA_APPLICABILITY: % list fields must be string arrays', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_each(coalesce(v_rule->'applicability','{}'::jsonb)) e
      where (e.key like 'min%' or e.key like 'max%') and jsonb_typeof(e.value) <> 'number') then
      raise exception 'PDA_APPLICABILITY: % ranges must be numeric', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_each(coalesce(v_rule->'applicability','{}'::jsonb)) e
      where e.key in ('requestedServices','vesselTypes','cargoTypes','cargoStatuses','voyageScopes','locations','percentageBaseCodes','settlementModes','flagTreatments')
        and (jsonb_array_length(e.value) > 100 or exists (
          select 1 from jsonb_array_elements_text(e.value) item(value)
          where length(trim(item.value)) not between 1 and 120
        ))) then
      raise exception 'PDA_APPLICABILITY: % list fields contain too many or invalid values', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,cargoStatuses}','[]'::jsonb)) item(value) where item.value not in ('laden','ballast'))
       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,voyageScopes}','[]'::jsonb)) item(value) where item.value not in ('domestic','international'))
       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,locations}','[]'::jsonb)) item(value) where item.value not in ('alongside','anchorage'))
       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,settlementModes}','[]'::jsonb)) item(value) where item.value not in ('cash','agent_account'))
       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,flagTreatments}','[]'::jsonb)) item(value) where item.value not in ('foreign','national'))
       or exists (select 1 from jsonb_array_elements_text(coalesce(v_rule#>'{applicability,percentageBaseCodes}','[]'::jsonb)) item(value) where item.value !~ '^[a-z][a-z0-9_]{1,79}$') then
      raise exception 'PDA_APPLICABILITY: % contains an unsupported enumerated value or rule code', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_each(coalesce(v_rule->'applicability','{}'::jsonb)) e
      where (e.key like 'min%' or e.key like 'max%') and (e.value #>> '{}')::numeric < 0) then
      raise exception 'PDA_APPLICABILITY: % ranges cannot be negative', v_rule->>'code' using errcode = '22023';
    end if;
    for v_pair in select * from (values
      ('minGt','maxGt'), ('minNt','maxNt'), ('minScnrt','maxScnrt'), ('minDwt','maxDwt'),
      ('minLoaM','maxLoaM'), ('minDraftM','maxDraftM'), ('minCargoQuantityMt','maxCargoQuantityMt')
    ) as pairs(min_key, max_key) loop
      if (v_rule->'applicability') ? v_pair.min_key and (v_rule->'applicability') ? v_pair.max_key
         and (v_rule#>>array['applicability',v_pair.min_key])::numeric > (v_rule#>>array['applicability',v_pair.max_key])::numeric then
        raise exception 'PDA_APPLICABILITY: % has an inverted %/% range', v_rule->>'code', v_pair.min_key, v_pair.max_key using errcode = '22023';
      end if;
    end loop;
    if nullif(v_rule->>'unit','') is not null
       and (v_rule->>'unit') not in ('gt','nt','scnrt','dwt','loa_m','days','hours','units','cargo_mt') then
      raise exception 'PDA_UNIT: % has an unsupported unit', v_rule->>'code' using errcode = '22023';
    end if;
    if (v_rule->>'basis') in ('tiered_flat','tiered_rate','progressive')
       and nullif(v_rule->>'unit','') is null then
      raise exception 'PDA_UNIT: % requires a supported band unit', v_rule->>'code' using errcode = '22023';
    end if;
    if exists (select 1 from jsonb_each(coalesce(v_rule->'applicability','{}'::jsonb)) e
      where e.key in ('cargoStatuses','voyageScopes','locations','settlementModes','flagTreatments')
        and (jsonb_array_length(e.value) > 2
             or (select count(distinct x.value) from jsonb_array_elements_text(e.value) x(value)) <> jsonb_array_length(e.value))) then
      raise exception 'PDA_APPLICABILITY: % two-value lists take each value at most once', v_rule->>'code' using errcode = '22023';
    end if;
    -- PR-10a: duration rounding is declared per rule; existing rules default to exact, unit 1.
    if nullif(v_rule->>'rounding','') is not null and (v_rule->>'rounding') not in ('exact','started') then
      raise exception 'PDA_ROUNDING: % rounding must be exact or started', v_rule->>'code' using errcode = '22023';
    end if;
    if nullif(v_rule->>'unitSize','') is not null and (jsonb_typeof(v_rule->'unitSize') <> 'number' or (v_rule->>'unitSize')::numeric <= 0) then
      raise exception 'PDA_ROUNDING: % unit size must be a positive number', v_rule->>'code' using errcode = '22023';
    end if;
    if (v_rule->>'basis') = 'percentage'
       and jsonb_array_length(coalesce(v_rule#>'{applicability,percentageBaseCodes}','[]'::jsonb)) = 0 then
      raise exception 'PDA_PERCENTAGE: % requires at least one base code', v_rule->>'code' using errcode = '22023';
    end if;
    insert into public.port_tariff_rules (
      tariff_version_id, code, label, basis, amount, rate, unit, priority,
      included_units, minimum_amount, maximum_amount, tax_percent, applicability,
      manual_instructions, source_id, source_page, source_sheet, source_excerpt,
      duration_rounding, unit_size
    ) values (
      p_version_id, v_rule->>'code', v_rule->>'label', v_rule->>'basis',
      nullif(v_rule->>'amount','')::numeric, nullif(v_rule->>'rate','')::numeric,
      nullif(v_rule->>'unit',''), coalesce((v_rule->>'priority')::integer, 100),
      coalesce(nullif(v_rule->>'includedUnits','')::numeric, 0),
      nullif(v_rule->>'minimumAmount','')::numeric, nullif(v_rule->>'maximumAmount','')::numeric,
      nullif(v_rule->>'taxPercent','')::numeric, coalesce(v_rule->'applicability', '{}'::jsonb),
      nullif(v_rule->>'manualInstructions',''), (v_rule->>'sourceId')::uuid,
      nullif(v_rule->>'sourcePage',''), nullif(v_rule->>'sourceSheet',''), nullif(v_rule->>'sourceExcerpt',''),
      coalesce(nullif(v_rule->>'rounding',''), 'exact'), coalesce(nullif(v_rule->>'unitSize','')::numeric, 1)
    ) returning id into v_rule_id;
    for v_band in select value from jsonb_array_elements(coalesce(v_rule->'bands', '[]'::jsonb)) loop
      insert into public.port_tariff_bands (
        rule_id, band_order, lower_bound, upper_bound, flat_amount, rate
      ) values (
        v_rule_id, (v_band->>'order')::integer, (v_band->>'lowerBound')::numeric,
        nullif(v_band->>'upperBound','')::numeric, nullif(v_band->>'flatAmount','')::numeric,
        nullif(v_band->>'rate','')::numeric
      );
    end loop;
    if (v_rule->>'basis') in ('tiered_flat','tiered_rate','progressive') then
      if not exists (select 1 from public.port_tariff_bands where rule_id = v_rule_id) then
        raise exception 'PDA_BANDS: % requires at least one band', v_rule->>'code' using errcode = '22023';
      end if;
      if exists (
        select 1 from (
          select band_order, lower_bound, upper_bound,
            lag(upper_bound) over (order by band_order) as prior_upper,
            row_number() over (order by band_order) as position,
            count(*) over () as band_count
          from public.port_tariff_bands where rule_id = v_rule_id
        ) b
        where (b.position = 1 and b.lower_bound <> 0)
           or (b.position > 1 and b.lower_bound is distinct from b.prior_upper)
           or (b.position < b.band_count and b.upper_bound is null)
           or (b.position = b.band_count and b.upper_bound is not null)
      ) then
        raise exception 'PDA_BANDS: % bands must start at zero, be contiguous and end open', v_rule->>'code' using errcode = '22023';
      end if;
      if (v_rule->>'basis') in ('tiered_rate','progressive') and exists (
        select 1 from public.port_tariff_bands where rule_id = v_rule_id and rate is null
      ) then
        raise exception 'PDA_BANDS: % requires a rate in every band', v_rule->>'code' using errcode = '22023';
      end if;
    end if;
    v_count := v_count + 1;
  end loop;
  if exists (
    select 1 from public.port_tariff_rules r
    cross join lateral jsonb_array_elements_text(coalesce(r.applicability->'percentageBaseCodes','[]'::jsonb)) base(code)
    left join public.port_tariff_rules prior on prior.tariff_version_id = r.tariff_version_id and prior.code = base.code
    where r.tariff_version_id = p_version_id and r.basis = 'percentage'
      and (prior.id is null or prior.priority >= r.priority)
  ) then
    raise exception 'PDA_PERCENTAGE: every base code must be a lower-priority rule in the same version' using errcode = '22023';
  end if;
  return v_count;
end;
$$;
revoke all on function public.pda_replace_tariff_rules(uuid, uuid, jsonb) from public, anon, authenticated;
grant execute on function public.pda_replace_tariff_rules(uuid, uuid, jsonb) to service_role;
