-- ════════════════════════════════════════════════════════════════════
-- Cargo classification — Part 7: resolve the 92 UNMAPPED cargoes  · append-only
--
-- Source: ArabShipBroker_UNIFIED_Cargo_Vessel_Map.xlsx (01_CARGO), where 92 of
-- 731 listings carried ASB_RESOLVE_FLAG = "UNMAPPED — add to master map" — i.e.
-- their market name was absent from commodity_map, so resolve_cargo_classification
-- returned UNMAPPED. This adds those 33 distinct commodities to the resolver
-- dictionary so all 731 reference cargoes resolve to a regime + code.
--
-- Each row is derived data-drivenly by the workbook's OWN rule (same as the
-- 000700 derivation): GRAIN if grain; CSS if the commodity is shipped break-bulk;
-- else IMSBC. Codes come from the authoritative dictionaries already seeded:
--   • CSS  → 08_CLASS_CSS market_aliases (steel→CSS-06/07, project/heavy→CSS-05,
--            wheel→CSS-04, unit-load/bagged→CSS-12)
--   • IMSBC→ 07_CLASS_IMSBC exact BCSN match (Alumina, Clay, …)
-- Dual-form commodities (shipped both bulk and break-bulk — Gypsum, Soda Ash,
-- Anthracite, Boron, Feldspar, Sulphur, Phosphate, …) carry plausible_regimes
-- {CSS,IMSBC} so the server-side guard accepts either, and the resolver picks the
-- live regime from the is_bulk flag at call time.
--
-- Pure reference/lookup data; firewall untouched; idempotent (ON CONFLICT).
-- Depends on …000701 (commodity_map table + base dictionary).
-- ════════════════════════════════════════════════════════════════════

INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Alumina','IMSBC'::public.cargo_regime_enum,'ALUMINA',NULL,false,ARRAY['IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Ammonium Nitrate','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Anthracite','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk, Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Bitumen','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Boron Products','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk, Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Calcite','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Calcium Chloride','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Calcium Phosphate','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Chipboards','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Clay','IMSBC'::public.cargo_regime_enum,'CLAY',NULL,false,ARRAY['IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Coal Tar Pitch','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('DBIC','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Feldspar','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk, Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Fly Ash','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('General Cargo','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Glass','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Granite Blocks','CSS'::public.cargo_regime_enum,'CSS-05',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Gypsum','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk, Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Hot Rolled Coils','CSS'::public.cargo_regime_enum,'CSS-06',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Kaolin','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('MDF Boards','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Marble Chips','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Mixed BB','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Olive Stone','CSS'::public.cargo_regime_enum,'CSS-12',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Phosphate','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Project Cargo','CSS'::public.cargo_regime_enum,'CSS-05',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Shredded Tyres','CSS'::public.cargo_regime_enum,'CSS-04',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Soda Ash','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk, Dry Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Debars','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Plates','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Sheets','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Steel Slabs','CSS'::public.cargo_regime_enum,'CSS-07',NULL,false,ARRAY['CSS'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
INSERT INTO public.commodity_map (market_name,regime,code,group_cat,is_dual_form,plausible_regimes,note) VALUES ('Sulphur','CSS'::public.cargo_regime_enum,'CSS-12',NULL,true,ARRAY['CSS'::public.cargo_regime_enum,'IMSBC'::public.cargo_regime_enum],'Auto-resolved from UNIFIED workbook (unmapped cargo). Observed as: Break Bulk.') ON CONFLICT (market_name) DO NOTHING;
